### ISSUE TITLE
Tag New v6.2.4?

### ISSUE THREAD

**Issue by jianjye** [solariumphp/solarium#1000]
In the current master branch, both `symfony/event-dispatcher-contracts` and `symfony/event-dispatcher` have new versions added which are important for Laravel 9 apps. Can we tag a new version since they are already in master?

**Comment by thomascorthals** [comment]
@jianjye [Solarium 6.2.4](https://github.com/solariumphp/solarium/releases/tag/6.2.4) was released today.
