### ISSUE TITLE
 Uncaught Error: Class "Symfony\Component\EventDispatcher\EventDispatcher" not found

### ISSUE THREAD

**Issue by Generalize** [solariumphp/solarium#1005]
**Solarium version(s) affected**: x.y.z
**Solr version**:"^6.2" 

**Description**  

 Uncaught Error: Class "Symfony\Component\EventDispatcher\EventDispatcher" not found
**How to reproduce**  

`<?php
require_once 'vendor/autoload.php';
$adapter = new Solarium\Core\Client\Adapter\Curl();
$eventDispatcher = new Symfony\Component\EventDispatcher\EventDispatcher();
$config = array(
    'endpoint' => array(
        'localhost' => array(
            'host' => '127.0.0.1',
            'port' => 8983,
            'path' => '/',
            'core' => 'torrent',
        )
    )
);
$client = new Solarium\Client($adapter, $eventDispatcher, $config);
$query = $client->createQuery($client::QUERY_SELECT);
$resultset = $client->execute($query);
echo 'NumFound: '.$resultset->getNumFound();
foreach ($resultset as $document) {
    foreach ($document as $field => $value) {
	    var_dump($document);
    }
    exit;
}
`
**Possible Solution**  

**Additional context**  

`composer.json
{
    "require": {
	    "illuminate/database": "^9.14",
        "solarium/solarium": "^6.2" 
    }
}`

**Comment by thomascorthals** [comment]
Solarium accepts any PSR-15 compatible event dispatcher. It's up to you to `require` one in your project's `composer.json`.

```json
{
    "require": {
        "illuminate/database": "^9.14",
        "solarium/solarium": "^6.2",
        "symfony/event-dispatcher": "^5.0"
    }
}
```

This isn't really obvious from the documentation.
