### ISSUE TITLE
check ping sucessful and failed 

### ISSUE THREAD

**Issue by hardiyanto33** [solariumphp/solarium#101]
Please help me.

Got this info when check solarium availability and ping Solr:
Solarium library version: 2.4.0 - Ping query successful
Ping query failed

And this info:
Fatal error: Uncaught exception 'Solarium_Exception' with message 'Solr JSON response could not be decoded' in /var/www/solarium/library/Solarium/Result.php:139 Stack trace: #0 /var/www/solarium/library/Solarium/Client/ResponseParser/Select.php(56): Solarium_Result->getData() #1 /var/www/solarium/library/Solarium/Result/QueryType.php(73): Solarium_Client_ResponseParser_Select->parse(Object(Solarium_Result_Select)) #2 /var/www/solarium/library/Solarium/Result/Select.php(143): Solarium_Result_QueryType->_parseResponse() #3 /var/www/solarium/examples/1.2-basic-select.php(16): Solarium_Result_Select->getNumFound() #4 {main} thrown in /var/www/solarium/library/Solarium/Result.php on line 139 

Thanks
Hardi

**Comment by ahsankhan201** [comment]
i dont know where is the bugg..
 Uncaught exception 'Solarium\Exception\UnexpectedValueException' with message 'Solr JSON response could not be decoded'

when i run ping code it shows status 200 ok but on simple select it shows this error.

another issue is that. 
$config = array(
    'endpoint' => array(
        'localhost' => array(
            'host' => 'localhost',
            'port' => 8983,
            'path' => '/solr/#/',
        )
    )
);
when i set path to '/solr/' it shows 404 error.

Thanks

**Comment by basdenooijer** [comment]
Are you able to use Solr directly? For instance in your browser? If so, what is the URL for a succesful query? I might be able to help you translate that into a working config.

**Comment by Ansaldos** [comment]
I'm facing with the same issue.
If i set path to '/solr/#' i get.

`Solarium library version: 2.4.0 - Ping query successful
Ping query failedSolarium_Exception: Solr JSON response could not be decoded in C:\xampp\htdocs\www\OpenSemanticSearch Solarium PHP\vendor\solarium\solarium\library\Solarium\Result.php:139
Stack trace:
#0 C:\xampp\htdocs\www\OpenSemanticSearch Solarium PHP\vendor\solarium\solarium\examples\1.1-check-solarium-and-ping.php(20): Solarium_Result->getData()
#1 {main}`

And if i set path to '/solr' i got the 404 error message.
