### ISSUE TITLE
Solarium 6.2.4 declares itself as 6.2.3

### ISSUE THREAD

**Issue by thomascorthals** [solariumphp/solarium#1012]
**Solarium version affected**: 6.2.4

**Description**  
Solarium 6.2.4 accidentally declares itself as 6.2.3.

https://github.com/solariumphp/solarium/blob/fcec5684ee3f2d73a8f06a9fbd0e25d2537e1ab2/src/Client.php#L44

**How to reproduce**
```php
echo Solarium\Client::VERSION;
```

**Possible Solution**
Release Solarium 6.2.5 with correct version.

**Additional context**
This has happened before with Solarium 6.1.0.

https://github.com/solariumphp/solarium/blob/fcec5684ee3f2d73a8f06a9fbd0e25d2537e1ab2/CHANGELOG.md#L156

**Comment by mkalkbrenner** [comment]
Once again :-(

Do you have an idea how to avoid this?

**Comment by thomascorthals** [comment]
Haven't been able to find a way to prevent a release from happening. But I did come up with a lightweight way to check if `Client::VERSION` matches the tag when a release is pushed.

Maybe someone with a better knowledge of workflows can do better. Ideally, a workflow that updates the verion in `CHANGELOG.md` and `src/Client.php`, tags and releases with that version, and prepares `CHANGELOG.md` with a new `[Unreleased]` section. That's way beyond me though.

**Comment by mkalkbrenner** [comment]
@thomascorthals Do you agree on the current version in master?
If yes we can prepare a new release.

But maybe we should add some logic in the tests to get them to pass locally.

**Comment by thomascorthals** [comment]
Current version looks good. I opened a PR to adjust the examples accordingly, fix a comment typo, and test that Client::VERSION matches Client::getVersion().

**Comment by mkalkbrenner** [comment]
@thomascorthals I merged it. Should I go for 6.2.5 now?

**Comment by thomascorthals** [comment]
@mkalkbrenner Go for it!
