### ISSUE TITLE
ParallelExecution doesn't honour PostBigRequest

### ISSUE THREAD

**Issue by thomascorthals** [solariumphp/solarium#1015]
### Discussed in https://github.com/solariumphp/solarium/discussions/1014

<div type='discussions-op-text'>

<sup>Originally posted by **leuchtdiode** July 14, 2022</sup>
Hi,

I'm using the PostBigRequest plugin in my Solarium client which is working fine with my "miles long queries".

But it looks like in combination with ParallelExecution the plugin gets omitted?

The result after executing in parallel throws "Request URI too long".

Is it possible to combine these two plugins?

Thx & BR,
Alex</div>

**Comment by leuchtdiode** [comment]
Is there a possibility to adapt this?

**Comment by thomascorthals** [comment]
I have a working fix over at https://github.com/thomascorthals/solarium/tree/parallelexecution but it runs into an issue with the integration test against Solr 9. I'll open a PR once that is sorted out.

**Comment by leuchtdiode** [comment]
Nice, thank you :)

**Comment by leuchtdiode** [comment]
Wow, it's insane. My request is now twice as fast with parallel execution on :)
