### ISSUE TITLE
Solarium distance facets query causes syntax error in Solr request

### ISSUE THREAD

**Issue by AACars** [solariumphp/solarium#1050]
Our website helps users to find used cars. It heavily relies on Solr’s spatial searches to enable users to find vehicles within a certain radius of travel. We use Solarium to display advanced facets that allow users to filter the search results.
Since version **6.2.3** we have found that Solarium builds Solr requests that result in the following error:

> SyntaxError: Cannot parse 'geodist()'

The above error comes as a result of building a distance facet that allows us to limit search results by distance:
`createFacetQuery('distance10 frange l=0 u=10')->setQuery('geodist()');`

This code works fine in **6.2.2**, but it breaks in **6.2.3**.
I believe using frange is the correct way of building distance facets in Solr.

After further investigation I have found that there is an issue related to Solarium adding single quotes to the facet query’s key.

Version **6.2.2** (correct): 

> facet.query={!key=distance10 frange l=0 u=10}geodist()

Version **6.2.3** (incorrect): 

> facet.query={!key='distance10 frange l=0 u=10'}geodist()

Here is the code that allows the issue to be reproduced:
```
$query = $client->createSelect();


$spatial = $query->getSpatial();
$spatial->setField("position");
$spatial->setPoint("51.7879284,0.006627");


$facetSet = $query->getFacetSet();
$facetSet->createFacetQuery('distance10 frange l=0 u=10')->setQuery('geodist()');
$facetSet->createFacetQuery('distance20 frange l=0 u=20')->setQuery('geodist()');


$resultset = $client->execute($query);


$data = $resultset->getData();
foreach ($data['facet_counts']['facet_queries'] as $range => $count) {
   echo $range . " [" . $count . "]\n";
}
```
Here are additional details of the environment we use:

- Solr: 8.2.0 (but we experienced the same issue with a higher version of Solr)
- solarium: 6.2.3
- PHP: 8.1.2
- Ubuntu: 22.04

Here is a simplified version of the schema that we use:

```
<schema name="default-config" version="1.6">
   <field name="make" type="string" indexed="false" stored="true" multiValued="false" omitNorms="true" />
   <field name="model" type="string" indexed="false" stored="true" multiValued="false" omitNorms="true" />
   <field name="position" type="location" indexed="true" stored="true" multiValued="false" omitNorms="true" />
</schema>
```

Can you advise if the new version of Solarium can support building distance facets that would generate the desired Solr requests for our use case?

**Comment by thomascorthals** [comment]
Looks like a regression introduced by #976.

**Comment by thomascorthals** [comment]
@AACars It seems it was more of a coincidence that this did work in Solarium 6.2.2. If you use `createFacetQuery()` with a string argument, that argument is supposed to be the facet key. Because those keys weren't escaped properly before, it just happened to work for your use case.

You should be able to get the desired result with both 6.2.2 and 6.2.3 if you select the frange query parser in `setQuery()` instead.

```php
$facetSet = $query->getFacetSet();
$facetSet->createFacetQuery('distance10')->setQuery('{!frange l=0 u=10}geodist()');
$facetSet->createFacetQuery('distance20')->setQuery('{!frange l=0 u=20}geodist()');
```
