### ISSUE TITLE
Add missing exclude support to facet fields

### ISSUE THREAD

**Issue by SebastianAppel** [solariumphp/solarium#1056]
**Solarium version(s) affected**: 6.2.8
**Solr version**:9.1.1

**Description**  
Solarium doesn't seem to support excludes in facet fields

**How to reproduce**  
$query->getFacetSet()->createFacetField('foo')->setField('bar')->addExclude('foobar')

**Possible Solution**  
Add support to src/Component/Facet/AbstractFacet.php:

```php
/**
     * Add an exclude
     *
     * @param string $exclude
     *
     * @return self Provides fluent interface
     */
    public function addExclude(string $exclude): FacetInterface
    {
        $this->getLocalParameters()->setExclude($exclude);

        return $this;
    }
```

**Additional context**

**Comment by thomascorthals** [comment]
I wonder if we would should provide convenience methods like that for the full set/add/remove/clear functionality that `LocalParameters` implements? Or just a `setExcludes()` to set them all in one go? You can always use `LocalParameters` anyway if you need finer control.

Same goes for `terms` while we're at it.

**Comment by SebastianAppel** [comment]
True. My point however is that it would be much more consistent with the fluent interface design. With the above mentioned functionality adding an exclude to a facet field would not require an additional call but could be done on the fly and still return the facet field instead of the local parameters object.

**Comment by jan-edge** [comment]
There is a way to add excludes to a FacetField, but it is not pretty and feels forced:
`$query->getFacetSet()->createFacetField(['local_key' => 'foo', 'local_exclude' => ['foobar']])->setField('bar');`

When working with a FacetSet with 3 different facet types, we now need 3 different methods to add excludes:
facet field: `->setOptions(['local_key' => 'foo', 'local_exclude' => ['foobar']]);`
range field: -`>setOptions(['exclude' => ['foobar']]);`
multiQuery: `->addExclude('foobar');`

Am i doing something wrong, or is this unnecessarily complex? Please tell me i'm doing it wrong.

**Comment by thomascorthals** [comment]
> Am i doing something wrong, or is this unnecessarily complex? Please tell me i'm doing it wrong.

This is unnecessarily complex because there is no fluent interface for the excludes.

I have a working implementation in my fork: https://github.com/thomascorthals/solarium/tree/facet. That will make it fluent and consistent between the different facet types. Holding out on a PR because it'll have merge conflicts with another PR I have open.

There is no separate option `exclude` for range fields, I think you have that confused with `include`?

**Comment by jan-edge** [comment]
Awesome! I'll have a look.

> There is no separate option `exclude` for range fields, I think you have that confused with `include`?

I just double checked, and the `->setOptions(['exclude' => ['foobar']]);` on range field does seem to work. (v6.2.8).

```
$facetSet->createFacetRange($field)->setField($field)
         ->setStart(0)
         ->setEnd(2000)
         ->setOptions(['exclude' => [$field]])
         ->setGap(50);
```

**Comment by thomascorthals** [comment]
> I just double checked, and the `->setOptions(['exclude' => ['foobar']]);` on range field does seem to work. (v6.2.8).

Indeed it does. This way of setting it was deprecated for other facet types in Solr 5 and removed in Solr 6. This might have been an oversight, I don't think there's an actual reason to keep it around just for ranges. @wickedOne can confirm this.

Anyway, `local_exclude` works for range facets too so in that way it is already compatible with field facets.

**Comment by wickedOne** [comment]
it's been a while, but as far as i can remember there wasn't an exception to the local params implementation so if there still is some sort of implementation suggesting otherwise it indeed is an oversight

**Comment by thomascorthals** [comment]
I've deprecated the `exclude` option in my branch.

**Comment by thomascorthals** [comment]
[Solarium 6.3.0](https://github.com/solariumphp/solarium/releases/tag/6.3.0) has been released with support for setting excludes (and terms) fluently on facet fields.
