### ISSUE TITLE
PHP 8.2: Deprecated notices in Core/Query/Result/QueryType.php 

### ISSUE THREAD

**Issue by michelaerts** [solariumphp/solarium#1063]
**Solarium version(s) affected**: 6.2.8

**Description**  
Following deprecated notices:

PHP-ERROR.NOTICE: Creation of dynamic property Solarium\QueryType\Server\CoreAdmin\Result\Result::$responseHeader is deprecated - Core/Query/Result/QueryType.php line 56

PHP-ERROR.NOTICE: Creation of dynamic property Solarium\QueryType\Server\CoreAdmin\Result\Result::$initFailures is deprecated - Core/Query/Result/QueryType.php line 56

PHP-ERROR.NOTICE: Creation of dynamic property Solarium\QueryType\Server\CoreAdmin\Result\Result::$status is deprecated - Core/Query/Result/QueryType.php line 56

PHP-ERROR.NOTICE: Creation of dynamic property Solarium\QueryType\Server\CoreAdmin\Result\Result::$queryTime is deprecated - Core/Query/Result/QueryType.php line 56

**How to reproduce**  
```
$query = $solr->createCoreAdmin();
$query->setAction( $query->createStatus()->setCore( 'core' ) );
$result = $solr->coreAdmin( $query )->getStatusResult();
```

**Comment by thomascorthals** [comment]
Just a heads up: I'm working on this. Isn't limited to a single QueryType so I'm trying to fix them all at once.

**Comment by michelaerts** [comment]
tnx thomas!

**Comment by thomascorthals** [comment]
[Solarium 6.3.0](https://github.com/solariumphp/solarium/releases/tag/6.3.0) has been released with deprecation notices fixed for various QueryTypes.
