### ISSUE TITLE
How to define setSchema?

### ISSUE THREAD

**Issue by gixxy22** [solariumphp/solarium#1064]
Im having trouble trying to define the schema for a core, I can see there is an API to Solr using the Core Admin Query and the method: `setSchema`

I have set this to a filename but it doesnt appear to be using it. I also have `setConfigSet` set.

Does `setConfigSet `override `setSchema`?

In the defaultConfigSet there is a file `managed-schema.xml` whichy seems to be auto generated, but this seems to be setting my schemaType based on the first value found and then causing issues later on..

`"msg":"ERROR: [doc=24305908] Error adding field 'size'='77 ml' msg=For input string: \"77 ml\"",`

Is there a way to specify the schema type for my fields when creating/modifying a core?

**Comment by thomascorthals** [comment]
> Does `setConfigSet `override `setSchema`?

They are both addded to the request if both are set. You can echo the request that will be sent like this:

```php
$coreAdminQuery = $client->createCoreAdmin();

$createAction = $coreAdminQuery->createCreate();
$createAction->setConfigSet('myconfigset');
$createAction->setSchema('myschema');
$coreAdminQuery->setAction($createAction);

echo $coreAdminQuery->getRequestBuilder()->build($coreAdminQuery)->getUri();
// admin/cores?wt=json&json.nl=flat&action=CREATE&configSet=myconfigset&schema=myschema
```

Does this show the expected parameters for your code?

**Comment by thomascorthals** [comment]
@gixxy22 Were you able to verify if Solarium adds both parameters to the URL? If not, can you post your code so we can look into reproducing and fixing the problem?

**Comment by gixxy22** [comment]
I wasnt able to verify it, I instead used the Request API to send field schema to the managed-schema.xml file instead upon field creation, and turned off autoCreateFields using:

`'set-user-property' => [
                    'update.autoCreateFields' => false,
                ],`

**Comment by thomascorthals** [comment]
If that fixes it for you, I assume the issue can be closed as a "Solr thing" rather than a Solarium problem.
