### ISSUE TITLE
Missing Guzzle adapter

### ISSUE THREAD

**Issue by zuzuleinen** [solariumphp/solarium#1068]
Hi, 

I'm trying to update solarium/solarium from `~3.8.1` to `6.2.8`. Apart from other changes that are documented in the repo's Readme, in previous version there used to be a `Solarium\Core\Client\Adapter\Guzzle` adapter and I noticed it's missing in the 6.2.8. 

Are there any release notes regarding what to use as replacement for it? Thanks!

**Comment by thomascorthals** [comment]
You can use Guzzle with a PSR-18 adapter.

https://solarium.readthedocs.io/en/stable/client-and-adapters/#psr-18-adapter

**Comment by thomascorthals** [comment]
You're right that this isn't explicitly mentioned in the upgrade notes. I've opened a PR to add this to the `README`.
