### ISSUE TITLE
Drop Support of PHP 7 for 6.4.0

### ISSUE THREAD

**Issue by mkalkbrenner** [solariumphp/solarium#1080]
Drop Support of PHP 7 for 6.4.0

**Comment by thomascorthals** [comment]
That will break backward compatibility for users on PHP 7 with `"solarium/solarium": "^6.0"` as a requirement. Might be safer to release this as Solarium 7?

**Comment by mkalkbrenner** [comment]
Yes, this might be safer. On the other hand, we just need to adjust the PHP requirement within composer.json. So solarium 7.0 could be reserved for a bigger change without blocking us to leverage newer PHP features in 6.x. PHP 7 already reached EOL.

**Comment by thomascorthals** [comment]
Come to think of it, Composer probably just wouldn't go higher than the latest 6.3.x if you're still on PHP 7.
