### ISSUE TITLE
pseudo fields are not returned in the result object

### ISSUE THREAD

**Issue by rafkamonday** [solariumphp/solarium#1100]
I do not get pseudo fields like [elevated] returned in the result object. I use QueryElevationComponent and the editorialMarkerFieldName with value "elevated". Because it is pseudo field it is in the square brackets. When I use the solr admin pane to query my database  [elevated] returns me the value true or false. Solarium does not return the field [elevated]. 

Solr: 9.0.0
Solarium: 6.3.2
PHP:8.2

$resultSet = $client->select($query);
foreach ($resultSet as $result) {
    $id=$result->id;
    $elevated=$result->[elevated]; //expected to work in any way. But $result shows on raw output, that there is no attribut elevated

   }

**Comment by thomascorthals** [comment]
Unless you remove them explicitly, the component adds the transformers `[elevated]` and (if `markExcludes=true`) `[excluded]` to the field list of the request.

To get the value, you can either use curly braces to access the object property:
```php
$elevated = $result->{'[elevated]'};
```
or use array syntax:
```php
$elevated = $result['[elevated]'];
```

**Comment by rafkamonday** [comment]
mhm, it says: no [elevated]

This:
 array(25) { ["omitHeader"]=> string(4) "true" ["wt"]=> string(4) "json" ["json.nl"]=> string(4) "flat" ["q"]=> string(5) "myquery" ["start"]=> int(0) ["rows"]=> int(10) ["fl"]=> string(7) "*,score" ["defType"]=> string(6) "dismax" ["qf"]=> string(27) "one^1.7 two^1.5 three^0" ["mm"]=> string(5) "2<90%" ["pf"]=> string(7) "content" ["ps"]=> int(10) ["tie"]=> float(0.1000000000000000055511151231257827021181583404541015625) ["bq"]=> string(111) "source:x^1 source:y^2.5 source:z^3.5 source:one*^2 source:two^0.3" ["bf"]=> string(74) "recip(ms(NOW,lastModified),6.33e-11,1,1)^8 if(termfreq(title,'value'),0,9)" ["hl"]=> string(4) "true" ["hl.method"]=> string(7) "unified" ["hl.fl"]=> string(17) "one,two,three" ["hl.snippets"]=> int(2) ["hl.fragsize"]=> int(100) ["hl.simple.pre"]=> string(3) "" ["hl.simple.post"]=> string(4) "" ["f.content.hl.defaultSummary"]=> string(4) "true" ["debugQuery"]=> string(4) "true" ["debug.explain.structured"]=> string(4) "true" }

**Comment by thomascorthals** [comment]
Are you sure you enabled the QueryElevationComponent?

```php
$query->getQueryElevation();
```

**Comment by rafkamonday** [comment]
That's the point! I'm sorry. Thanks a lot for your help!

**Comment by thomascorthals** [comment]
No problem. Happy to help!
