### ISSUE TITLE
EscapePhrase with \r does not work 

### ISSUE THREAD

**Issue by alexander-schranz** [solariumphp/solarium#1104]
**Solarium version(s) affected**: 6.x-dev b785b8b
**Solr version**: 9
**Solr mode**: cloud

**Description**

In my search engine abstraction I try to filter by a very special field:

```php
$specialString = "^The 17\" O'Conner && O`Series \n OR a || 1%2 \r\n book? \r \twhat \\ text // ok? end$";
```

Why most of the special chars work with the `escapePhrase` method it does not work for the `\r` value. So I thin kthere is something missing.

**How to reproduce**

Index a document with that special chars.

Try to filter by it: 

```php
'tag.raw=' . $helper->escapePhrase($specialString); 
```

**Possible Solution**

Not sure what is missing in `escapePhrase`.

**Additional context**

```
// does not work:
$specialString = "^The 17\" O'Conner && O`Series \n OR a || 1%2 \r\n book? \r \twhat \\ text // ok? end$";
// works:
$specialString = "^The 17\" O'Conner && O`Series \n OR a || 1%2 \n book? \twhat \\ text // ok? end$";
```

**Comment by thomascorthals** [comment]
I'm not sure what's happening here. Only `"` and `\` are escaped by `escapePhrase()` so it shouldn't treat `"\r\n"` any differently than `"\n"`.

Did you index through Solarium as well? If so, can you provide a code sample to reproduce this behaviour?

Either way, can you verify that the `\r` value is actually present in the index? If by "works" you mean you can retrieve the document without `\r` in the query, I suspect it never made it into the field in the first place.

**Comment by alexander-schranz** [comment]
Yeah it is indexed also via Solarium. You can checkout the failing test here: https://github.com/schranz-search/schranz-search/pull/302

Checkout the PR:

```
git clone git@github.com:alexander-schranz/schranz-search.git
cd schranz-search
git checkout bugfix/solr-filter
cd packages/seal-solr-adapter/

docker compose up # takes some time until solr is booted

# run the test

composer test -- --filter="testEqualConditionSpecialString"
```

I will check it at the evening if the `\r` is still there when read from the index.

**Comment by alexander-schranz** [comment]
Solr itself does not strip the `\r` away reading and outputing the docs the `\r` still is there:

> `echo (json_encode($loadedDocuments[0]['tags'][2]));`
> "^The 17\" O'Conner && O`Series \n OR a || 1%2 \r\n book? \r \twhat \\ text \/\/ ok? end$"

But still not sure how correctly escape it here in the filters currently `$query->getHelper()->escapePhrase($value)` is used: https://github.com/schranz-search/schranz-search/blob/c422234356fb0dd5c3d319202c30728ea73d63e9/packages/seal-solr-adapter/src/SolrSearcher.php#L85

**Comment by alexander-schranz** [comment]
One more update I currently try todo manual escaping and avoid the Helper for most cases this works:

```php
return (string) '"' . \addcslashes($value, '"\\') . '"';
```

Result:

```php
// this string works:
$specialString = "^The 17\" O'Conner && O`Series \n OR a || 1%2 \n book? \twhat \\ text: }{ )( - + // ok? end$";

// but with \r still fails
$specialString = "^The 17\" O'Conner && O`Series \n OR a || 1%2 \r\n book? \r \twhat \\ text: }{ )( - + // ok? end$";
```

On https://solr.apache.org/guide/solr/latest/query-guide/standard-query-parser.html#escaping-special-characters The following chars are listed: `+ - && || ! ( ) { } [ ] ^ " ~ * ? : /`.

So I would expect that `\addcslashes($value, '+-&|!(){}[]^"~*?:/')` is enough 🤔  but atleast `\` is already required and not listed to be escaped so the list there already incorrect.

**Comment by thomascorthals** [comment]
> On https://solr.apache.org/guide/solr/latest/query-guide/standard-query-parser.html#escaping-special-characters The following chars are listed: `+ - && || ! ( ) { } [ ] ^ " ~ * ? : /`.

We do have an integration test that checks those with both term and phrase queries.

https://github.com/solariumphp/solarium/blob/b5b434a61b451019bb9ae3cd2d5f8f1e14d57d6e/tests/Integration/AbstractTechproductsTestCase.php#L287-L289

**Comment by alexander-schranz** [comment]
I'm not sure how to get the tests run locally for solarium but I extend the testcase you linked here with more special chars which should be tested: https://github.com/solariumphp/solarium/pull/1106 and use the `createFilterQuery` in it like I currently doing it.

**Comment by thomascorthals** [comment]
As I suspected, the problem is with indexing and not querying. I wrote a test for it and it fails upon checking the indexed value, but only when indexed as XML. When using JSON for indexing, the test passes.

https://github.com/thomascorthals/solarium/actions/runs/6949658848/job/18908226768#step:9:84

```diff
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
 Array &0 (
     0 => '^The 17" O'Conner && O`Series \n
- OR a || 1%2 \r\n
- book? \r
+ OR a || 1%2 \n
+ book? \n
  	what \ text // ok? end$'
 )
```

Both `\r\n` and `\r` are stored as `\n` because of XML's [End-of-Line Handling](https://www.w3.org/TR/REC-xml/#sec-line-ends).

> To simplify the tasks of [applications](https://www.w3.org/TR/REC-xml/#dt-app), the [XML processor](https://www.w3.org/TR/REC-xml/#dt-xml-proc) _MUST_ behave as if it normalized all line breaks in external parsed entities (including the document entity) on input, before parsing, by translating both the two-character sequence #xD #xA and any #xD that is not followed by #xA to a single #xA character.

**Comment by alexander-schranz** [comment]
I'm not sure if solarium use JSON or XML but as in the previous comment the `\r` still is returned when write a document and read it so it seems in that case not be replaced.

Writing a document is currently done this way:

```php
        $update = $this->client->createUpdate();
        $indexDocument = $update->createDocument($document); // containing tags with \r

        $update->addDocuments([$indexDocument]);
        $update->addCommit();

        $this->client->getEndpoint()
            ->setCollection('our_index');

        $this->client->update($update);
```

**Comment by alexander-schranz** [comment]
> Both \r\n and \r are stored as \n because of XML's [End-of-Line Handling](https://www.w3.org/TR/REC-xml/#sec-line-ends).

That should be mean that we need todo something like:

```
$value = \str_replace("\r\n", "\n", (string) $value);
$value = \str_replace("\r", "\n", (string) $value);
```

before escaping the rest of the string.

**Comment by thomascorthals** [comment]
Your extended test case runs into the same failure with XML.

https://github.com/solariumphp/solarium/actions/runs/6949726717/job/18908670560?pr=1106#step:9:109

```diff
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
 Array &0 (
     0 => ' +-&&||!(){}[]^"~*?:/\\n
-	\r
-\r\n
+	\n
+\n
 '
     1 => 'a b'
     2 => 'a+b'
@@ @@
     21 => 'a\n
 b'
     22 => 'a	b'
-    23 => 'a\r
+    23 => 'a\n
 b'
-    24 => 'a\r\n
+    24 => 'a\n
 b'
 )
```

> I'm not sure if solarium use JSON or XML

Solarium can do both. Support for JSON updates was introduced in 6.2.8 and it became the default format in 6.3.0. If you don't use XML specific functionality, you can switch to JSON updates seamlessly and they're actually more performant. Our integration tests run with both XML and JSON updates to ensure this functional equivalence (but none of them indexed an `\r` before 😉).

**Comment by thomascorthals** [comment]
> > Both \r\n and \r are stored as \n because of XML's [End-of-Line Handling](https://www.w3.org/TR/REC-xml/#sec-line-ends).
> 
> That should be mean that we need todo something like:
> 
> ```
> $value = \str_replace("\r\n", "\n", (string) $value);
> $value = \str_replace("\r", "\n", (string) $value);
> ```
> 
> before escaping the rest of the string.

We can't because there is no way of telling which format was used for indexing. If the index was built outside Solarium, besides XML and JSON it could also have been CSV and more recently CBOR.

**Comment by alexander-schranz** [comment]
Okay, as the outside user of my abstraction don't get into contact with the internals of solarium I can force a specific format. What would be interesting for `Solarium` is that I could set it more globally example via `$client->setFormat('JSON');` instead for every query itself what I currently did see?

**Comment by alexander-schranz** [comment]
I tested various things now and this code seems currently work with the default indexing above (https://github.com/solariumphp/solarium/issues/1104#issuecomment-1821727348) in my cases:

```
    private function escapeFilterValue(string|int|float|bool $value): string
    {
        $value = \str_replace(["\r\n", "\r"], "\n", (string) $value);

        return '"' . \addcslashes($value, '"+-&|!(){}[]^~*?:\\/ ') . '"';
    }
```

**Comment by alexander-schranz** [comment]
The tests run currently against `6.2` and latest `6.x-dev b785b8b` set min requirement to 6.3 should so not be a problem. Supported PHP Version is currently ^8.1.

**Comment by thomascorthals** [comment]
I tried indexing with `<![CDATA[ ]]>` instead of entity references for the XML PCDATA but that still gets rid of `\r`.

**Comment by alexander-schranz** [comment]
The `6.x-dev` seems to be outdated and not in sync with the `main` branch. When a library allows to test against `dev` dependencies it currently install `6.x-dev` branch on `b785b8b` which seems outdated if I do a diff between 6.3.3 the tagged version seems to be newer then the dev version which should not be: https://github.com/solariumphp/solarium/compare/b785b8b...6.3.3

**Comment by thomascorthals** [comment]
> The `6.x-dev` seems to be outdated and not in sync with the `main` branch. When a library allows to test against `dev` dependencies it currently install `6.x-dev` branch on `b785b8b` which seems outdated if I do a diff between 6.3.3 the tagged version seems to be newer then the dev version which should not be: [b785b8b...6.3.3](https://github.com/solariumphp/solarium/compare/b785b8b...6.3.3) reverse diff looks like this [6.3.3...b785b8b](https://github.com/solariumphp/solarium/compare/6.3.3...b785b8b) .

@mkalkbrenner Can you chime in on this?

**Comment by alexander-schranz** [comment]
To avoid this kind of problem I personally avoid a branch named `main` or `master` as always go with branch names by versions as composer detects them as `@dev` branches. Another way is to not have the `6.x` branch and remove it but define composer alias from your current master: https://getcomposer.org/doc/articles/aliases.md.

**Comment by alexander-schranz** [comment]
From my point of view the issue can so be closed, thank you all for your help.
