### ISSUE TITLE
PHP 8.2 deprecations

### ISSUE THREAD

**Issue by mkalkbrenner** [solariumphp/solarium#1114]
Deprecated function: Creation of dynamic property Solarium\QueryType\Server\Collections\Result\ClusterStatusResult::$cluster is deprecated in Solarium\Core\Query\Result\QueryType->mapData() (line 101 of /var/www/html/vendor/solarium/solarium/src/Core/Query/Result/QueryType.php).

Deprecated function: Creation of dynamic property Solarium\QueryType\Server\Collections\Result\ReloadResult::$success is deprecated in Solarium\Core\Query\Result\QueryType->mapData() (line 101 of /var/www/html/vendor/solarium/solarium/src/Core/Query/Result/QueryType.php).

**Comment by thomascorthals** [comment]
I fixed it with `#[\AllowDynamicProperties]`. Adding properties to every `*Result` class with proper getters wasn't feasible right now as I'd have to dig through the Solr source code for every possible property name.
