### ISSUE TITLE
Documentation at Read the Docs not updated

### ISSUE THREAD

**Issue by thomascorthals** [solariumphp/solarium#1115]
https://solarium.readthedocs.io/en/stable/ has 6.3.1 as the latest stable version.

**Comment by mkalkbrenner** [comment]
It seems that there's a new requirement for a .readthedocs.yaml file.
I added it to master, let's see ...

**Comment by mkalkbrenner** [comment]
Building latest seems to work. We need to tag 6.3.5 to update stable.

**Comment by thomascorthals** [comment]
[TermVector](https://solarium.readthedocs.io/en/latest/queries/select-query/building-a-select-query/components/termvector-component/) is an example that's available for latest but not for stable yet. I notice the menu doesn't show it though. It's different on latest and stable.

**Comment by thomascorthals** [comment]
Easier to see with a page that's available on both. Stats component [stable](https://solarium.readthedocs.io/en/stable/queries/select-query/building-a-select-query/components/stats-component/) vs. [latest](https://solarium.readthedocs.io/en/latest/queries/select-query/building-a-select-query/components/stats-component/).

**Comment by mkalkbrenner** [comment]
For whatever reason, our mkdocs.yml has not been picked for a long time. So the navigation has been auto-created. Now it gets picked up again. But it only contains a few pages in the navigation section.
We could configure it to use the auto-navigation or we need to list all pages explicitly to have our own non-alphabetical order.

**Comment by mkalkbrenner** [comment]
@thomascorthals 'latest' now contains a full navigation.
That is a start. But feel free to reorganize things in mkdocs.yml

**Comment by thomascorthals** [comment]
I've shuffled them around in places where it makes sense to break with the alphabetical order. E.g. putting "Building an update query" first instead of after "Add command".

Tip of the day: I use [MkDocs](https://www.mkdocs.org/) locally when working on the documentation.

**Comment by thomascorthals** [comment]
6.3.5 is available at Read the Docs now.

I see 6.3.2 – 6.3.4 are still missing. Don't think we had any breaking changes that would make the current docs backward incompatible with one of those specific versions?

**Comment by mkalkbrenner** [comment]
We would need to create dedicated branches and move the tags to get these missing documentations. But I don't think that this would be worth the effort.

**Comment by thomascorthals** [comment]
Thought so too.
