### ISSUE TITLE
For labelled single nested child documents update functionality gives error for xml format

### ISSUE THREAD

**Issue by eastern-ravindra** [solariumphp/solarium#1132]
**Solarium version(s) affected**: 6.3.1
**Solr version**: 8.6.3
**Solr mode**: standalone / cloud

**Description**

For labelled single nested child documents if passed multidimension array for update functionality gives 
`missing required field ` issues for xml format 

`Solr HTTP error: OK (400) { "responseHeader":{ "status":400, "QTime":183}, "error":{ "metadata":[ "error-class","org.apache.solr.common.SolrException", "root-error-class","org.apache.solr.common.SolrException"], "msg":"[doc=null] missing required field: title", "code":400}}
`

**How to reproduce**

If we try to update solr index with below data where `title` is required field and have parent child relationship

```
$data = [
    "id" => "parent1",
    "title" => "Parent Document",
    "children" => [
        "child1" => [
            "id" => "child1",
            "title" => "Child Document 1"
        ],
        "child2" => [
            "id" => "child2",
            "title" => "Child Document 2"
        ]
    ]
];
```

While executing update query it gives missing required field `title`.

**Possible Solution**

 ```
} else {
          $xml .= '<doc';
          if ('_childDocuments_' !== $key) {
              // labelled single nested child documents can't be indexed in XML, but
              // we aim for forward compatibility with the proposed syntax in SOLR-16183
              $xml .= ' name="'.$key.'"';
          }
          $xml .= '>';
          foreach ($value as $k => $v) {
              $xml .= $this->buildFieldsXml($k, $boost, $v, null);
          }
          $xml .= '</doc>';
}
```
Above code in src/QueryType/Update/RequestBuilder/Xml.php file line no. 306 will create xml output as follows

```
<doc>
	<field name="id">parent1</field>
	<field name="title">Parent Document</field>
       <doc name="children">
         <doc name="child1">
            <field name="id">child1</field>
	    <field name="title">Child Document 1</field>
        </doc>
       <doc name="child2">
            <field name="id">child2</field>
	    <field name="title">Child Document 2</field>
        </doc>
       <doc>
</doc>
```
`<doc name="children">` is this section really needed?
Ideally xml should be like

```
<doc>
	<field name="id">parent1</field>
	<field name="title">Parent Document</field>
   
         <doc>
            <field name="id">child1</field>
	    <field name="title">Child Document 1</field>
        </doc>
       <doc>
            <field name="id">child2</field>
	    <field name="title">Child Document 2</field>
        </doc>
       
</doc>
```

I think, we should modify foreach loop in above code as below to fix this issue(just a suggestion)

```
foreach ($value as $multivalue) {
    foreach ($multivalue as $k => $v) {
        $xml .= $this->buildFieldsXml($k, $boost, $v, null);
    }
}
```

**Comment by thomascorthals** [comment]
> `<doc name="children">` is this section really needed?

That should be `<field name="children">`.

**Comment by thomascorthals** [comment]
Actually, it makes sense why the request builder gives you `<doc name="children">`. Your `$data` contains an associative array as the value for the (pseudo-)field `children`. So you're asking for a single nested child document labelled `children`, which itself contains two single nested child documents labelled `child1` and `child2`. The document labelled `children` is rejected because it doesn't have a `title` field.

You could add one like this (and will most like want an `id` too in this case):

```php
$data = [
    "id" => "parent1",
    "title" => "Parent Document",
    "children" => [
        "id" => "children1",
        "title" => "Child Documents",
        "child1" => [
            "id" => "child1",
            "title" => "Child Document 1"
        ],
        "child2" => [
            "id" => "child2",
            "title" => "Child Document 2"
        ]
    ]
];
```

to get this:

```xml
<doc>
    <field name="id">parent1</field>
    <field name="title">Parent Document</field>
    <doc name="children">
        <field name="id">children1</field>
        <field name="title">Child Documents</field>
        <doc name="child1">
            <field name="id">child1</field>
            <field name="title">Child Document 1</field>
        </doc>
        <doc name="child2">
            <field name="id">child2</field>
            <field name="title">Child Document 2</field>
        </doc>
    </doc>
</doc>
```

But I think what you want is either this:

```php
$data = [
    "id" => "parent1",
    "title" => "Parent Document",
    "children" => [
        [
            "id" => "child1",
            "title" => "Child Document 1"
        ],
        [
            "id" => "child2",
            "title" => "Child Document 2"
        ]
    ]
];
```

to get this:

```xml
<doc>
    <field name="id">parent1</field>
    <field name="title">Parent Document</field>
    <field name="children">
        <doc>
            <field name="id">child1</field>
            <field name="title">Child Document 1</field>
        </doc>
        <doc>
            <field name="id">child2</field>
            <field name="title">Child Document 2</field>
        </doc>
    </field>
</doc>
```

Or this:

```php
$data = [
    "id" => "parent1",
    "title" => "Parent Document",
    "child1" => [
        "id" => "child1",
        "title" => "Child Document 1"
    ],
    "child2" => [
        "id" => "child2",
        "title" => "Child Document 2"
    ]
];
```

to get this:

```xml
<doc>
    <field name="id">parent1</field>
    <field name="title">Parent Document</field>
    <doc name="child1">
        <field name="id">child1</field>
        <field name="title">Child Document 1</field>
    </doc>
    <doc name="child2">
        <field name="id">child2</field>
        <field name="title">Child Document 2</field>
    </doc>
</doc>
```

If the latter is what you want, i.e. two labelled single nested child documents, it won't work with XML formatted update requests before Solr 9.3 because of [SOLR-16183](https://issues.apache.org/jira/browse/SOLR-16183). If you use JSON formatted requests (Solarium's default behaviour since 6.3.0), it will work with Solr version before 9.3.

**Comment by thomascorthals** [comment]
@eastern-ravindra Were you able to make this work?

**Comment by eastern-ravindra** [comment]
> @eastern-ravindra Were you able to make this work?

No.
As of now, used json format and  used `array_values` to remove nested array keys.

**Comment by thomascorthals** [comment]
Since you've found a solution that works for you, I'm going to close this issue.
