### ISSUE TITLE
Subquery/nested query Support

### ISSUE THREAD

**Issue by relwell** [solariumphp/solarium#123]
Hello,

Does this library support  the following syntax?

```
foo:bar AND _query_:"{!dismax qf=myfield}how now brown cow"
```

If not, can I accomplish this by casting a pre-built query as a string and passing that to a different query?

Thanks for your help on this!

**Comment by dewos** [comment]
Oh well, 2012.... but I just saw it. @basdenooijer is it still in the todo list?

**Comment by basdenooijer** [comment]
Yes, no such functionality has been developed yet. I don't have the time to do this at the moment, but I can offer some support for a contribution.

**Comment by dewos** [comment]
Hi @basdenooijer, first of all thanks for showing an interest on the topic. If your time is little, let me suggest you one possible solution:

In Java-world we use Spring Data Solr and its awesome Criteria string builder. 

Links:
- http://docs.spring.io/spring-data/solr/docs/current/api/org/springframework/data/solr/core/query/Criteria.html
- http://docs.spring.io/spring-data/solr/docs/current/reference/html/
-https://github.com/spring-projects/spring-data-solr/blob/master/src/test/java/org/springframework/data/solr/core/query/CriteriaTests.java

Criteria is a very powerful and flexible builder, and thousand of people use it every day. A q= query builder would definitely recommend for solarium, so I **probably** could release a corrispective 1:1 PHP version for the PHP community. It is a source-code that I know very well, so the timeline is short, maybe next week.

Moreover, the idea of a bridge between Java and Php would be very romantic, like the Doctrine API is very similar to the Hibernate one, and switching from a language to another one is easy for the devs.

Let me know, what you think about it :)

**Comment by relwell** [comment]
Cleaning out my open issues.
