### ISSUE TITLE
Integrate with the Search Framework library

### ISSUE THREAD

**Issue by cpliakas** [solariumphp/solarium#150]
This is not really a feature request and more just me putting something on your radar, but I have been working on the [Search Framework](https://github.com/cpliakas/search-framework) project this week that integrates with this library via the [Solr Search Engine](https://github.com/cpliakas/solr-search-engine) add-on.

The goal is not to abstract libraries such as Solarium and Elastica, but rather provide a blueprint where people can write reusable code in a backend agnostic manner but still leverage the advanced functionality exposed by the backend of their choosing. In other words, it wants to facilitate code reuse for PHP-based search applications but still allow the wonderful, well-documented libraries such as yours to do what they do best.

Although the framework touches many different parts of search, it focuses heavily on the document processing methodology, in other words gathering the source data and processing it for indexing. I feel that this aspect of building search applications is fairly backend agnostic, and the goal is to provide a framework where people can write and contribute "collection" extensions that work with Solarium, Elastica, etc. A couple of examples of collections are [Feed data](https://github.com/cpliakas/feed-collection), [Git logs messages](https://github.com/cpliakas/git-collection), and there is likely to be a Drupal collection in the very near future.

Anyways, at this point it is more of an idea although there is a lot of working code to prove the concept. There is nothing that the Solarium library has to do, but again I wanted to throw it on your radar since the Solarium project is a first class citizen regarding the libraries I am targeting as best-in-breed.

**Comment by mkalkbrenner** [comment]
I think we should close this one.
