### ISSUE TITLE
When using ZendHttp adaptor multiple facetfields break facet response from solr4

### ISSUE THREAD

**Issue by cooperaj** [solariumphp/solarium#210]
We're using solr4 and solarium3. This issue caught us today and it took stepping through with a debugger to find what was going wrong. 

We're attaching multiple facets via 'createFacetField' as is normal and yet the result set returned no facet counts for any of the facets. Debugging down to the http layer was giving us the url:

```
/solr/core/select?omitHeader=true&wt=json&indent=true&q=*:*&start=0&rows=10&fl=*,score&facet=true&facet.field[0]={!key=typeOfPlace}typeOfPlace&facet.field[1]={!key=county}county&facet.field[2]={!key=language}language&facet.field[3]={!key=source}source&facet.field[4]={!key=century}century&f.typeOfPlace.facet.mincount=1&f.county.facet.mincount=1&f.language.facet.mincount=1&f.source.facet.mincount=1&f.century.facet.mincount=1
```

This url would return a json response that terminated with:

```
"facet_counts":{
"facet_queries":{},
"facet_fields":{},
"facet_dates":{},
"facet_ranges":{}}}
```

A bit of trial and error (and much cursing) led us to discover that because ZendHttp was encoding the multiple facet.fields as number keyed arrays solr4 was not able to interpret the request correctly. Changing the request to:

```
/solr/core/select?omitHeader=true&wt=json&indent=true&q=*:*&start=0&rows=10&fl=*,score&facet=true&facet.field={!key=typeOfPlace}typeOfPlace&facet.field={!key=county}county&facet.field={!key=language}language&facet.field={!key=source}source&facet.field={!key=century}century&f.typeOfPlace.facet.mincount=1&f.county.facet.mincount=1&f.language.facet.mincount=1&f.source.facet.mincount=1&f.century.facet.mincount=1
```

gave us the correct response. i.e. one populated with facet counts. We worked around this issue by switching to the Curl adaptor.

Thanks
Adam

**Comment by mkalkbrenner** [comment]
Zend_HTTP is not supported anymore
