### ISSUE TITLE
Spellcheck warning

### ISSUE THREAD

**Issue by Patrick0815** [solariumphp/solarium#218]
Solarium call a warning by a spellcheck results like this:

```
<response>
  <result name="response" numFound="60121" start="0" maxScore="1.0"/>
  <lst name="spellcheck">
    <lst name="suggestions">
      <bool name="correctlySpelled">true</bool>
    </lst>
  </lst>
</response>
```

because there is a

```
<lst name="suggestions">
```

without

```
<lst name="suggestion">
```

Warning: Invalid argument supplied for foreach() in /solarium/library/Solarium/QueryType/Select/ResponseParser/Component/Spellcheck.php on line 186

?? take this to line 186: ??

```
if(isset($value['suggestion']) && is_array($value['suggestion']))
```

**Comment by mkalkbrenner** [comment]
I think that's already solved
