### ISSUE TITLE
"Complex" range implementation

### ISSUE THREAD

**Issue by trasher** [solariumphp/solarium#240]
Hello,

I'm trying to get a range facet on the the same date field with multiple parameters. On Solr side, I use something like:
`{!key=foo facet.date.start=1980-01-01T00:00:00.000Z facet.date.end=2000-01-01T00:00:00.000Z facet.date.gap=+1DAY}date_field`

That way, I get a facet named "foo" with the specified parameters on my date_field field. I did not find the right way to do that with Solarium :/

I've tried to pass the full expression in the createFacetRange() function. Doing this, I get the correct query sent to Solr, but Solarium is "not able" to retrieve results, so getFacets() does not return those specific results.

As far as I understand what happens in the Solarium\QueryType\Select\ResponseParser\Component::parse() function, Solarium will try to load a facet named "foo facet.date.start[...]" while Solr returns a facet named "foo".

Is there something I've missed or misunderstand, or is this feature not (yet?) implemented into Solarium? Is there a way I can get my facet results back?

Than you

**Comment by thomascorthals** [comment]
If you create a facet with a `string` argument, it is always interpreted as the facet key:

```php
$second_range = $facetSet->createFacetRange(
    'years f.date_field.facet.range.start=1500-12-31T00:00:00Z f.date_field.facet.range.end=2010-12-31T23:59:59Z f.date_field.facet.range.gap=+1YEARS'
);
```

Since Solarium 6.1.4, you can send a request with multiple range facets on the same field like this.

```php
$first_range = $facetSet->createFacetRange('threeyears');
$first_range->setField('{!f.date_field.facet.range.start=1500-12-31T00:00:00Z f.date_field.facet.range.end=2010-12-31T23:59:59Z f.date_field.facet.range.gap=+3YEARS}date_field');

$second_range = $facetSet->createFacetRange('years');
$second_range->setField('{!f.date_field.facet.range.start=1500-12-31T00:00:00Z f.date_field.facet.range.end=2010-12-31T23:59:59Z f.date_field.facet.range.gap=+1YEARS}date_field');
```

Earlier versions render an invalid request string with that code.
