### ISSUE TITLE
Support block joins

### ISSUE THREAD

**Issue by basdenooijer** [solariumphp/solarium#250]
More info
http://blog.griddynamics.com/2013/09/solr-block-join-support.html
https://cwiki.apache.org/confluence/display/solr/Other+Parsers#OtherParsers-BlockJoinQueryParsers

**Comment by bmeynell** [comment]
:+1:

**Comment by rjcrystal** [comment]
:+1:

**Comment by thomascorthals** [comment]
Block join and [other query parsers](https://solr.apache.org/guide/other-parsers.html) can be used if you specify them in the local parameters of a query.

Examples from our integration tests:

https://github.com/solariumphp/solarium/blob/802c69c57d56934cde9ab530450b55d102d64e55/tests/Integration/AbstractTechproductsTest.php#L1625-L1626

https://github.com/solariumphp/solarium/blob/802c69c57d56934cde9ab530450b55d102d64e55/tests/Integration/AbstractTechproductsTest.php#L1635-L1636

You can generate the local params block with a [helper function](https://solarium.readthedocs.io/en/stable/queries/query-helper/query-helper/).

```php
$select->setQuery(
    $select->getHelper()->qparser(
        'parent',
        [
            'which' => '"cat:parent"',
            'excludeTags' => 'tag1,tag2',
        ]
    ).'id:solarium-child-1'
);
```

Is this sufficient support for block joins?

My personal opinion is that a full object-oriented approach to generating these queries would be more work than it's worth.

- There are dozens of query parsers and they all have different parameters that can be set.
- People coming from the Solr ref guide will probably put the local params block directly in the query string anyway.

**Comment by thomascorthals** [comment]
With the release of [Solarium 6.1.4](https://github.com/solariumphp/solarium/releases/tag/6.1.4), a bug has been fixed that prevented using local parameters in a facet query.

`Helper::qparser()` has also been improved to support booleans and arrays. You can now write:
```php
$select->setQuery(
    $select->getHelper()->qparser(
        'parent',
        [
            'which' => '"cat:parent"',
            'excludeTags' => ['tag1', 'tag2'],
        ]
    ).'id:solarium-child-1'
);
```
to build the local parameters. This is equivalent to:
```php
$select->setQuery('{!parent which="cat:parent" excludeTags=tag1,tag2}id:solarium-child-1');
```
