### ISSUE TITLE
Warning when using buffered add with multidimensional array

### ISSUE THREAD

**Issue by joshuaadickerson** [solariumphp/solarium#251]
`Warning: htmlspecialchars() expects parameter 1 to be string, array given in solarium\solarium\library\Solarium\QueryType\Update\RequestBuilder.php on line 177`

Errors on a similar document:

``` php
$doc = [
    '_id' => 'aQfja',
    'title' => 'Golden Star Restaurant',
    'events' => [
        ['_id' => 'Sua7e', 'title' => 'Taste Test', 'dtg' => '2014-03-27 20:13:56'],
    ]
];
```

In `RequestBuilder::buildAddXml()` the `foreach ($value as $multival)` loop needs to be recursive. I'd submit a PR, but I'm not sure about the structure of the XML.

**Comment by thomascorthals** [comment]
This warning wasn't specific to `BufferedAdd`. Solarium didn't yet support nested documents in update queries when this issue was created. Support for nested documents has been added in Solarium 3.7.0. This will now work whether you update through `BufferedAdd` or directly.
