### ISSUE TITLE
Timezone of a DateTime gets set to UTC

### ISSUE THREAD

**Issue by skarnl** [solariumphp/solarium#253]
When adding a DateTime object to a field, it will be formatted by the _\Solarium\QueryType\Update\RequestBuilder.php::buildFieldXml()_ method. There it will use the helper function _\Solarium\Core\Query\Helper::formatDate()_ to format the DateTime to the right Solr-format.

In that helper method the timezone of the $input will be set to UTC. But since the DateTime is given by reference, Solarium adjusts the timezone of the referenced DateTime.

```
$input->setTimezone(new \DateTimeZone('UTC'));
```

The solution could be to create a clone of the $input just before adjust it.

```
$input = clone $input;
```

or

```
// input of datetime object
case $input instanceof \DateTime:
    $input = clone $input; //instead of the no work needed ^^
break;
```

**Comment by mkalkbrenner** [comment]
Since PHP 5.x and 7.0 and Solr versions before 6.4 are EOL we declare EOL for solarium 3.x, too.
For sure it is still available but we won't merge PRs anymore and there won't be another 3.x release.
