### ISSUE TITLE
Solarium\Exception\HttpException

### ISSUE THREAD

**Issue by FabianKoestring** [solariumphp/solarium#266]
Hey there!
Everything works fine since yesterday. Iam getting following Exception. We changed nothing on the System. Anybody an idea what is going wrong?

``` php
Solarium\Exception\HttpException
 Solr HTTP error: HTTP request failed, Recv failure: Connection reset by peer
```

**Comment by AshrafSarsour** [comment]
did you find solution ?

**Comment by FabianKoestring** [comment]
Sry, i stopped using solr. We use elasticsearch. Never had any problems with es. 👌

**Comment by AshrafSarsour** [comment]
is it easy to integrate when you want to move from solr to elastic search ? 
and is there any extra benefits worth the restructure ?
