### ISSUE TITLE
Why is the event dispatcher not injected?

### ISSUE THREAD

**Issue by bartfeenstra** [solariumphp/solarium#275]
Why is the event dispatcher not injected, but instead created hard-coded in Solarium\Core\Client\Client::init()? It should be injected through the constructor, or otherwise (but I personally don't like that) through a setter method. The way the code works now, event dispatching cannot be tested, the class cannot use an application's global event dispatcher, and it makes testing dependent classes harder.

**Comment by mkalkbrenner** [comment]
all of these suggestions are already implemented
