### ISSUE TITLE
Atomic Updates - remove command

### ISSUE THREAD

**Issue by dwsrumwq7cyey7qv** [solariumphp/solarium#277]
Hello,

there is a remove command mentioned in the official documentation of Solr (https://cwiki.apache.org/confluence/display/solr/Updating+Parts+of+Documents). It is supposed to remove an entry of a multi-valued field. As far as I know, this functionality is not supported by solarium (http://api.solarium-project.org/v3.x/classes/Solarium.QueryType.Update.Query.Document.Document.html).

Are there any plans of implementing this functionality? Thank you in advice!

**Comment by pauf** [comment]
Hate to bring this back from the dead, but there appears to be no documentation of this feature anywhere.

I am attempting to remove an entry from a multi-value field. I've tried multiple ideas, but right now I'm using:

	$document->removeField('mymultivalue', 'apple');
	$document->setFieldModifier('mymultivalue', 'remove');

Of course 'apple' is indeed set for this particular multi-valued field.

But I'm not getting anywhere at all.

Also tried:

	$document->setField('mymultivalue', 'apple');
	$document->setFieldModifier('mymultivalue', 'remove');

	$document->addField('mymultivalue', 'apple');
	$document->setFieldModifier('mymultivalue', 'remove');

Can anyone please point me in the right direction?

Thanks for any responses!

**Comment by thomascorthals** [comment]
@pauf You have to use `setKey` to set the unique id by which the document is identified in Solr.

```php
$document->setKey('id', 123);
$document->setField('mymultivalue', 'apple');
$document->setFieldModifier('mymultivalue', $document::MODIFIER_REMOVE);
```

Your schema has to meet certain criteria for atomic updates to work at all. You'll find them in the [Solr Reference Guide](https://lucene.apache.org/solr/guide/updating-parts-of-documents.html#atomic-updates).
