### ISSUE TITLE
How to set multicore in solarium?

### ISSUE THREAD

**Issue by samarapiggy** [solariumphp/solarium#278]
Hi! I've been wondering how to set multicore in solarium, cause I want to make the program more flexible, thanks! Please tell me step by step.

**Comment by kostalihas** [comment]
Can you help me with this issue
https://github.com/solariumphp/solarium/issues/408

**Comment by basdenooijer** [comment]
Solarium doesn't switch endpoints by itself. You can either set the endpoint to use when executing a query, or if you want automatic failover use the loadbalancer plugin.

**Comment by kostalihas** [comment]
Thank you basdenooijer I try loadbalancer plugin but Iam cofuse about $config tell me if Iam wrong :

```
$config=array('endpoint'=>array('local1' =>array("host"=>"127.0.0.1",
         "port"=>"8983", "path"=>"/solr", "core"=>"master",),
     'local2'=>array("host"=>"127.0.0.1",
         "port"=>"9000", "path"=>"/solr", "core"=>"slave",)
     ));
          $client = new Solarium\Client();
$endpoint1 = $client->createEndpoint('local1'); //normally you would add endpoint specific settings...
$endpoint2 = $client->createEndpoint('local2');

// get loadbalancer plugin instance and add endpoints
$loadbalancer = $client->getPlugin('loadbalancer');
$loadbalancer->addEndpoint($endpoint1, 1);
$loadbalancer->addEndpoint($endpoint2, 1);
//debug($loadbalancer);
         
        // get a select query instance
        $query = $client->createSelect();
        // set a query 
        $forsearch=$this->request->data ;
        $query = $client->createSelect();
        $query->setQuery($forsearch);
```
I get this ERROR: `ERROR 404 Not found `
I debug my variante $loadbalancer

I remark the endpoint dont get the name of my both core:

```
[protected] endpoints => array(
						'localhost' => object(Solarium\Core\Client\Endpoint) {
							[protected] options => array(
								'host' => '*****',
								'port' => '*****',
								'scheme' => 'http',
								'path' => '/solr',
								'core' => null,
								'timeout' => (int) 5,
								'key' => 'localhost'
							)
						},
						'local1' => object(Solarium\Core\Client\Endpoint) {
							[protected] options => array(
								'host' => '*****',
								'port' => '*****',
								'scheme' => 'http',
								'path' => '/solr',
								'core' => null,
								'timeout' => (int) 5,
								'key' => 'local1'
							)
						},
						'local2' => object(Solarium\Core\Client\Endpoint) {
							[protected] options => array(
								'host' => '*****',
								'port' => '*****',
								'scheme' => 'http',
								'path' => '/solr',
								'core' => null,
								'timeout' => (int) 5,
								'key' => 'local2'
							)
						}
```

**Comment by basdenooijer** [comment]
I've just spotted an issue with the handling of the 'core' config option. For now there are 2 workarounds: use the setCore method, or append the core name to the 'path' value.

Also, use setFailoverEnabled(true) for the loadbalancer plugin.

**Comment by kostalihas** [comment]
thank you I use setcore() methode and setFailoverEnabled(true) I get both core in endpoint but load balancer dosnt swetch endpoint itself , its work when the both master/slave are running and dont work when i stop master server.

**Comment by kostalihas** [comment]
I had try also : 
$loadbalancer->addEndpoint($endpoint1,100);
$loadbalancer->addEndpoints($endpoint2,100);

**Comment by kostalihas** [comment]
The prb was in $config i dont know the right $config so I setCore and setPort and setHot when I create each endpoint to make think work :
```
$endpoint2 = $client->createEndpoint('slave');
$endpoint2->setCore('slave');
$endpoint2->setPort(9000);
```
