### ISSUE TITLE
Unable to set options

### ISSUE THREAD

**Issue by hiranmilinda** [solariumphp/solarium#305]
Hi guys, 
Whats the best way of setting options
For example I see 
curl_setopt($handler, CURLOPT_TIMEOUT, $options['timeout']);
Whats the best of of passing a custom value?

Thanks

**Comment by basdenooijer** [comment]
Currently there is no good way to do that. 

The Curl adapter would have to be extended for that, allowing for custom Curl options, through config and/or a setter method.

**Comment by hiranmilinda** [comment]
Thanks for your reply. Will fork and give it a try. I've been using solarium in few projects and it's well written and documented. Thanks a lot.

**Comment by DMGPage** [comment]
This is annoying, that it is not possible to set timeout for solr. I want, to call data import with executeRequest function, but it will always throw timeout exception.

**Comment by mkalkbrenner** [comment]
The feature exists since solarium 3.3.

https://github.com/solariumphp/solarium/blob/bdb78b9260df9922161cfe8b4cf7df9243b50ccb/src/Core/Client/Adapter/Curl.php#L83
