### ISSUE TITLE
throwing exception should be avoided when building a Result.php

### ISSUE THREAD

**Issue by cordoval** [solariumphp/solarium#306]
https://github.com/solariumphp/solarium/blob/master/library/Solarium/Core/Query/Result/Result.php#L103

This seems a bit wrong, should it be better to avoid throwing this exception when building a Result?

maybe passing a response with a code or something?

**Comment by basdenooijer** [comment]
Are there any cases of a 4xx or 5xx response code where there is sensible data to build a result with?

**Comment by cordoval** [comment]
when i search with "--- any string here" it throws an exception that leave out to the open view the whole source code and query structure.

Additional information:

Solarium\Exception\HttpException
File:
src/vendor/solarium/solarium/library/Solarium/Core/Query/Result/Result.php:103
Message:
Solr HTTP error: OK (400)
{"error":{"msg":"org.apache.solr.search.SyntaxError: Cannot parse 'estado:2 AND localizado:1 AND tipo_inmueble:terreno AND (dpto:--- jj OR prov:--- jj OR nombre:--- jj OR descripcion:--- jj OR codigo:--- jj OR keyword_id_aviso:--- jj)': Encountered \" \"-\" \"- \"\" at line 1, column 62.\nWas expecting one of:\n     ...\n    \"(\" ...\n    \"*\" ...\n     ...\n     ...\n     ...\n     ...\n     ...\n    \"[\" ...\n    \"{\" ...\n     ...\n     ...\n    ","code":400}}

**Comment by andifant** [comment]
you should catch those exceptions yourself - why should there be a result, when solr responses with 4xx or 5xx?

**Comment by basdenooijer** [comment]
I share that view. It's no different than database exceptions of even PHP errors. You don't want to show them in production environments, therefore you should catch exceptions and use the correct PHP configuration to log instead of display errors.

**Comment by cordoval** [comment]
thanks for the reponse. Yeah good close.
