### ISSUE TITLE
ZendHttp Adapter doesn't work with Zend Framework 2

### ISSUE THREAD

**Issue by marinpurgar** [solariumphp/solarium#307]
when ZendHttp Adapter is set for the client:

$client->setAdapter('Solarium\Core\Client\Adapter\ZendHttp');

the following fatal error occurs:

Fatal error: Class 'Zend_Http_Client' not found in vendor/solarium/solarium/library/Solarium/Core/Client/Adapter/ZendHttp.php on line 153

**Comment by marinpurgar** [comment]
I have changed stuff from ZendHttp.php to be ZF2 compliant and created Zend2Http.php, The PR is #308.

**Comment by basdenooijer** [comment]
A new release has been done that includes a ZF2 adapter.
