### ISSUE TITLE
Issue with examples and the facet options

### ISSUE THREAD

**Issue by Parcye** [solariumphp/solarium#309]
I am new to solarium and have been trying to get it up and running. All seems well until I wanted to look into the facet search examples.

$facet = $resultset->getFacetSet()->getFacet('priceranges');

This seems to return NULL in file 2.1.5.1.4-facet-range.php .

My output does show results:
id  53
name    Sample 53product
price   13.34

The error is:
Facet ranges:
Warning: Invalid argument supplied for foreach() in /_sandbox/solarium-master/examples/2.1.5.1.4-facet-range.php on line 31

**Comment by basdenooijer** [comment]
The examples are intended to be used on the Solr example index, is this also what you use? And which version?
