### ISSUE TITLE
ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by scottscreations** [solariumphp/solarium#310]
I have nginx -> php-fpm setup using Solarium. I notice on queries that might take longer then normal i get this 
Error code: ERR_INCOMPLETE_CHUNKED_ENCODING
in chrome. This seems to work in ff so im not sure if its solarium or not but there doesn't seem to be a 
user group or forum to post this. 

I set my timeout to be 0, because i don't want it to timeout.
config:
```
      $config = array(
            'endpoint' => array(
                'localhost' => array(
                    'host' => 127.0.0.1,
                    'port' => 8983,
                    'path' => '/solr/',
                    'core' => 'core1',
                    'timeout' => 0
                )
            )
        );
```
Has anyone else ran into this and is there a resolution?

**Comment by basdenooijer** [comment]
It seems that by setting the timeout to 0 you've run into another timeout (max execution time maybe?). In most cases I'd suggest to do some research on the slow queries and improve querytime instead of raising timeouts

**Comment by scottscreations** [comment]
thanks for the input. I will adjust some things on the web server. I read some stuff that it might be nginx -> php-fpm. I redid my solr delta importing to use a json -> import and so far its been running much better. I haven't seen the chunk issue.

My problem is i would like a infinite execution with a search result no matter how long it takes because the queries are going on a very big database and the hardware varies.

Thanks again.
