### ISSUE TITLE
Update a document partly

### ISSUE THREAD

**Issue by pooya1366** [solariumphp/solarium#311]
Hi.
I want update a field in a document.
https://cwiki.apache.org/confluence/display/solr/Updating+Parts+of+Documents here is a document for this with set command.
How can I do this with solarium?

**Comment by basdenooijer** [comment]
Take a look at the addField or setField method, they take a modifier as an (optional) argument:
https://github.com/solariumphp/solarium/blob/master/library/Solarium/QueryType/Update/Query/Document/Document.php#L185

In this case you would need MODIFIER_SET
