### ISSUE TITLE
solarium-master installation problem

### ISSUE THREAD

**Issue by ahsankhan201** [solariumphp/solarium#316]
I install the solarium-master using composer but it shows me this text on my cmd
Problem1 - the requested package solarium/solarium 1.0.0 could not be found.

i try to open the solarim in browser and check the ping and version it shows
"Solarium library version: 3.2.0 - Ping query successful "

i try to open basic select  in browser
i find this  bugg..
Uncaught exception 'Solarium\Exception\UnexpectedValueException' with message 'Solr JSON response could not be decoded'

another issue is that. 
this is my config file 
$config = array(
'endpoint' => array(
'localhost' => array(
'host' => 'localhost',
'port' => 8983,
'path' => '/solr/#/',
)
)
);
when i set path to '/solr/' it shows 404 error.

Thanks

**Comment by surajdhami** [comment]
use like this  it will automatically detect the version "require": {
          "solarium/solarium": "*.*"
      }

**Comment by Baachi** [comment]
> "solarium/solarium": " * . * "

Never use this! Use explicit versions.

@ahsankhan201 Add this line to your composer.json

```
"solarium/solarium": "~3.3.0"
```

or type this in your terminal

```
php composer.phar require solarium/solarium
```

**Comment by michelnagme** [comment]
I'm using Solr 5.2.1 and only got Solarium to work after setting my config.php like this:

$config = array(
    'endpoint' => array(
        'localhost' => array(
            'host' => '127.0.0.1',
            'port' => 8983,
            'path' => '/solr/techproducts',
        )
    )
);

where 'techproducts' is a example core provided by Solr. Actually, it would only work for me is I set some core name.

Documentation for version 3.x is quite misleading once using 'path' => '/solr/' won't work. I don't know if it is some issue regarding the newest Solr version though.

**Comment by basdenooijer** [comment]
This is indeed a change in the latest Solr version. As these are now the recommended versions the default example config will need to be updated, and include a note for older versions.

Thanks for mentioning this.

**Comment by mkalkbrenner** [comment]
The should be
`$config = array(
'endpoint' => array(
'localhost' => array(
'host' => '127.0.0.1',
'port' => 8983,
'path' => '/solr/',
'core' => 'techproducts',
)
)
);`

Have a look at the integration tests in the 4.x branch.
