### ISSUE TITLE
createFilterQuery overrite? [QUESTION]

### ISSUE THREAD

**Issue by Julian-B90** [solariumphp/solarium#317]
In this line https://github.com/solariumphp/solarium/blob/master/examples/2.1.6-helper-functions.php#L14 and this line https://github.com/basdenooijer/solarium/blob/2.4.1/examples/2.1.6-helper-functions.php#L17 the "createFilterQuery" overrite the query or?

**Comment by basdenooijer** [comment]
No, the createFilterQuery() method return a filterquery instance which is used by 'chaining', and this also has a 'setQuery' method but this is not the setQuery method of the 'main' query.

**Comment by basdenooijer** [comment]
To clarify, this:

```php
$query->createFilterQuery('price')->setQuery($helper->rangeQuery('price', 10, 300))
```
is effectively the same as this:
```php
$fq = $query->createFilterQuery('price');
$fq->setQuery($helper->rangeQuery('price', 10, 300));
```

**Comment by Julian-B90** [comment]
Thanks ^^ :-D
