### ISSUE TITLE
Collations format changed in Solr 5.0

### ISSUE THREAD

**Issue by eostis** [solariumphp/solarium#320]
getSpellcheck()->getCollations() does not work anymore with Solr 5.0

Response from Solr 5.0:
`{"response":{"numFound":0,"start":0,"maxScore":0.0,"docs":[]},"spellcheck":{"suggestions":["cassandr",{"numFound":1,"startOffset":0,"endOffset":8,"origFreq":0,"suggestion":[{"word":"cassandra","freq":13}]}],"correctlySpelled":false,"collations":["collation",{"collationQuery":"cassandra","hits":0,"misspellingsAndCorrections":["cassandr","cassandra"]}]}}`

Response from Solr 4.xxx:
`{"response":{"numFound":0,"start":0,"maxScore":0.0,"docs":[]},"spellcheck":{"suggestions":["cassandr",{"numFound":1,"startOffset":0,"endOffset":8,"origFreq":0,"suggestion":[{"word":"cassandra","freq":13}]},"correctlySpelled",false,"collation",["collationQuery","cassandra","hits",0,"misspellingsAndCorrections",["cassandr","cassandra"]]]}}`

**Comment by basdenooijer** [comment]
Thanks for reporting, we will need to add support for this new format while also keeping support for the 4.x format.

**Comment by eostis** [comment]
My workaround:

	        // New 5.0 format
	        if ( isset( $data['spellcheck']['collations'] ) ) {
		        // Convert object to array
		        foreach ( $data['spellcheck']['collations'][1] as $key => $value ) {
			        $collations[] = $key;
			        $collations[] = $value;
		        }
		        $collations = $this->parseCollation($query, $collations );
	        }

	        return new SpellcheckResult\Result($suggestions, $collations, $correctlySpelled);

**Comment by BBrunekreeft** [comment]
Thanks for this workaround.
Same issue with 'correctlySpelled'
"The spellcheck response format has changed, affecting xml and json clients. In particular, the "correctlySpelled" and "collations" subsections have been moved outside the "suggestions" subsection, and now are directly under "spellcheck". See SOLR-3029 for more information."
http://lucene.apache.org/solr/5_0_0/changes/Changes.html#v5.0.0.upgrading_from_solr_4.x

**Comment by basdenooijer** [comment]
The fix for this issue has been included in the latest release.
