### ISSUE TITLE
Wrong version 3.2.0 on 3.3.0

### ISSUE THREAD

**Issue by MLoureiro** [solariumphp/solarium#329]
Hi there

https://github.com/solariumphp/solarium/blob/3.3.0/library/Solarium/Client.php#L73

Executing your examples it says version 3.2.0

```
    // check solarium version available
    echo 'Solarium library version: ' . Solarium\Client::VERSION . ' - ';
```

**Comment by basdenooijer** [comment]
Forgot to update this, thanks for mentioning it so I can take more care for future releases.
Fixed it in the latest release.
