### ISSUE TITLE
Http post method is not allowed by this URL

### ISSUE THREAD

**Issue by pavneet9** [solariumphp/solarium#332]
I installed solr using the Bitnami installation in windows. When i ping the server using solarium.

If use  var_dump($result->getResponse()); then everything works fine but if i use  var_dump($result->getdata()); I get a error saying JSON could not be encoded.

Similarly when i try to index data into the solr server i get this error.

Fatal error: Uncaught exception 'Solarium\Exception\HttpException' with message 'Solr HTTP error: OK (405) <html> <head> <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/> <title>Error 405 HTTP method POST is not supported by this URL
HTTP ERROR 405
Problem accessing /solr/admin.html. Reason: 
 HTTP method POST is not supported by this URL
Powered by Jetty
in C:\xampp\htdocs\trial\search\vendor\solarium\solarium\library\Solarium\Core\Query\Result\Result.php on line 104

What can be the possible issue?

**Comment by sabdullah98** [comment]
Hi @pavneet9 , how did you resolved it, i am having the same issue.

**Comment by floriansemm** [comment]
How do you perform the request? Can you show your implementation?

**Comment by mkalkbrenner** [comment]
outdated
