### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by LarryEitel** [solariumphp/solarium#333]
Does this package support Laravel 5? Looking for good options for working with Solr 5.1 with Laravel 5.

Thanks for any input.

**Comment by GregEisenman** [comment]
It does.

However, there are several serious issues with Solr 5.0/5.1. Check the pull requests. I put up a fix for Collations (#325), and there is at least one critical issue (#328) that seems like it has been addressed but hasn't been merged with head.

**Comment by basdenooijer** [comment]
Just created a release that includes this fix.

**Comment by LarryEitel** [comment]
Thank you. :)

**Comment by maryamsafari2012** [comment]
hi, i am new in laravel. please guide me. my version is 5.1. when i install solar. i have error.
my error is :BadMethodCallException in Builder.php line 2093:
Call to undefined method Illuminate\Database\Query\Builder::getFeature()?
please guide me that how can install solar in laravel 5.
thanks
