### ISSUE TITLE
Support for deep paging / cursorMark?

### ISSUE THREAD

**Issue by EgbertW** [solariumphp/solarium#345]
I'm been searching through the documentation, code and API-docs, but I couldn't find any reference to the deep paging functionality using the cursorMark parameter. 

The feature was added in Solr 4.7 and allows to efficiently paginate through huge result sets. It basically only involves adding a cursorMark=? parameter to the query and updating the cursorMark parameter for a follow-up request with the value returned by the previous request. However, as far as I can see, doing setOption("cursorMark", "?") does not end up in the final request. Or is there another way to accomplish this?

**Comment by basdenooijer** [comment]
The easiest workaround for now is using the customizerequest plugin, there is an example in the examples folder of Solarium.

**Comment by MadEgg** [comment]
Whoa, quick reply. Seems like a proper work-around. But how would I go about getting the returned cursorMark value in order to request the next page then? The Result does not have a getCursorMark() accessor. Or should I then parse the response manually using Result->getResponse()->getBody()?

**Comment by basdenooijer** [comment]
I think you could use result->getData(), it should return an associative array with all response values, you only need to find the correct key

**Comment by MadEgg** [comment]
Great, I'll give it a try. Thanks for the suggestion. You can close it if you want, or keep it as a feature request for built-in support for a future version.

**Comment by thomascorthals** [comment]
I have a working implementation that hasn't been merged yet because I didn't find the time for test coverage and documentation. Have a look at my pull request: https://github.com/solariumphp/solarium/pull/421.

**Comment by mkalkbrenner** [comment]
It's merged in 4.x.
But PRs for documentation and tests are welcome!
