### ISSUE TITLE
Setting CURL-adapter to explicitly use no proxy

### ISSUE THREAD

**Issue by Ancillius** [solariumphp/solarium#351]
I have to avoid using the system wide proxy for my solarium script, so i tried to do the following:

    $client = new Solarium\Client();
    $client->setOptions([
      'adapteroptions' => [
        'proxy' => '',
      ],
    ]);

Setting the solarium adapter proxy options  to "" (empty string) does not work, since Solarium\Core\Client\Adapter : 154 checks:

        if ($proxy = $this->getOption('proxy')) {
            curl_setopt($handler, CURLOPT_PROXY, $proxy);
        }

Thus an empty string would be casted to "false" and would not be set as proxy.

What about changing it to 

        if (($proxy = $this->getOption('proxy')) !== null) {
            curl_setopt($handler, CURLOPT_PROXY, $proxy);
        }

This helps in my case, but does it break anything?

**Comment by basdenooijer** [comment]
A fix for this has been merged in the develop branch
