### ISSUE TITLE
Vendor Autoload in Example 1

### ISSUE THREAD

**Issue by Robdebert** [solariumphp/solarium#356]
See https://github.com/solariumphp/solarium/blob/master/examples/init.php

The script tries to include "../vendor/autoload.php". But this folder and the file is missing.

**Comment by rubao** [comment]
you have to run ´composer update´ in the root folder

**Comment by Robdebert** [comment]
@rubao I think this can be closed now, when it works with composer (i didn't try, because i do not use composer in my projects )
