### ISSUE TITLE
404 not found when solr is set up correctly.

### ISSUE THREAD

**Issue by ronaksvyas** [solariumphp/solarium#359]
Hello!

I have configured solr correctly and have been using it for my site since last year. 

I am trying to integrate solarium. The script to test ping in examples gives me this error. 

<html><head><title>Solarium examples</title></head><body>Solarium library version: 3.2.0 -
Fatal error: Uncaught exception 'Solarium\Exception\HttpException' with message 'Solr HTTP error: OK (404)
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /Applications/solr-4.10.2/admin/ping. Reason:
<pre>    Not Found</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>

I have the ping handler and I can successfully ping through solr admin panel. The permissions of solr directory are fine and I don't know what the issue is. 

Can someone please help?

**Comment by ronaksvyas** [comment]
I think I solved it. I thought the path in config.dist file was the directory path. I put '/solr' in it. It works fine now.

**Comment by nitinsurana** [comment]
I had a similar issue. Changing in config.dist didn't worked for me but changing in 'Solarium_Client_Adapter' `solarium/solarium/library/Solarium/Client/Adapter.php`worked.
