### ISSUE TITLE
support for luke handler

### ISSUE THREAD

**Issue by memic** [solariumphp/solarium#363]
there is a libary which implements the luke request handler into solarium.. is "native" support planed?

**Comment by basdenooijer** [comment]
It would be nice to include, maybe we could look into integrating the library. Currently I don't have the time to do this myself, however I would be able to provide feedback on a PR.

**Comment by herlon214** [comment]
👍

**Comment by thomascorthals** [comment]
[Solarium 6.3.0](https://github.com/solariumphp/solarium/releases/tag/6.3.0) has been released with native support for Luke queries.

Have a look at the [documentation](https://solarium.readthedocs.io/en/stable/queries/luke-query/luke-query/) on how to use it or dig right in with the [examples](https://github.com/solariumphp/solarium/tree/master/examples) (they're under `2.11.*`)
