### ISSUE TITLE
Query parameter "ie"

### ISSUE THREAD

**Issue by emanuelvianna** [solariumphp/solarium#367]
Since version 4.5, Solr accepts a query parameter ie="<encoding>" which specify the encoding of the query text. If "ie" is supplied, SolrRequestParsers checks if the charset of the query text is the same of "ie" argument. If it is the same it decode it to UTF-8 (the standard encoding) otherwise throws a Bad Request exception. This is useful for PHP applications that uses "iso-8859-1" (very common) or other encoding types. Currently, Sollarium didn't implement it, right? Do you have plans to support it?

Very best regards,
Emanuel

**Comment by basdenooijer** [comment]
Hi Emanuel,

I didn't know about that parameter, so thanks for mentioning it. Currently there are no API methods in  Solarium for this parameter, but it is possible to add custom parameters to the request. I do agree it would be a nice addition but that depends on when I or someone else has time to implement this.
