### ISSUE TITLE
solarium-3x: Curl- Connexion keepalive

### ISSUE THREAD

**Issue by kostalihas** [solariumphp/solarium#379]
How to force the connection to explicitly close when it has finished processing, and not be pooled for reuse.
I am looking for indexing from my app cakephp richdata from files system when i execute my request esxtract from a directorry contient many files(500Mo and more) after 30 second the time out of wamp server stop my request no finished;
I saw cURL is default adapter how Curl will just open another connection when that happens.

this is my function:

```
App::import('Vendor','autoload',array('file'=>'solarium/vendor/autoload.php'));

public function indexDocument(){
$config = array(
"endpoint" => array("localhost" => array("host"=>"127.0.0.1",
"port"=>"8983", "path"=>"/solr", "core"=>"demo",)
) );
$start = microtime(true);

if($_POST){
// create a client instance
$client = new Solarium\Client($config);
$dossier=$this->request->data['User']['dossier'];
$dir = new Folder($dossier);
$files = $dir->find('..');

$headers = array('Content-Type:multipart/form-data');

foreach ($files as $file) {
$file = new File($dir->pwd() . DS . $file);

$query = $client->createExtract();
$query->setFile($file->pwd());
$query->setCommit(true);
$query->setOmitHeader(false);

$doc = $query->createDocument();
$doc->id =$file->pwd();
$doc->name = $file->name;
$doc->title = $file->name();

$query->setDocument($doc);

$request = $client->createRequest($query);
$request->addHeaders($headers);

$client->executeRequest($request);
}

}

$this->set(compact('start'));
} 
```

**Comment by basdenooijer** [comment]
Sounds like an exceeded php max execution time. If you have a big indexing job to do I would suggest to do this using a commandline PHP process, and not using your wamp webserver. I'm not familiar with cakephp but must frameworks have some kind of CLI mode. 

In you PHP cli config (or runtime by using ini_set) you can raise your timeout. Another workaround would be to to divide in smaller batches that can be processed within the timeout.

**Comment by kostalihas** [comment]
yes Indexing using  command line is better and faster , but when I index
rich data from a directory  using SimplePostTool :

D:\solr\solr-5.3.1>java -classpath example\exampledocs\post.jar -Dauto=yes
-Dc=solr_docs_search-core -Ddata=files -Drecursive=yes
org.apache.solr.util.SimplePostTool D:\Lucene\document

the fields name and title of each document msword are not correct or not
exist.


2015-12-03 12:03 GMT+00:00 Bas de Nooijer <notifications@github.com>:

**Comment by kostalihas** [comment]
I have to extract rich document and commit using solarium Client php for Apache Solr; in the documentation of solarium Curl is default Adapter then i dont need:
````
$client->setAdapter('Solarium\Core\Client\Adapter\Curl');

// Then I want to force the connection to explicitly close when it has finished processing , Curl will just open another connection when that happens; for that i try this code:

$ch = curl_init();
$headers=array('Content-Type:multipart/form-data',
    'Connection: Keep-Alive',
    'Keep-Alive: 300');
 curl_setopt($ch, CURLOPT_HTTPHEADER,$headers);

//finally execute request:

$query->setDocument($doc);

$request = $client->createRequest($query);


$result = $client->executeRequest($request);

// But after 30 second time out stop the process of indexing .
