### ISSUE TITLE
Proxy can't be disabled while using curl adapter

### ISSUE THREAD

**Issue by IndianaHorrscht** [solariumphp/solarium#383]
When the operating system defines a proxy (e.g. via environment variable http_proxy) the curl adapter uses it, even while sending array(proxy => '') in the configuration array. The problem is this:

        if ($proxy = $this->getOption('proxy')) {
            curl_setopt($handler, CURLOPT_PROXY, $proxy);
        }

Which doesn't set the option because an empty string casts to false. I propose isset() instead.

Fixed it myself in my installation but perhaps this helps someone else. Thanks for your great work! This library is extremely handy.

**Comment by basdenooijer** [comment]
The latest Solarium release includes an update for this:

```php
if (null !== ($proxy = $this->getOption('proxy'))) {
    curl_setopt($handler, CURLOPT_PROXY, $proxy);
}
```
Are you on an older version, or is this solution not working for you?

**Comment by IndianaHorrscht** [comment]
That works, thanks :) I had a Solarium version from early December and wasn't expecting a fix so quickly!

**Comment by basdenooijer** [comment]
Great!
