### ISSUE TITLE
Can filter queries be shown in debugging?

### ISSUE THREAD

**Issue by laukaichung** [solariumphp/solarium#386]
I have been following the instructions on this [page](http://solarium.readthedocs.org/en/stable/queries/select-query/building-a-select-query/components/debug-component/)

Here is an example:

```
$query = $client->createSelect();

$debug = $query->getDebug();

$bindArr = array('item_id'=>"item_id:(1 AND 2)");

foreach($bindArr as $field=>$parameter){     

       $query->createFilterQuery($field)->setQuery($parameter);

}

$resultset = $client->select($query);

$debugResult = $resultset->getDebug();

echo '<h1>Debug data</h1>';
echo 'Querystring: ' . $debugResult->getQueryString() . '<br/>';
echo 'Parsed query: ' . $debugResult->getParsedQuery() . '<br/>';
echo 'Query parser: ' . $debugResult->getQueryParser() . '<br/>';
echo 'Other query: ' . $debugResult->getOtherQuery() . '<br/>';
```

The output:

```
Debug data
Querystring: *:*
Parsed query: MatchAllDocsQuery(*:*)
Query parser: LuceneQParser
Other query: 
```

It only shows the main query.Is there any way to show what filters (in this case,"item_id") have been built as well?

**Comment by basdenooijer** [comment]
As far as I know Solr doesn't offer this information. This component is based on Solr DebugQuery: https://wiki.apache.org/solr/CommonQueryParameters#debugQuery

Solr can output all input parameters in the response, but this adds no additional info / analysis.

**Comment by mkalkbrenner** [comment]
You could combine echoParams="all" ewth debug.
