### ISSUE TITLE
BC break in 3.5.x release

### ISSUE THREAD

**Issue by hjr3** [solariumphp/solarium#394]
In https://github.com/solariumphp/solarium/commit/21f1799f6d3fe4ab7f713ddeea68a17a20d71ac0 the public interface changed. This change occurred between `3.3` and `3.4` releases. This breaks code that was complying to the interface. I think this change should be in a `4.x` branch.

**Comment by basdenooijer** [comment]
Yes, this change should have been in a major release, unfortunately it slipped through. It's something to pay more attention to in the future, however at this moment there is no easy solution to correct it as far as I can think of. Many people have already fixed their code for this BC break, by reverting their code will break again.

**Comment by hjr3** [comment]
@basdenooijer No worries! We pinned to `3.3` until we are ready to make the change. Anyone else having this problem will hopefully find this issue and will be able to take appropriate action. Thank you for all your great work!
