### ISSUE TITLE
Getting raw data from components (for example, stats)

### ISSUE THREAD

**Issue by eborned** [solariumphp/solarium#395]
I'm trying to use the 'new' percentiles option for the stats component:

`stats.field={!percentiles='10,50,95'}price`

I can append the local parameters to the stats field, but I cannot access the returned percentile data. This is because the class Solarium\QueryType\Select\Result\Stats implements only the basic attributes (min, max, mean, etc.). Would it be possible to add an additional method _getPercentiles_, that would return this new value. Or just implement a _getValues_ method, to return all values in one go?

**Comment by eborned** [comment]
I've created a patch and pull request to get the functionality I required: https://github.com/solariumphp/solarium/pull/396

**Comment by wickedOne** [comment]
fixed @ https://github.com/solariumphp/solarium/pull/398
