### ISSUE TITLE
Suggester query builder and response parser are using an old configuration

### ISSUE THREAD

**Issue by dpgover** [solariumphp/solarium#400]
Hi, 
First things first: I'm using version 3.5.1 and solr 5.3.1.

So I implemented the suggestion request handler in my solr. I'm using this configuration:

``` xml
<searchComponent class="solr.SuggestComponent" name="suggest">
    <lst name="suggester">
      <str name="name">suggest</str>
      <str name="storeDir">dict_suggest</str>

      <str name="lookupImpl">AnalyzingInfixLookupFactory</str>
      <str name="highlight">false</str>

      <str name="field">suggestion</str>
      <str name="suggestAnalyzerFieldType">suggest</str>

      <str name="dictionaryImpl">DocumentDictionaryFactory</str>
      <str name="payloadField">id</str>

      <str name="buildOnStartup">false</str>
      <str name="buildOnCommit">true</str>
    </lst>
  </searchComponent>

  <requestHandler name="/suggest" class="solr.SearchHandler" startup="lazy">
    <lst name="defaults">
      <str name="echoParams">explicit</str>
      <str name="suggest">true</str>
      <str name="suggest.dictionary">suggest</str>
      <str name="suggest.count">10</str>
    </lst>
    <arr name="components">
      <str>suggest</str>
    </arr>
  </requestHandler>
```

As I check the query string resulting of using the suggester query builder, I noticed that solarium uses `spellcheck` and `q`.
I bypass that by adding parameters explicitly like: `$suggester->addParam('suggest.q', $term);` for example.

But when the query gets executed and I try to parse the results as the docs say, I get an empty array. That's because the parser is expecting this `$data['spellcheck']['suggestions']` and solr returns `$data['suggest']['suggestions']`

More accurately, this is the response json I get: `{"suggest":{"suggest":{"ale":{"numFound":10,"suggestions":[{"term":"Alejandro","weight":0,"payload":"18"},{"term":"alerodahr","weight":0,"payload":"18"},{"term":"Alejandro","weight":0,"payload":"167"},{"term":"alejandroikonicoff","weight":0,"payload":"167"},{"term":"Alejandro","weight":0,"payload":"169"},{"term":"alejandrosciarrillo","weight":0,"payload":"169"},{"term":"Aleli","weight":0,"payload":"284"},{"term":"Alejandro","weight":0,"payload":"436"},{"term":"Ale","weight":0,"payload":"493"},{"term":"aleriedel","weight":0,"payload":"493"}]}}}}`

Am I using the incorrect query type? or do I need to parse the response in my code?

Thanks.

**Comment by basdenooijer** [comment]
The current Solarium code assumes the suggestcomponent is used with the 'spellcheck' requesthandler. This is hardcoded in the requestbuilder and responseparser for the suggest query type. 

I think this should be made configurable, because your config with a dedicated 'suggest' requesthandler is also valid.

**Comment by rakeshgithub** [comment]
I am on the same issue with SOLR 6.1, did you get any solution to fix it or bypass the solarium for it.

**Comment by rakeshgithub** [comment]
I am parsing the json received inside the Solarium object by decoding that:
$keyword = 'Searched word';
$objResultData = json_decode($resultset->getResponse()->getBody());
$objResults = $objResultData->suggest->suggest;
print_r($objResults->$keyword);

**Comment by sarcanon** [comment]
Same issue here with 6.1.0.
Thanks to @rakeshgithub for the workaround.

**Comment by farhantahir** [comment]
@rakeshgithub Thanks your solution worked for me so far, though I think Solarium should have option to configure this thing.

**Comment by mkalkbrenner** [comment]
https://github.com/solariumphp/solarium/commit/d88ed3fb547f5beaa0bfd69c19ef365b3109434d

**Comment by mkalkbrenner** [comment]
In the 4.x brnach you can now choose between the Suggest and the Spellcheck query and between the Spellcheck and the Suggest component.
