### ISSUE TITLE
highlighting not working when i am adding field name in query with sorting

### ISSUE THREAD

**Issue by nisha-kajale** [solariumphp/solarium#402]
Hi,

When i write a query as - attr_field:"test" and sort it by another field in ASCENDING order.
I am not getting any result in highlighting.

But if a write a query as - attr_field:"test" and sort it by SAME FIELD AS ABOVE in DESCENDING order i am getting results highlighted.

Can anyone help me ?

**Comment by basdenooijer** [comment]
It might be that the sort in descending order simply returns the worst matches, which have nog highlighting results. But it's hard to say without knowing the index and the data.

Does the 'attr_field' field contain the exact word 'test' for the documents that have no highlighting?
