### ISSUE TITLE
Sometimes buffer is not cleared

### ISSUE THREAD

**Issue by Valantir007** [solariumphp/solarium#403]
I use buffer plugin to indexing solr. Buffer size is 1000 and sometimes event to clear buffer is not colled... I checked my code and everything is ok - buffer has many then 1000 items so condition is always false:

`(count($this->buffer) == $this->options['buffersize'])`

in addDocument method. I don't know why buffer has much more items then declared size...

**Comment by basdenooijer** [comment]
I've used the buffer many times without issues. I'm not sure what would cause this. Can you provide a script, or manual steps, to reproduce this?

Or are you maybe using embedded documents?

**Comment by Valantir007** [comment]
No, I can not share the code... sorry. By "embedded" you mean using "multiValued"? Yes, I use multiValued.  My code is similar to:

In constructor i have:
`$this->solrClient->getEventDispatcher()->addListener(
        Events::PRE_FLUSH,
        function (PreFlushEvent $event) {
            echo 'Cleaning the buffer (' . count($event->getBuffer()) . ' documents)' . PHP_EOL;
        }
)`

`foreach ($products as $id => $product) {
    $row = [
        'categories' => [],
        'status' => 1
        'isbn' => 'string'
    ];
    $this->buffer->createDocument($row);
}
$this->buffer->flush(null, 1);
`

Maybe setting the condition to (count($this->buffer) >= $this->options['buffersize']) will solve the problem?

**Comment by basdenooijer** [comment]
To be honest I have no idea what the issue is. Maybe you can use a debugger session see what is being executed step by step.

**Comment by Valantir007** [comment]
Hmmm... I noticed that, when this problem occurred, I had to restart solr that everything was ok...
