### ISSUE TITLE
Using a own handler

### ISSUE THREAD

**Issue by jr-ewing** [solariumphp/solarium#407]
Hello Solarium-Team,
How can i define an other handler like "?select" ?
I have tried 
$client->registerQueryType('trvh'); 

But it don't work. 
This is the request i want to build.

http://149.xxx:8820/solr/SingleDomainSite_34_shard1_replica1/tvrh?q=site_term_maincontent:term&rows=1&tv.fl=site_term_maincontent&tv.all=true&shards.qt=/tvrh

best regards
Tom

**Comment by basdenooijer** [comment]
Maybe you can use a select query and call setHandler('trvh')?

**Comment by jr-ewing** [comment]
Yes, it works - was to simple for me :-) 

I was looking for create an new plugin, described here ->

http://solarium.readthedocs.org/en/stable/customizing-solarium/
Section: Plugin output

Thank you !!!
