### ISSUE TITLE
Upgrade symfony/event-dispatcher 

### ISSUE THREAD

**Issue by llewellynthomas** [solariumphp/solarium#409]
Hi, 

I'm not very familiar with this library, but our application has a dependency on your library.

I'm currently upgrading our stack to symfony 3 that requires 'symfony/event-dispatcher' 3, is there any plan to upgrade the symfony/event-dispatcher and if not I could look at your code and do a pull request. Is there anything reason that anyone knows why this might not be a good idea. Any pointers would be greatly appreciated. 

Thanks

**Comment by basdenooijer** [comment]
You're not the first one to run into this issue, see this PR: https://github.com/solariumphp/solarium/pull/388
 
A new release including this change still needs to be done, but if you are comfortable with it you could use a development version for now. 

This is also a good reminder for me to create a new release soon.

**Comment by llewellynthomas** [comment]
@basdenooijer thanks
