### ISSUE TITLE
404 error when using /solr/ as path - need to provide core

### ISSUE THREAD

**Issue by barrychapman** [solariumphp/solarium#414]
Is there a way to specify the core to use in the config? It seems we need to put the core in the path for it to work.

Thanks,
Barry

**Comment by basdenooijer** [comment]
I've just spotted that the 'core' config value is not handled correctly. For added the core to the path is indeed a workaround, or using the setCore method instead of config.

This will be fixed in the next release.

**Comment by mkalkbrenner** [comment]
this should be fixed
