### ISSUE TITLE
getDebug() on query returns null

### ISSUE THREAD

**Issue by barrychapman** [solariumphp/solarium#415]
I am running the following:

$config = array( 'endpoint' => array( 'localhost' => array( 'host' => '127.0.0.1', 'port' => 8983, 'path' => '/solr/Locations/' ) ) );

```
    $select = [
            'query'         => 'address1:304 MARKET PLZ',
            'start'         => 0,
            'rows'          => 20

    ];

    $client = new Client($config);
    $query = $client->createSelect($select);
    $resultset = $client->execute($query);
    $db = $resultset->getDebug();
    echo $db->getQueryString();
```

But when I run $db = $resultset->getDebug(), getDebug() returns 'null'

Why is this?

**Comment by basdenooijer** [comment]
You should enable debug in the query, this way Solarium can tell Solr to include this data in the response. For an example see:
http://solarium.readthedocs.org/en/stable/queries/select-query/building-a-select-query/components/debug-component/
