### ISSUE TITLE
[Suggestion] Customize facet rendering

### ISSUE THREAD

**Issue by bpolaszek** [solariumphp/solarium#422]
Hello,

I was wondering how to implement a feature that would allow to customize the values of a facet. 
It would be useful when working both with Solr & a SQL database.
For instance, let's assume I have the following data in my database:

| Id | City |
| --- | --- |
| 1 | New York |
| 2 | San Francisco |
| 3 | Los Angeles |

Now let's say I have a collection of restaurants in Solr:

``` json
[
    {
        "id"             : "2b4284bd-198a-4e0f-844f-0b56c60be8ee",
        "restaurant_name": "Burger King",
        "city_id"        : 1
    },
    {
        "id"             : "2e364d10-cc83-46ab-8591-1e0121ce0937",
        "restaurant_name": "Wendy's",
        "city_id"        : 3
    },
    {
        "id"             : "614f22fb-a5ba-4273-85cd-e4b89a53b152",
        "restaurant_name": "MacDonald's",
        "city_id"        : 2
    }
]
```

As you can see, I rely on the City's ID to organize my data.
Now, if I want to offer the user to filter by city, here's the code:

``` php
$facetCity = $query->getFacetSet()->createFacetField('city_id')->setField('city_id');
```

The problem is, the displayed result will be ids and not names (of course, because Solr don't know that city_id #2 means San Francisco) with their associated result count. When you render the result, via HTML or JSON, you have to make some ugly conditions to tell your app that #2 should be displayed as San Francisco.

What I suggest:
- Create a plugin (or a native feature) that will allow to set a callable in the facet building. The closure would be called after result rendering to change the facet values.

I was thinking about something like:

``` php
$facetCity->setOptions(['valueMap' => function ($value, $count) {
    return $this->getEntityManager()->getRepository(City::class)->find($value);
}]);
$eventDispatcher->addListener(Events::POST_EXECUTE, function (PostExecute $event) use ($query) {
    if ($query === $event->getQuery()) {
        $result = $event->getResult();
        $facets = $result->getFacetset()->getFacets();
        // Find the facets that have the 'valueMap' option and apply the closure
        // I currently don't know a simple way to do this
    }
});
```

The problems I encounter:
- Writing a plugin is complex: I can hook to `PostCreateResult` event, but the facet / facetset / result are kind of immutable (well, not really, but they don't have any setters for future modification)
- That feature should be available in any kind of facet (range, pivot, etc) and with the hopefully upcoming JSON facet API #378  ;-)
- The facet values are currently the keys of an array in the `Solarium\QueryType\Select\Result\Facet\Field` class. Since the keys would be replaced by unknown strings (may contain spaces, accents, etc), this may lead to issues with some templating languages. So instead of the following `value => count` existing schema: 

``` php
[
   2 => 6561
];
```

I would prefer something like this (BC break in 3...2...1):

``` php
[
    2 => [
        'count' => 6561,
        'label' => 2
    ],
];
```

It would then be easier, in the future, to transform `label => 2` to `label => 'San Francisco'`

What do you think about this feature ? In your opinion, what's the best way to implement it?

This is the example I currently have issues for, but we could go further in customizing with grouping, etc.

**Comment by basdenooijer** [comment]
I agree there is currently no easy way to implement such a thing. 
The valuemap you propose would be a solution for your case, but what happens if someone not only want to map the values, but also add additional data fields, or do something with the counts?

Maybe we should look at a more generic approach. Instead of switching the key-value array to a nested array we could also use value objects for facet results. I'm thinking about creating something like a FacetValueFactoryInterface which always returns instances of the FacetValueInterface. 
Default implementations will be provided by Solarium, and using the API you can set your own factory implementation to customize whatever you want. 

That way we have a solution that covers more than one use case, and is very flexible. This can also be easily applied to other result types.

**Comment by Asparagirl** [comment]
+1

**Comment by bpolaszek** [comment]
:+1: +1 too :)

**Comment by mkalkbrenner** [comment]
JSONFacets are already supported. Is anyone interested in providing a PR here or should we close the issue?
