### ISSUE TITLE
Allow Multiple Boost Queries (bq)

### ISSUE THREAD

**Issue by bmeynell** [solariumphp/solarium#423]
Solr documentation on [bq](https://cwiki.apache.org/confluence/display/solr/The+DisMax+Query+Parser#TheDisMaxQueryParser-Thebq(BoostQuery)Parameter) as used in conjunction with dismax/edismax:

> You can specify multiple bq parameters. If you want your query to be parsed as separate clauses with separate boosts, use multiple bq parameters.

Solarium seems to only support *one* Boost Query instead of *multiple*. For example, the following two example code snippets only send that *last* Boost Query set:

```php
$edismax = $query->getEDisMax();

// Using setBoostQuery() - only sets single bq=foo:396.
$edismax->setBoostQuery('foo:394');
$edismax->setBoostQuery('foo:396');

// Using addParam() - only sets single bq=foo:396.
$select->addParam('bq', 'foo:394');
$select->addParam('bq', 'foo:396');
```

**Comment by basdenooijer** [comment]
I think a recently introduced changed (very last release) may be what you need: https://github.com/solariumphp/solarium/pull/391

The docs might still need an update to reflect these changes.

**Comment by bmeynell** [comment]
Indeed, TY!
