### ISSUE TITLE
v3.6.0 shows v3.4.0

### ISSUE THREAD

**Issue by balmydrizzle** [solariumphp/solarium#428]
I use composer to install v3.6.0 but when I run 1.1-check-solarium-and-ping.php in examples (need to modify require path in init.php). it shows "Solarium library version: 3.4.0 - Ping query successful". Is this a bug or not?

**Comment by basdenooijer** [comment]
Yes, this is a bug, thanks for reporting!

I've just fixed the version declaration: https://github.com/solariumphp/solarium/commit/095d41a8d7ced6a346211b239d187c9a897869cb
