### ISSUE TITLE
v3.6.0 getQueryTime() returns null

### ISSUE THREAD

**Issue by petericebear** [solariumphp/solarium#430]
Hello,

Somehow I don't get the query time with $result->getQueryTime();
I am using SOLR 6.0.1. It keeps returning null as a response.

Greetings,
Peter

**Comment by basdenooijer** [comment]
The omitHeader setting is true by default, because the header adds some overhead to queries and is not used most of the time. 
If you call setOmitHeader(false) on your query object before execution you should get a query time in the response.

**Comment by petericebear** [comment]
Thanks that was the issue for me. Thanks for the swift reply.
