### ISSUE TITLE
How to dump raw query that is sent

### ISSUE THREAD

**Issue by matchdav** [solariumphp/solarium#432]
It is unclear in the docs how to extract the `params={q=stuff&bf=otherstuff...}` string that is being sent when Solarium sends a query.  I can see it in the Solr logs, but I would like to get at this within the API for all kinds of reasons.  Halp!?

**Comment by basdenooijer** [comment]
Check this example:
https://github.com/solariumphp/solarium/blob/master/examples/5.1-partial-usage.php

You probably need the $request->getUri() part.
If you need it for logging the best option is probably to create a simple plugin, see this example:
https://github.com/solariumphp/solarium/blob/master/examples/5.3.1-plugin-event-hooks.php
