### ISSUE TITLE
Empty grouping results when using group.func

### ISSUE THREAD

**Issue by pavelsmolka** [solariumphp/solarium#440]
When I use a grouping parameter `group.func`, calling `$result->getGrouping()->getGroups()` returns an empty array.

The underlying reason seems to be that `Solarium\QueryType\Select\ResponseParser\Component\Grouping` checks the Grouping fields in the response data. However, if the function is used, no grouping fields are set, and therefore the data is discarded.

It seems that checking for `$grouping->getFunction()` in the `parse` method of the mentioned class would fix this. If you can confirm my thinking is right, I can provide a pull request.

**Comment by basdenooijer** [comment]
I think that would be the correct solution. Currently only grouping fields and queries are checked, a function check should be added. I think large parts of the code for field group parsing could be reused (by abstracting them first).

**Comment by basdenooijer** [comment]
This has been resolved in #441
