### ISSUE TITLE
Where did the API docs go?

### ISSUE THREAD

**Issue by MadEgg** [solariumphp/solarium#442]
I'm pretty sure I saw generated API docs for Solarium in the past, but I can't seem to find the link anymore. I only found tutorial-style documentation. Where did the API-docs go? Thanks in advance for providing a link!

**Comment by basdenooijer** [comment]
They got lost when the transition was made to Github pages for the Solarium website some time ago. There still is an item on my todo list to somehow add the generation and publication of API docs to the CI process.

You could run phpdoc locally to generate your own set of docs, for now.

**Comment by MadEgg** [comment]
I already managed to build the docs using ApiGen, looks good. Still good to have an online reference though. Thanks for the reply! I'll see online when it arrives.
