### ISSUE TITLE
Searching docs doesn't work

### ISSUE THREAD

**Issue by nitinsurana** [solariumphp/solarium#445]
Hi,
1. Visit any docs url - http://solarium.readthedocs.io/en/stable/queries/ping-query/
2. Type say for e.g. "ping" in the search box on the top-left corner
3. Press Enter
4. Notice the results are blank, though there are pages with `ping` in it.

**Comment by basdenooijer** [comment]
Hmm, this seems to be an issue with readthedocs, the search function is included in their default functionality

**Comment by mkalkbrenner** [comment]
I don't think that we can do anything here.
