### ISSUE TITLE
responsewriter not working

### ISSUE THREAD

**Issue by nitinsurana** [solariumphp/solarium#447]
As per the docs, http://solarium.readthedocs.io/en/stable/solarium-concepts/

```
$query = $client->createQuery($client::QUERY_SELECT, array('responsewriter' => 'json'));
$query->setQuery('title:' . $q . ' and desc:' . $q)->setRows(20);
$resultset = $client->execute($query);
```

above code should return `$resultset` as `json`, but it's an instance of `Query\Result`, no matter what's the value of `responsewriter` (any random value).

**Comment by basdenooijer** [comment]
Json is being used as the Solr response format, however you get a Result object instance returned by this method. This object allows you to access to response in multiple ways:

- most common use case is to use the response API for fetching documents, facets, etcetera
- you can also use $result->getData() to get the decoded json array
- if you really want the 'raw' JSON, you can use $result->getResponse()->getBody()

**Comment by nitinsurana** [comment]
Thanks, `getData()` is what I was looking for.
