### ISSUE TITLE
Key and excludes for facet intervals

### ISSUE THREAD

**Issue by thomascorthals** [solariumphp/solarium#448]
Functionality for setting a key and adding exclude to facet intervals is commented out in the [FacetSet component](https://github.com/solariumphp/solarium/blob/master/library/Solarium/QueryType/Select/RequestBuilder/Component/FacetSet.php#L250). I have removed the comment and it does work as far as I can tell (against Solr 5.5 in my case). Could this functionality be restored permanently?

**Comment by basdenooijer** [comment]
In that case I think we could restore it, maybe we should also check if this doesn't cause issues for older Solr versions (4.x). However, I think that's not very likely, it will probably just be ignored if not supported.

**Comment by vlastv** [comment]
This fixed for Solr 5 and 6, I created PR #431
