### ISSUE TITLE
Possible internal array pointer access/modification in a by-value foreach loop

### ISSUE THREAD

**Issue by elvispdosreis** [solariumphp/solarium#454]
File: Solarium\QueryType\Analysis\ResponseParser\Field.php

> Line 114: Possible internal array pointer access/modification in a by-value foreach loop
>     current($typeData);

**Comment by thomascorthals** [comment]
I do believe this is a false positive. It looks like output from [php7cc](https://github.com/sstalle/php7cc), which has been discontinued.

Without looking at its code, I assume it naïvely checks for any use of `current()` in a `foreach` loop. In this case, it isn't used on the array being looped over but on the value (that happens to be an array) in the current iteration. The array-being-looped-over's internal array pointer isn't accessed.

@mkalkbrenner If neither phpstan nor phpunit has a problem with it, this issue can be closed.

**Comment by thomascorthals** [comment]
@mkalkbrenner Just pinging you again in this one. I'm certain that it can be closed.

**Comment by wickedOne** [comment]
agreed, this appears to be a false positive
