### ISSUE TITLE
setMethod(POST)

### ISSUE THREAD

**Issue by gorankrgovic** [solariumphp/solarium#457]
Hi all,

I cannot find anywhere, how to set Request method to POST instead of GET. I have a large filter query and constantly have an error 414. This is not covered in documentation so please help me to init the class with POST request method instead of the default GET. 
Thanks

**Comment by basdenooijer** [comment]
Hi, I think this will solve it: http://solarium.readthedocs.io/en/latest/plugins/#postbigrequest-plugin

**Comment by gorankrgovic** [comment]
Many many thanx
