### ISSUE TITLE
Authentication does not work with the default curl adapter

### ISSUE THREAD

**Issue by pavneet9** [solariumphp/solarium#458]
I am using the default curl adpater to connect with my solr instance on google cloud.

I have solarium 3.0.0

I have tried both the methods.

1) Set authentication method -

I get this error

 `Call to undefined method Solarium\Client::setAuthentication() in /var/www/html/add_toknowledgemaps.php on line 404
`
2) End point method
```
$config4 = array(
    'endpoint' => array(
        'localhost' => array(
            'host' => '104.18.218.2',
            'port' => 80,
            'core' => 'search_suggest',
            'path' => '/solr/',
              'username' => 'user',
                'password' => 'passowrd'
        )
    )
);

In this case i get this error:-

`'Solarium\Exception\HttpException' with message 'Solr HTTP error: OK (401)
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
' in /var/www/html/vendor/solarium/solarium/library/Solarium/Core/Query/Result/Result.php:104
Stack trace:
#0 /var/www/html/vendor/solarium/solarium/library/Solarium/Core/Client/Client.php(726): Solarium\Core\Query\Result\Result->__construct(Object(Solarium\Client), Object(Solarium\QueryType\Update\Query\Query), Object(Solarium\Core\Client\Response))
#1 /var/www/html/vendor/solarium/solarium/library/Solarium/Core/Client/Client.php(757): Solarium\Core\Client\Client->createResult(Object(Solarium\QueryType\Update\Query\Query), Object(Solarium\Cor in /var/www/html/vendor/solarium/solarium/library/Solarium/Core/Query/Result/Result.php on line 104`

How do you set up authentication with the default curl adapter


```

**Comment by basdenooijer** [comment]
Method 2 should work. Maybe you can check the request that's being created
by Solarium. You can do this using a breakpoint, or alternatively by
calling $request = $client->createRequest($query); and checking the
contents of $request.


Met vriendelijke groet / Kind regards,
Bas de Nooijer

Raspberry | Web application specialist

Member of Dutch Web Alliance - leaders in web technology
https://www.dutchweballiance.nl <http://www.dutchweballiance.nl>

2016-11-03 16:25 GMT+01:00 pavneet9 <notifications@github.com>:

**Comment by mkalkbrenner** [comment]
Since there's no more feedback and drupal's Search API Solr Search uses solarium with curl and basic authentication I' ll close this issue.
