### ISSUE TITLE
/autoload.php failed to open

### ISSUE THREAD

**Issue by manusrivastav** [solariumphp/solarium#459]
/autoload.phpfailed to open

**Comment by pawel-dubiel** [comment]
https://github.com/solariumphp/solarium/issues/356

**Comment by floriansemm** [comment]
You have to run composer to install all project dependencies.

Installation with git:
```
git clone https://github.com/solariumphp/solarium.git
cd solarium
composer install
```

**Comment by thePanz** [comment]
Closing as the correct way to use this library is via Composer.
