### ISSUE TITLE
Solr HTTP error: HTTP request failed, Failed to connect to 127.0.0.1 port 8983: Bad access...

### ISSUE THREAD

**Issue by tesmai4** [solariumphp/solarium#460]
My Solr server and PHP web site is working on Windows.  I ported PHP as a webapp on Azure in a Ubuntu VM.

Solr server is accessible from http://127.0.0.1:8983 and sample PHP pages are independently working. 

However, I am getting the following error while connecting PHP Solarium and Solr server from PHP pages:

Fatal error: Uncaught exception 'Solarium\Exception\HttpException' with message 'Solr HTTP error: HTTP request failed, Failed to connect to 127.0.0.1 port 8983: Bad access' in D:\home\site\wwwroot\vendor\solarium\solarium\library\Solarium\Core\Client\Adapter\Curl.php:195 Stack trace: #0 D:\home\site\wwwroot\vendor\solarium\solarium\library\Solarium\Core\Client\Adapter\Curl.php(92): Solarium\Core\Client\Adapter\Curl->check('', Array, Resource id #3) #1 D:\home\site\wwwroot\vendor\solarium\solarium\library\Solarium\Core\Client\Adapter\Curl.php(213): Solarium\Core\Client\Adapter\Curl->getResponse(Resource id #3, false) #2 D:\home\site\wwwroot\vendor\solarium\solarium\library\Solarium\Core\Client\Adapter\Curl.php(68): Solarium\Core\Client\Adapter\Curl->getData(Object(Solarium\Core\Client\Request), Object(Solarium\Core\Client\Endpoint)) #3 D:\home\site\wwwroot\vendor\solarium\solarium\library\Solarium\Core\Client\Client.php(804): Solarium\Core\Client\Adapter\Curl->execute(Object(Solarium\Core\Client\Request), Object(Solarium\C in D:\home\site\wwwroot\vendor\solarium\solarium\library\Solarium\Core\Client\Adapter\Curl.php on line 195

Any help is appreciated.

**Comment by floriansemm** [comment]
This stack trace shows a windows environment. Where does the bad request error occurs on a windows  or ubuntu machine?

**Comment by bossliu609** [comment]
I use solarium on a CentOS macheine,and I have the same problem?
Could someone help to solve that?

**Comment by floriansemm** [comment]
Looks more like a problem with your local setup.

Does `curl http://127.0.0.1:8983/solr/your-core/query -d 'q=*:*'` work?

**Comment by bossliu609** [comment]
I have tried to **curl http://127.0.0.1:8983/solr/your-core/query -d 'q=*:*'**
it does have expected results like this

**[root@centos-4 solr-6.3.0]# curl http://127.0.0.1:8983/solr/bsfile/query -d 'q=*:*'
{
  "responseHeader":{
    "status":0,
    "QTime":34,
    "params":{
      "q":"*:*"}},
  "response":{"numFound":2,"start":0,"docs":[
      {
        "title":["aaaa.docx"],
        "size":92595,
        "lastModified":"2016-12-29T22:16:50Z",
        "id":"/usr/local/Docs/aaaa.docx",
        "author":"MC SYSTEM",**

**Comment by bossliu609** [comment]
I know the reason why ping failed .
because the selinux enforcing
the port 8983 do not work
thanks anyway

**Comment by mkalkbrenner** [comment]
If you still have problems, feel free to re-open the issue.
