### ISSUE TITLE
conflict with your requirements or minimum-stability.

### ISSUE THREAD

**Issue by bossliu609** [solariumphp/solarium#473]
When I run composer install   in CentOS 6.8
like this 
[root@centos-4 html]# composer require solarium/solarium
 but it always appear a problem
all the message show 
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package solarium/solarium No version set (parsed as 1.0.0) is satisfiable by solarium/solarium[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.
[root@centos-4 html]# 

how to solve the problem 1?
thanks for somebody can help me

**Comment by floriansemm** [comment]
What happens if you require a version like `composer require solarium/solarium:^3.7`?

**Comment by bossliu609** [comment]
oh , I have found method to solve this problem.
In the composer.json file 
if  **"solarium/solarium": "^3.7",** is added in the "require" column 
 _"require": {
        "php": ">=5.3.2",
		**"solarium/solarium": "^3.7",**
        "symfony/event-dispatcher": "~2.3|~3.0",
		"guzzlehttp/guzzle": "~3.0"
    },_
you must add **"version":"3.7.0",** or some in the composer.json file
like this
_{
    "name": "solarium/solarium",
	**"version":"3.7.0",**
    "type": "library",
    "description": "PHP Solr client",
    "keywords": ["solr", "search", "php"],
    "homepage": "http://www.solarium-project.org",
    "license": "BSD-3-Clause",
    "authors": [
        {
            "name": "See GitHub contributors",
            "homepage": "https://github.com/basdenooijer/solarium/contributors"
        }
    ],
    "require": {
        "php": ">=5.3.2",
		"solarium/solarium": "^3.7",
        "symfony/event-dispatcher": "~2.3|~3.0",
		"guzzlehttp/guzzle": "~3.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~3.7",
        "squizlabs/php_codesniffer": "~1.4",
        "zendframework/zendframework1": "~1.12",
        "satooshi/php-coveralls": "~1.0"
    },
    "suggest": {
        "minimalcode/search": "Query builder compatible with Solarium, allows simplified solr-query handling"
    },
    "extra": {
        "branch-alias": {
            "dev-develop": "3.3.x-dev"
        }
    },
    "autoload": {
        "psr-0": { "Solarium\\": "library/" }
    }
}_


And thank you all the same @nathanpbell
