### ISSUE TITLE
Try to check ping, but appears nothing

### ISSUE THREAD

**Issue by NerdKid** [solariumphp/solarium#476]
Please help me

I just installed SOlarium via composer.json. And then i try to ping solr  but shows nothing. It only prints solarium version
Result: Solarium library version: 3.4.0 -
And in browser console , it gives error which 500 internal server error. 
I copied this code:

require(__DIR__.'/init.php');

// check solarium version available
echo 'Solarium library version: ' . Solarium\Client::VERSION . ' - ';

// create a client instance
$client = new Solarium\Client($config);

// create a ping query
$ping = $client->createPing();

// execute the ping query
try {
    $result = $client->ping($ping);
    echo 'Ping query successful';
    echo '<br/><pre>';
    var_dump($result->getData());
    echo '</pre>';
} catch (Solarium\Exception $e) {
    echo 'Ping query failed';
}

**Comment by floriansemm** [comment]
try `require(__DIR__.'/init.php');`

**Comment by chadicus** [comment]
@floriansemm the bold __DIR__ was just github markdown. @NerdKid  is using `__DIR__`

**Comment by floriansemm** [comment]
okay! So what was the exact error-message?

**Comment by chadicus** [comment]
@NerdKid change your `catch` statement to catch the generic `Exception` then echo `$e->getMessage()` Paste the output here.

**Comment by mkalkbrenner** [comment]
A real ping test was just added by #537 and it works fine with Solr 6 and 7.
