### ISSUE TITLE
Search function on documentation page is broken

### ISSUE THREAD

**Issue by mikl** [solariumphp/solarium#482]
Trying to peruse [the docs](http://solarium.readthedocs.io/en/stable/) is quite frustrating, since the search function doesn't work. Searching for “Solr” takes you to [this page](https://readthedocs.org/search/?q=solr&check_keywords=yes&area=default&project=solarium&version=stable&type=file) which says there's no results. Clearly, there's like a thousand matches for this word in the text, so something is clearly wrong.

I've tried other words or phrases, nothing gives any results.

**Comment by mkalkbrenner** [comment]
fixed: https://solarium.readthedocs.io/en/latest/
