### ISSUE TITLE
Class 'Solarium\Client' not found

### ISSUE THREAD

**Issue by Tranbook** [solariumphp/solarium#488]
I use Solr6.3.0 and Solarium 3.8.1 for work,
After I install Solarium via composer method,I try to check the examples working or not,
but I found that **Class 'Solarium\Client' not found**
All the tips is 
**Fatal error: Class 'Solarium\Client' not found in /home/wwwroot/c1.ciee.com/solarium/examples/1.1-check-solarium-and-ping.php on line 7**

**Comment by floriansemm** [comment]
the example includes `init.php` which requires the autoload.php under `__DIR__.'/../vendor/`

Please check if this path is correct in your local setup.

**Comment by mkalkbrenner** [comment]
Since there's no more feedback I'll close this one.
