### ISSUE TITLE
Unnecessary (?) use of ini_get in Curl Adapter

### ISSUE THREAD

**Issue by ejn** [solariumphp/solarium#492]
In many hosting environments, the function ini_get is disabled for security reasons. In this case the Curl Adapter creates warnings due to the attempt to check the value of open_basedir.

This could be easily fixed using a check on function_exists('ini_get'), which returns FALSE in the case that this function is disabled.

**Comment by mkalkbrenner** [comment]
Since #493 is committed, we can close this one
