### ISSUE TITLE
Spellcheck Component Solr 6.5.0 ready

### ISSUE THREAD

**Issue by stockii** [solariumphp/solarium#494]
After an upgrade of my solr to 6.5.0, solarium is broken. This is my old code, but this doesn't work, because Apache changed the response of the spellcheck component...

/** @var Spellcheck $Spellcheck */
 $Spellcheck = $this->Result->getSpellcheck();

**Comment by mkalkbrenner** [comment]
same in drupal search_api_solr. The tests fail if executed on 6.5.0 while 6.4.x works.
https://travis-ci.org/mkalkbrenner/search_api_solr/builds/221818438

**Comment by mkalkbrenner** [comment]
related: https://github.com/solariumphp/solarium/pull/472

**Comment by stockii** [comment]
The ResponseParser of Spellcheck need to be updated. 
For me i found a workaround ... just "disable" the parse() function in Spellcheck.php and implement an own function to get the results directly from the response. Hopefully someone can fix this issue :D

**Comment by waynedyck** [comment]
I don't use Solarium, however, I wouldn't suggest modifying any code to fix it as the issue has been addressed with [SOLR-10522](https://issues.apache.org/jira/browse/SOLR-10522). The result was a bug introduced in 6.5.0 with [SOLR-9972](https://issues.apache.org/jira/browse/SOLR-9972). That commit was reverted on May 8 and the change pushed into 6.6.

This would also address issue #500

**Comment by mkalkbrenner** [comment]
I confirm that Solr 6.6.0 solves the issue! 
Our Drupal integration tests that fail with Solr 6.5.x are passing again with Solr 6.6.0:
https://www.drupal.org/node/2869529

**Comment by mkalkbrenner** [comment]
The bug is solved in Solr 6.6.0. It's not a solarium issue.
