### ISSUE TITLE
Atomic Updates REMOVE modifier

### ISSUE THREAD

**Issue by pauf** [solariumphp/solarium#499]
Hi,

I realise this was discussed as issue #277 , but it appears something isn't right.

I've looked in the source code, and all that was added was the option to allow the constant MODIFIER_SET to be set to "remove", which doesn't actually appear to do anything anywhere else, other than not spit out an error.

I am attempting to remove an entry from a multi-value field. I've tried multiple ideas, but right now I'm using:

$document->removeField('mymultivalue', 'apple');
$document->setFieldModifier('mymultivalue', 'remove');
Of course 'apple' is indeed set for this particular multi-valued field.

But I'm not getting anywhere at all.

Also tried:

$document->setField('mymultivalue', 'apple');
$document->setFieldModifier('mymultivalue', 'remove');

$document->addField('mymultivalue', 'apple');
$document->setFieldModifier('mymultivalue', 'remove');

Maybe this wasn't implemented correctly to begin with, or maybe I am confused. Either way there doesn't seem to be much in the way of documentation for this feature after multiple searches. 

Can anyone please point me in the right direction?

Thanks for any responses!

**Comment by thomascorthals** [comment]
You have to use `setKey` to set the unique id by which the document is identified in Solr.

```php
$document->setKey('id', 123);
$document->setField('mymultivalue', 'apple');
$document->setFieldModifier('mymultivalue', $document::MODIFIER_REMOVE);
```

Your schema has to meet certain criteria for atomic updates to work at all. You'll find them in the [Solr Reference Guide](https://lucene.apache.org/solr/guide/updating-parts-of-documents.html#atomic-updates).

We'll add an example to the Solarium docs.
