### ISSUE TITLE
Feature Request: Support the new Unified Highlighter

### ISSUE THREAD

**Issue by Deewde** [solariumphp/solarium#517]
The new [Unified Hightlighter](https://cwiki.apache.org/confluence/display/solr/Highlighting#Highlighting-TheUnifiedHighlighter) has been added in [Solr 6.5.0](https://cwiki.apache.org/confluence/display/solr/Upgrading+Solr), which Solarium can't use yet.

> A new highlighter named UnifiedHighlighter has been added. You are encouraged to try out the UnifiedHighlighter by setting hl.method=unified and report feedback. It might become the default in 7.0. It's more efficient/faster than the other highlighters, especially compared to the original Highlighter.

**Comment by mooman** [comment]
I'm using the CustomizeRequest plugin for this:

```php
    $customizer = $client->getPlugin('customizerequest');
    $hlOptions = array(
      'method' => 'unified',
      'tag.pre' => '<strong>',
      'tag.post' => '</strong>',
      'defaultSummary' => 'true',
      'offsetSource' => 'ANALYSIS'
    );  

    foreach($hlOptions as $name => $value) {
      $customizer->createCustomization(array(
        'key' => "hl.$name",
        'type' => 'param',
        'name' => "hl.$name",
        'value' => $value
      )); 
    } 
```

**Comment by thomascorthals** [comment]
@Deewde [Solarium 6.2.4](https://github.com/solariumphp/solarium/releases/tag/6.2.4) was released with updated support for all current highlighting options in Solr.

@mooman's example can now be written natively as:
```php
// create a client instance
$client = new Solarium\Client($adapter, $eventDispatcher, $config);

// get a select query instance
$query = $client->createSelect();
$query->setQuery('memory');

// get highlighting component and apply settings
$hl = $query->getHighlighting();
$hl->setMethod($hl::METHOD_UNIFIED);
$hl->setTagPrefix('<strong>');
$hl->setTagPostfix('</strong>');
$hl->setDefaultSummary(true);
$hl->setOffsetSource($hl::OFFSETSOURCE_ANALYSIS);
```

A full overview of the supported options can be found in the [Solarium documentation](https://solarium.readthedocs.io/en/stable/queries/select-query/building-a-select-query/components/highlighting-component/).
