### ISSUE TITLE
Pagination example

### ISSUE THREAD

**Issue by markusdanek** [solariumphp/solarium#521]
Hey,

is there a code example how to implement a pagination system with Solarium (e.g. ten results per page)? Already searched for it but all example are from 2011 or older!

Thanks,
Markus

**Comment by laurinomme-helmes** [comment]
Option one is to use `\Solarium\QueryType\Select\Query\Query` methods `setStart` & `setRows`.
Another way is to use [deep paging](http://yonik.com/solr/paging-and-deep-paging/) with cursorMark (it's not implemented in Solarium but the patch to enable it is a <20 lines.

**Comment by thePanz** [comment]
@laurinomme-helmes can you provide such a patch to implement the deep-paging? it would be great when paginating over a hug result-set!

Closing this issue, as the documentation has been updated.
