### ISSUE TITLE
Using Solarium with Amazon CloudSearch

### ISSUE THREAD

**Issue by mefiblogger** [solariumphp/solarium#522]
Hello,

This is not really an issue, more like a question: I'm wondering if there's anyone using Solarium with Amazon CloudSearch? We are planning to switch from Solr to Amazon CloudSearch and for the first sight the two APIs seems compatible, but I'd like to talk with someone who has hands-on experience in the topic.

Thanks in advance,
Mefi

**Comment by extrarius** [comment]
Honestly you would be better off using the AWSSDK for this, while Amazon CloudSearch does share similar behavior to Solr it is not same (especially with regards to facets)

**Comment by mkalkbrenner** [comment]
@extrarius Thanks for the explanation.
