### ISSUE TITLE
How to fire a delta-import?

### ISSUE THREAD

**Issue by rkorebrits** [solariumphp/solarium#525]
I've checked though the documentation, but working how I can fire a `delta-import`? Doing this makes a lot more sense to me than writing additional custom logic to add records to the index. 

Is this possible via solariumphp? Or would you rather suggest a cron job on the minute calling the delta-import?

**Comment by mkalkbrenner** [comment]
Can you explain that more detailed?

**Comment by zb010** [comment]
This question is related to the DIH. There you can configure "full import" and "delta import" queries (SQL). https://wiki.apache.org/solr/DataImportHandler

The Solr admin has a nice interface of doing full and delta import using Angular.
A response kind of looks like this:

```
{
  "responseHeader":{
    "status":0,
    "QTime":3},
  "initArgs":[
    "defaults",[
      "config","data-config.xml"]],
  "command":"delta-import",
  "status":"idle",
  "importResponse":"",
  "statusMessages":{
    "Total Requests made to DataSource":"1",
    "Total Rows Fetched":"1304",
    "Total Documents Processed":"1304",
    "Total Documents Skipped":"0",
    "Full Dump Started":"2018-01-04 23:59:53",
    "":"Indexing completed. Added/Updated: 1304 documents. Deleted 0 documents.",
    "Committed":"2018-01-04 23:59:53",
    "Time taken":"0:0:0.286"}}
```

You are gonna need a cronjob anyways. I don't see this related to solariumphp.

**Comment by thomascorthals** [comment]
There is no built-in query type for the Data Import Handler because that's not typically something you'd do through a web application. It is possible to do it though, thanks to the extensible nature of Solarium. The easiest way is by modifying a Ping query.

```php
$query = $client->createPing();
$query->setHandler('dataimport');
$query->addParam('command', 'delta-import');
// add any other parameters you need

try {
    $result = $client->execute($query);
    $resultData = $result->getData();

    echo 'status: ', $resultData['status'], PHP_EOL;
    echo 'importResponse: ', $resultData['importResponse'], PHP_EOL;
    echo 'statusMessages:', PHP_EOL;

    foreach ($resultData['statusMessages'] as $type => $message) {
        echo '- ', $type, ': ', $message, PHP_EOL;
    }
} catch (Exception $e) {
    // ...
}
```

Keep in mind that the import runs asynchronously. The first request will return very little output.

```
status: idle
importResponse: 
statusMessages:
```

Subsequent requests will return more status info.

```
status: idle
importResponse: 
statusMessages:
- Time Elapsed: 0:17:10.62
- Total Requests made to DataSource: 1
- Total Rows Fetched: 0
- Total Documents Processed: 0
- Total Documents Skipped: 0
- Delta Dump started: 2021-06-30 08:52:21
- Identifying Delta: 2021-06-30 08:52:21
- Delta Import Failed: 2021-06-30 08:52:22
```

(Output from running the snippet on the `db` core of a DIH example server launched with `bin/solr -e dih`.)
