### ISSUE TITLE
Solr 7.1 spellcheck

### ISSUE THREAD

**Issue by alimo2** [solariumphp/solarium#528]
Hi
I'm running solr 7.1 & check spellcheck example (2.1.5.9-spellcheck.php), but in line 24:
`$spellcheckResult = $resultset->getSpellcheck();`

$spellcheckResult is null! what shall i do?

But `localhost:8983/solr/testcore/spell?df=text&spellcheck.q=exampel&spellcheck=true` has results as expected.

what is the problem? any incompatibility between solariumphp and newest version of solr?

**Comment by alimo2** [comment]
What a pity such a best solr client library with no support!!

**Comment by mkalkbrenner** [comment]
I just started to go through the issues. It would be great if you can post any additional info you probably have now.

**Comment by mkalkbrenner** [comment]
No feedback for one week. What a pity!

;-)

If you switch to the 4.x branch you should get spellcheck results. Can you confirm that?

**Comment by mkalkbrenner** [comment]
Our automated tests fetch results from Solr 7.2.0 containing spellcheck and suggest.
