### ISSUE TITLE
How to execute percentiles functionality?

### ISSUE THREAD

**Issue by JigneshR** [solariumphp/solarium#534]
Hello,

Is there code example for Percentiles stats ? As In Stats component, getPercentiles() method there, but how to use this method/related functionality not defined.

In change log ## 3.6.0 - 2016-05-03
     - added: support for additional stats values like percentiles

Can you update example : 2.1.5.10-stats.php ?

**Comment by thomascorthals** [comment]
[Solarium 6.1.5](https://github.com/solariumphp/solarium/releases/tag/6.1.5) was released with improved support for the Stats Component, including a bugfix for percentiles.

There's a dedicated example in [2.1.5.10.1-stats-percentiles.php](https://github.com/solariumphp/solarium/blob/master/examples/2.1.5.10.1-stats-percentiles.php) and a mention in the [docs](https://solarium.readthedocs.io/en/stable/queries/select-query/building-a-select-query/components/stats-component/).
