### ISSUE TITLE
No data in Suggester\Result\Result when using Solr Suggest

### ISSUE THREAD

**Issue by zb010** [solariumphp/solarium#536]
Pull request #472 addresses an issue where `spellcheck` was used in stead of `suggest`. But the `Result` is still empty when using `$client->createSuggester()`.

 The suggester result given by Solr is like:

```json
{
	responseHeader: {
		status: 0,
		QTime: 5
	},
	suggest: {
		mySuggester: {
			foo: {
				numFound: 1,
				suggestions: [
					{
						term: "<b>foo</b>bar",
						weight: 0,
						payload: ""
					}
				]
			}
		}
	}
}
```
But this cannot be retrieved because it's not parsed correctly. 
I guess it's related to #528 too.

Edit: only `$result->getResponse()->getBody()` has a "plain-text" output. 
Edit 2: maybe I'm not understanding the proper use of the lib, I found out `$client->suggester($query)->getData()` does give back an array. Which is better of course than parsing `getBody()`. But it's still "just an array" and not structured data. But like i said, maybe i'm not getting it correctly.

**Comment by mkalkbrenner** [comment]
Which version of solarium are you using?

**Comment by zb010** [comment]
I'm using the 4.x branch

**Comment by mkalkbrenner** [comment]
The highly experimental new branch ;-)
Thanks for the early testing. I merged #501 as WIP.
#538 should finish the suggester feature and you should see results. Can you test it?
In addition #538 brings back the 3.x behavior but correctly named as Spellcheck.

**Comment by zb010** [comment]
I've been doing some testing with the updates in the 4.x branch but I can't get suggestions yet. But maybe I'm doing it wrong, because I'm a bit confused about the suggest vs. spellcheck issues.

This is what I did: 

- Downloaded a Solr 7.2 instance
- Started the `techproducts` example
- Got the 4.x lib via `composer require solarium/solarium:4.x-dev`
- Copied the contents of the `2.6-suggester-query.php` example
- Modified the setQuery line to `$query->setQuery('c');` to make sure their *are* suggestions in Solr

But where Solr has this response (used wt XML for improved readability):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<response>

<lst name="responseHeader">
  <int name="status">0</int>
  <int name="QTime">1</int>
</lst>
<lst name="suggest">
  <lst name="mySuggester">
    <lst name="c">
      <int name="numFound">4</int>
      <arr name="suggestions">
        <lst>
          <str name="term">camera</str>
          <long name="weight">329</long>
          <str name="payload"/>
        </lst>
        <lst>
          <str name="term">copier</str>
          <long name="weight">179</long>
          <str name="payload"/>
        </lst>
        <lst>
          <str name="term">connector</str>
          <long name="weight">19</long>
          <str name="payload"/>
        </lst>
        <lst>
          <str name="term">currency</str>
          <long name="weight">0</long>
          <str name="payload"/>
        </lst>
      </arr>
    </lst>
  </lst>
</lst>
</response>
```
my "program" has this resonse in `resultset`

```
Result {#11 ▼
  #status: null
  #queryTime: null
  #results: null
  #all: null
  #parsed: false
  #response: Response {#10 ▼
    #headers: array:1 [▼
      0 => "HTTP/1.1 200 OK"
    ]
    #body: """
      {\n
        "command":"build",\n
        "suggest":{"mySuggester":{\n
            "c":{\n
              "numFound":4,\n
              "suggestions":[{\n
                  "term":"camera",\n
                  "weight":329,\n
                  "payload":""},\n
                {\n
                  "term":"copier",\n
                  "weight":179,\n
                  "payload":""},\n
                {\n
                  "term":"connector",\n
                  "weight":19,\n
                  "payload":""},\n
                {\n
                  "term":"currency",\n
                  "weight":0,\n
                  "payload":""}]}}}}\n
      """
    #statusCode: 200
    #statusMessage: "OK"
  }
  #data: null
  #query: Query {#6 ▼
    #options: array:10 [▼
      "handler" => "suggest"
      "resultclass" => "Solarium\QueryType\Suggester\Result\Result"
      "dictionaryclass" => "Solarium\QueryType\Suggester\Result\Dictionary"
      "termclass" => "Solarium\QueryType\Suggester\Result\Term"
      "omitheader" => true
      "build" => true
      "reload" => false
      "query" => "c"
      "dictionary" => "mySuggester"
      "count" => 10
    ]
    #helper: null
    #params: []
  }
}
```

I'd like to do some more testing in the future.

**Comment by mkalkbrenner** [comment]
the examples were not up to date :-(

TechproductsTest.php would have been the better source for example code.
I'm not yet completely happy with the way the terms are accessed, but the structure is close to Solr itself.

It basically works now, but there still some more things to improve with spellcheck (and suggester). I'm working on it ...

**Comment by mkalkbrenner** [comment]
some more work has been done https://github.com/solariumphp/solarium/commit/4a16523d3586c04fba6d16c8a7cbe05e91dbc4f4

**Comment by zb010** [comment]
I can confirm the `2.6-suggester-query.php` does work now.

**Comment by mkalkbrenner** [comment]
thanks for the feedback!
