### ISSUE TITLE
Include Coding stles fixes

### ISSUE THREAD

**Issue by thePanz** [solariumphp/solarium#558]
I suggest to include and run php-cs-fixer on the main code of the project, just to comply to some coding standards.

**Comment by mkalkbrenner** [comment]
I agree

**Comment by bmeynell** [comment]
> ... just to comply to some coding standards.

[PSR-2](http://www.php-fig.org/psr/psr-2/) in particular (which is a superset of PSR-1) which is what [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) was built to do.
