### ISSUE TITLE
Add method removeParam to Query

### ISSUE THREAD

**Issue by timohund** [solariumphp/solarium#579]
With addParam unssuported parameters can be added. It would be nice to have the possibility to remove a param as well, e.g. by adding a method removeParam($name).

**Comment by mkalkbrenner** [comment]
Sounds right.
But depending on the concrete parameter, some RequestBuilders will not remove the paramter but fall back to a default value for it.
So, for unknown parameters a removeParam() method will immediately work, for known / expected ones it will trigger a default value. Is that what you need?

**Comment by timohund** [comment]
Hi @mkalkbrenner sorry for the delay, that is what i need. I'll prepare a pr for that.
