### ISSUE TITLE
BufferedAdd post commit suppose to return DocumentInterface[] but returns Solarium\QueryType\Update\Result

### ISSUE THREAD

**Issue by haydenyoung** [solariumphp/solarium#587]
I have registered a post commit even trigger using:

```
        $client->getEventDispatcher()->addListener(
            Events::POST_COMMIT,
            function (\Symfony\Component\EventDispatcher\Event $event) {
                var_dump($event->getResult());
            }
        );
```

The phpdoc documentation says that $event->getResult() will return an array of array of \Solarium\QueryType\Select\Result\DocumentInterface but when I review the output of the var_dump I see Solarium\QueryType\Update\Result.

Checking the getResult() method it is indeed simply returning an instance of the Result class.

What should this method be returning? The Result object or an array of DocumentInterfaces?

**Comment by mkalkbrenner** [comment]
Are you already using 4.x?

**Comment by haydenyoung** [comment]
Sorry for the (very) late reply. Just updated to 4.x and problem resolved.

Thanks
