### ISSUE TITLE
Support joining across collections

### ISSUE THREAD

**Issue by ernestoallely** [solariumphp/solarium#589]
The method join included on Solarium\Core\Query\Helper.php does not support joining across collections as defined on the documentation.

https://lucene.apache.org/solr/guide/7_3/other-parsers.html#joining-across-collections

Would it be possible to extend the method to support this functionality?

**Comment by mkalkbrenner** [comment]
For sure, it's possible. But I'm not convinced that we should support every feature in that way. There're already a lot of advanced features we don't support directly via API. But you can indirectly use them, for example by using the addParam() function.

I already used such joins heavily with solarium, but as part of streaming expressions.
