### ISSUE TITLE
Search with filters and facets with keywords only

### ISSUE THREAD

**Issue by khashabawy** [solariumphp/solarium#598]
Hi guys ,

How can i use solarium to get search results with filters and keywords but get facets related to the keywords only ?

**Comment by thomascorthals** [comment]
You have to add a tag to your filter queries. That tag can be used to exclude that specific filter from the facet calculations.

```php
<?php

require(__DIR__.'/init.php');
htmlHeader();

// create a client instance
$client = new Solarium\Client($config);

// get a select query instance
$query = $client->createSelect();

// set a query
$query->setQuery('memory');

// create filterqueries and add tags
$query->createFilterQuery('maxprice')->addTag('price')->setQuery('price:[1 TO 300]');
$query->createFilterQuery('type')->addTag('type')->setQuery('type:3');
$query->createFilterQuery('store')->addTag('store')->setQuery('storeId:3845');

// get the facetset component
$facetSet = $query->getFacetSet();

// create a facet field instance and set options
// exclude price and type filters from the facets, store filter will be respected
$facetSet->createFacetField('stock')->addExcludes(['price', 'type'])->setField('inStock');

// this executes the query and returns the result
$resultset = $client->select($query);

// display the total number of documents found by solr
echo 'NumFound: '.$resultset->getNumFound();

// display facet counts
echo '<hr/>Facet counts for field "inStock":<br/>';
$facet = $resultset->getFacetSet()->getFacet('stock');
foreach ($facet as $value => $count) {
    echo $value . ' [' . $count . ']<br/>';
}

// show documents using the resultset iterator
foreach ($resultset as $document) {

    echo '<hr/><table>';
    echo '<tr><th>id</th><td>' . $document->id . '</td></tr>';
    echo '<tr><th>name</th><td>' . $document->name . '</td></tr>';
    echo '<tr><th>price</th><td>' . $document->price . '</td></tr>';
    echo '</table>';
}

htmlFooter();

```

**Comment by khashabawy** [comment]
@thomascorthals  thank you , I did that and it worked but only for one filter , when i select from more than one filter it happens again , so what do you suggest ?

**Comment by thomascorthals** [comment]
@khashabawy Does each filter have a unique tag and is each tag added to the excludes? There are three ways of adding excludes:

- `setExcludes(['tag1', 'tag2', 'tag3'])` clears existing excludes and replaces them with the provided list of tags.
- `addExcludes(['tag1', 'tag2', 'tag3'])` adds the provided list tags to the existing excludes.
- `addExclude('tag1')` adds the provided tag to the existing excludes.

Both `add*` methods can be called multiple times on the same facet field to build an exclude list in multiple steps. You can use `getExcludes()` to verify which excludes have been set on the field.

```php
<?php

$facetSet = $query->getFacetSet();
$facetField = $facetSet->createFacetField('stock')->setField('inStock');
$facetField->addExclude(['tag4']);
$facetField->addExcludes(['tag1', 'tag3']);
$facetField->addExclude(['tag2']);

// returns ['tag4', 'tag1', 'tag3', 'tag2']
$facetField->getExcludes();
```

**Comment by ubermichael** [comment]
This is one of the top Google hits for "solr facet filter exclude" but I think the response above is out of date. In Solarium 6.1.1 and possibly before, the correct way to do this seems to be

```<?php

$facetField->getLocalParameters()->addExcludes(['tag1', 'tag3']);
```

**Comment by thomascorthals** [comment]
@ubermichael This has been changed indeed, since Solarium 6.0.

Facets with excludes are now [included in the examples](https://github.com/solariumphp/solarium/blob/master/examples/2.1.5.1.1.2-facet-field-excludes.php). These examples are always up-to-date with the codebase since they are run alongside the unit and integration tests as part of the CI workflow.
