### ISSUE TITLE
Implement JsonSerializable

### ISSUE THREAD

**Issue by mbkv** [solariumphp/solarium#603]
I'm currently working on an internal search API and I noticed that no class implements JsonSerializable, even thought it would be very easy to do so.

For example, for the `Solarium\QueryType\Select\Result\Result` class. If you try to json_encode `$result->getDocuments()`, you're just returned an array of empty objects. But, if you add the following things
```php
class AbstractDocument implements JsonSerializable
{
    public function jsonSerialize()
    {
        return $this->getFields()
    }
}
```

JsonSerializable is PHP >5.4 only. So this can't be backported to 3. But it would be a welcome addition to 4

**Comment by mkalkbrenner** [comment]
As you might have noticed, we started with an older code base. With 4.x we'll modernize it step by step. So your suggestions and even better a PR are welcome.
