### ISSUE TITLE
Generate and upload schema.xml etc.

### ISSUE THREAD

**Issue by Firesphere** [solariumphp/solarium#604]
I am probably looking in the wrong place, but I'd like to use PHP to generate and upload a schema.xml with the solrconfig.xml, stopwords, elevation.xml, synonyms.txt etc. files and activate them in Solr.

Does Solarium support this?

**Comment by mkalkbrenner** [comment]
We do something similar in Drupal's search_api_solr module using solarium. Solarium itself doesn't support the feature out of the box but provides the required basic communication stuff.
But maybe it makes sense to isolate the API for this feature from search_api_solr and to integrate it here.

**Comment by Firesphere** [comment]
Apologies, _very_ late reply as I haven't had time to look in to this closer, but do you have this documented/demoed somewhere @mkalkbrenner ?

I'm not a Drupal user, so I don't know exactly where to look :)

**Comment by mkalkbrenner** [comment]
It's not easy to extract as the generation heavily uses Drupal technology.
https://www.drupal.org/project/search_api_solr

**Comment by mkalkbrenner** [comment]
At least the upload should be implemented in Solarium for Solr Cloud using ZooKeeper and the Collections API.

**Comment by mkalkbrenner** [comment]
If we don't upload entire config sets but single files we could use https://issues.apache.org/jira/browse/SOLR-14907

**Comment by mkalkbrenner** [comment]
Will be solved by #948

**Comment by thomascorthals** [comment]
> Will be solved by #948

@mkalkbrenner Does this mean this issue can be closed?

**Comment by mkalkbrenner** [comment]
Yes, the upload is in place now. "Generating" a schema is out of scope for solarium and must be done by the application that uses solarium.
