### ISSUE TITLE
Multiple dictionaries

### ISSUE THREAD

**Issue by martin-ro** [solariumphp/solarium#606]
Is there any plans to support more then one dictionary for the suggester component?
See example in docs: [Multiple Dictionaries](https://lucene.apache.org/solr/guide/6_6/suggester.html#Suggester-MultipleDictionaries.1)

Cheers

**Comment by mkalkbrenner** [comment]
Multiple dictionaries are already supported. But it's not documented. I created a PR to fix the documentation and added some tests.

**Comment by martin-ro** [comment]
Ah.. didn't saw that. Thanks.
