### ISSUE TITLE
Encoded query string is mismatched

### ISSUE THREAD

**Issue by davpsh** [solariumphp/solarium#609]
### Environment

**PHP**: 7.1.9
**Solarium**: 3.8.1
**Solr**: 6.6.4

**Searching query**: `(+"Product" +"72")`

### Problem description
When I'm trying to search by query `(+"Product" +"72")`, Solr return empty result. After debugging find that the problem in the query encoding:

https://github.com/solariumphp/solarium/blob/c353babec89fdbe8c64054bfec8e77bcb5da6705/library/Solarium/Core/Client/Request.php#L413

According to [documentation](http://php.net/manual/en/function.http-build-query.php): 

> enc_type
By default, PHP_QUERY_RFC1738.

>If enc_type is PHP_QUERY_RFC1738, then encoding is performed per » RFC 1738 and the application/x-www-form-urlencoded media type, **which implies that spaces are encoded as plus (+) signs**

Making a GET request and according to 
https://github.com/solariumphp/solarium/blob/c353babec89fdbe8c64054bfec8e77bcb5da6705/library/Solarium/Core/Client/Adapter/Curl.php#L129
``` php
        if (!isset($options['headers']['Content-Type'])) {
            if($method == Request::METHOD_GET){
                $options['headers']['Content-Type'] = 'application/x-www-form-urlencoded; charset=utf-8';
            } else {
                $options['headers']['Content-Type'] = 'application/xml; charset=utf-8';
            }
        }
```

**Content-Type**  is **application/x-www-form-urlencoded**
That means that all spaces in the query will be replaced by **+**, that will broke the query.

### Examples

Encode with **PHP_QUERY_RFC1738**: `http_build_query(['query' => '(+"Product" +"72")'])`
Result with **PHP_QUERY_RFC1738**: `query=%28%2B%22Product%22+%2B%2272%22%29` (_here **+** is a space_)

Encode with **PHP_QUERY_RFC3986**: `http_build_query(['query' => '(+"Product" +"72")'], NULL, NULL, PHP_QUERY_RFC3986)`
Result with **PHP_QUERY_RFC3986**: `query=%28%2B%22Product%22%20%2B%2272%22%29` (_here **%20** is a space_)

Encoding with **PHP_QUERY_RFC3986** works fine and returned results are valid.

### The question is

Am I doing something wrong or it is a possible bug?

**Comment by mkalkbrenner** [comment]
Why are you still using solarium 3.x?

In 4.x we have some real integration tests that cover this and the issue might be solved already.

**Comment by davpsh** [comment]
@mkalkbrenner Before I've created the issue, I've checked 4.x branch sources and all places (which I described in the issue) are the same as in 3.8.1. I guess, result will be the same but I'll recheck with 4.x. branch, anyway.

**Comment by mkalkbrenner** [comment]
In all the various installations I have access to, using "+" as space is the correct encoding that works. And "%20" doesn't!
How did you install Solr? Are you using the built-in Jetty-Server?

**Comment by mkalkbrenner** [comment]
no feedback
