### ISSUE TITLE
DateTime is not set to UTC when using Extract

### ISSUE THREAD

**Issue by jeroenherczeg** [solariumphp/solarium#618]
When using the update QueryType, it will change the timezone to UTC.
When using the extract QueryType, it will keep **not** change it to UTC.

**Comment by jeroenherczeg** [comment]
Would it be possible to get this fix in v3?

**Comment by mkalkbrenner** [comment]
Sure, if @thePanz agrees and if you file a new PR for that, or at least a new issue.

**Comment by jeroenherczeg** [comment]
I will create a new PR, which branch should it be based of?

**Comment by mkalkbrenner** [comment]
3.x
https://github.com/solariumphp/solarium/tree/3.x
