### ISSUE TITLE
Support managed resources api

### ISSUE THREAD

**Issue by timohund** [solariumphp/solarium#626]
Stopword and Synonyms can be manged with managed resources in Apache Solr. It would be nice to support the API for that in solarium. Some years ago i started that in an own package https://github.com/timohund/solr-rest-api-client and it would be nice to have this functionality in solarium.

I'll try to implement that in the next weeks.

**Comment by jsteggink** [comment]
Hi, I just built this. I'll try if I can create a pull request this week.

**Comment by timohund** [comment]
Sounds good!

**Comment by timohund** [comment]
For synonyms solr allows to create multiple entries, without passing a base word (a group with equal words).

E.g. "iphone", "smartphone", "mobile"

=>
"iphone" => "smartphone", "mobile"
"smartphone" => "iphone", "mobile"
"mobile" => "iphone", "smartphone"

I think i would be cool to support that and maybe "detect" on the api level the groups. To group them in the rendering, or to delete them in one api call. What do you think? If i can help you with testing or whatever just ping me.

**Comment by jsteggink** [comment]
@timohund, sorry, I didn't get to it as I'm on a holiday. I'll do a PR on Monday.

**Comment by jsteggink** [comment]
@timohund I pushed a commit, maybe you can have a look: https://github.com/jsteggink/solarium/tree/issue-626-managed-resources

**Comment by timohund** [comment]
@jsteggink 

Thanks for your work, would be nice to have that in Version 5 of solarium.

By reading the code i have a few questions:

1. For the commands there is a method "addCommand". Is it possible to execute multiple commands or just one at once? When only one is possible i would name it "setCommand", for me "addCommand" sounds like you are able to run multiple commands.
2. What about a GET_COMMAND, i guess this is just missing by now?
3. I think i would be nice to have some integration tests that cover the creation, deletion and retrieval of those entities to make sure that this still works when a newer version of Apache Solr will be used.

Maybe @mkalkbrenner @basdenooijer  and @thePanz can also give some input. By now i think this is really a cool feature and what you did looks great.

**Comment by jsteggink** [comment]
Thanks for the review @timohund!

1. I will change it to setCommand
2. Right now it works by just firing the query without any command. I followed the pattern of other query types where it works like this. All the other commands require an additional parameter, however, GET has no parameters. It just lists all resources.
3. I have made the integration tests, but the schema doesn't have the right filters yet. I'm not adding it yet, because I'm unsure if it affects any other tests as of now. I'll have to check.

After running the integration tests I found some bugs which I've also fixed.

I'll let you know when I have added the commit.

**Comment by jsteggink** [comment]
@timohund  Check the new changes. I've also added integration tests, as the techproducts schema also includes managed resources for stopwords and synonyms.

**Comment by timohund** [comment]
@jsteggink For me it looks good now. Maybe you can open a pull request and @mkalkbrenner @thePanz or @basdenooijer can give some feedback?

In addition to the current implementation if have a feature idea, but this could also be part of a new issue or i can solve that in our client application.

Imagine you have the following words that should be threated as equal synonyms:

"smartphone, mobile, mobilephone".

With managed lists you would need to create three entries:

```
"smartphone" => "smartphone, mobile, mobilephone".
"mobile" => "smartphone, mobile, mobilephone".
"mobilephone" => "smartphone, mobile, mobilephone".
```

Technically Apache Solr could generate these 3 entries just by passing no baseword, or term in your domain model.

From the application perspective it would be nice to group the somehow e.g. to perform a deletion of these multiple autogenerated lines. An approach could be to build a "groupHash" on all involved worlds, which should result in the same hash for all of these three entries:

```
"smartphone" => "smartphone, mobile, mobilephone"
"mobile" => "smartphone, mobile, mobilephone"
"mobilephone" => "smartphone, mobile, mobilephone"
```

But maybe this also goes to far for now. Would be nice to get your and the input from the others on that.

**Comment by jsteggink** [comment]
@timohund, what you describe already works. If you take a look at the tests you'll see how it works. In the command you don't set a term / base word and it will create symmetrical synonyms.

**Comment by timohund** [comment]
@jsteggink yes i saw that. What i mean is when you afterwards want to delete these symmetrical synonyms. Is that possible to perform a deletion without term as well, and all three lines get deleted? As far as i know you then would need to trigger three deletions. And therefore it would be nice to have the possibility to check if a synonym row belongs to the same group like another.

**Comment by timohund** [comment]
@jsteggink What about to open a pull request? I think it would be nice to have that in solarium 5.0.0
