### ISSUE TITLE
Solr 7.4.0 Spellcheck

### ISSUE THREAD

**Issue by samsmooth** [solariumphp/solarium#631]
I'm running solr 7.4.0 & spellcheck example but the code:
$spellcheckResult = $resultset->getSpellcheck();

$spellcheckResult is null! what shall i do?

But localhost:8983/solr/testcore/spell?df=text&spellcheck.q=exampel&spellcheck=true has results as expected.

what is the problem? any incompatibility between solariumphp and newest version of solr?

_There is a closed ticket on this issue already, but without a solution, so I re-post it._

**Comment by mkalkbrenner** [comment]
Did you build the spellcheck catalog?

->setBuild(true)
->setReload(true)

Maybe we need to enhance the documentation.

You don't need to build the catalog on each request, just from time to time or when the index changes.

**Comment by samsmooth** [comment]
I had ->setBuild(true) yes, but without the reload.
Unfortunately adding ->setReload(true) doesn't solve the problem.

**Comment by mkalkbrenner** [comment]
Can you paste the complete code block?

**Comment by samsmooth** [comment]
Sure. Here is the code.

                `// get a select query instance
                $client = $this->solr->createSelect();
                $client->setRows(0);

                // add spellcheck settings
                $spellcheck = $client->getSpellcheck();
                $spellcheck->setQuery($query);

                $spellcheck->setCount(10);
                $spellcheck->setBuild(true);
                $spellcheck->setReload(true);
                $spellcheck->setCollate(true);
                $spellcheck->setExtendedResults(true);
                $spellcheck->setCollateExtendedResults(true);

                // this executes the query and returns the result
                $resultset = $this->solr->select($client);
                $spellcheckResult = $resultset->getSpellcheck();

                dd($resultset);`

And here is the output.

                `Result {#210 ▼
                  #numfound: 575
                  #maxscore: 1.0
                  #nextcursormark: null
                  #documents: []
                  #components: array:1 [▼
                    "spellcheck" => null
                  ]
                  #status: null
                  #queryTime: null
                  #parsed: true
                  #response: Response {#209 ▼
                    #headers: array:1 [▼
                      0 => "HTTP/1.1 200 OK"
                    ]
                    #body: """
                      {\n
                        "response":{"numFound":575,"start":0,"maxScore":1.0,"docs":[]\n
                        }}\n
                      """
                    #statusCode: 200
                    #statusMessage: "OK"
                  }
                  #data: array:1 [▼
                    "response" => array:4 [▼
                      "numFound" => 575
                      "start" => 0
                      "maxScore" => 1.0
                      "docs" => []
                    ]
                  ]
                  #query: Query {#204 ▼
                    #options: array:8 [▼
                      "handler" => "select"
                      "resultclass" => "Solarium\QueryType\Select\Result\Result"
                      "documentclass" => "Solarium\QueryType\Select\Result\Document"
                      "query" => "*:*"
                      "start" => 0
                      "rows" => 0
                      "fields" => "*,score"
                      "omitheader" => true
                    ]
                    #tags: []
                    #fields: array:2 [▼
                      "*" => true
                      "score" => true
                    ]
                    #sorts: []
                    #filterQueries: []
                    #helper: null
                    #params: []
                    #components: array:1 [▼
                      "spellcheck" => Spellcheck {#203 ▼
                        #queryInstance: Query {#204}
                        #options: array:7 [▼
                          "query" => "example"
                          "count" => 10
                          "build" => true
                          "reload" => true
                          "collate" => true
                          "extendedresults" => true
                          "collateextendedresults" => true
                        ]
                        #collateParams: []
                      }
                    ]
                    #componentTypes: array:14 [▼
                      "morelikethis" => "Solarium\Component\MoreLikeThis"
                      "spellcheck" => "Solarium\Component\Spellcheck"
                      "suggest" => "Solarium\Component\Suggester"
                      "debug" => "Solarium\Component\Debug"
                      "spatial" => "Solarium\Component\Spatial"
                      "facetset" => "Solarium\Component\FacetSet"
                      "dismax" => "Solarium\Component\DisMax"
                      "edismax" => "Solarium\Component\EdisMax"
                      "highlighting" => "Solarium\Component\Highlighting\Highlighting"
                      "grouping" => "Solarium\Component\Grouping"
                      "distributedsearch" => "Solarium\Component\DistributedSearch"
                      "stats" => "Solarium\Component\Stats\Stats"
                      "queryelevation" => "Solarium\Component\QueryElevation"
                      "rerankquery" => "Solarium\Component\ReRankQuery"
                    ]
                  }
                }`

**Comment by mkalkbrenner** [comment]
You did not specify a dictionary using setDictionary().

**Comment by samsmooth** [comment]
Thank you, Markus.
I added $spellcheck->setDictionary('suggest'), which doesn't make a change.

**Comment by mkalkbrenner** [comment]
Does it work now?

**Comment by samsmooth** [comment]
No.

**Comment by mkalkbrenner** [comment]
> But localhost:8983/solr/testcore/spell?df=text&spellcheck.q=exampel&spellcheck=true has results as expected.

That uses the `spell`query handler. But does your `select`query handler contain a spellcheck component in your solrconf.xml?

**Comment by mkalkbrenner** [comment]
ok, you check manually using the Solr admin UI if a select with spellcheck causes an Exception to figure out if we have a solarium or Solr issue.

**Comment by samsmooth** [comment]
admin UI generates this URI which works well.

`http://localhost:8983/solr/core/select?q=example&spellcheck=on`

**Comment by mkalkbrenner** [comment]
Can you post the query, solarium creates?

**Comment by samsmooth** [comment]
This is the output from dd($spellcheck);

```
Spellcheck {#203 ▼
  #queryInstance: Query {#204 ▼
    #options: array:8 [▼
      "handler" => "select"
      "resultclass" => "Solarium\QueryType\Select\Result\Result"
      "documentclass" => "Solarium\QueryType\Select\Result\Document"
      "query" => "*:*"
      "start" => 0
      "rows" => 0
      "fields" => "*,score"
      "omitheader" => true
    ]
    #tags: []
    #fields: array:2 [▼
      "*" => true
      "score" => true
    ]
    #sorts: []
    #filterQueries: []
    #helper: null
    #params: []
    #components: array:1 [▼
      "spellcheck" => Spellcheck {#203}
    ]
    #componentTypes: array:14 [▼
      "morelikethis" => "Solarium\Component\MoreLikeThis"
      "spellcheck" => "Solarium\Component\Spellcheck"
      "suggest" => "Solarium\Component\Suggester"
      "debug" => "Solarium\Component\Debug"
      "spatial" => "Solarium\Component\Spatial"
      "facetset" => "Solarium\Component\FacetSet"
      "dismax" => "Solarium\Component\DisMax"
      "edismax" => "Solarium\Component\EdisMax"
      "highlighting" => "Solarium\Component\Highlighting\Highlighting"
      "grouping" => "Solarium\Component\Grouping"
      "distributedsearch" => "Solarium\Component\DistributedSearch"
      "stats" => "Solarium\Component\Stats\Stats"
      "queryelevation" => "Solarium\Component\QueryElevation"
      "rerankquery" => "Solarium\Component\ReRankQuery"
    ]
  }
  #options: array:8 [▼
    "query" => "example"
    "count" => 10
    "build" => true
    "reload" => true
    "collate" => true
    "extendedresults" => true
    "collateextendedresults" => true
    "dictionary" => "name"
  ]
  #collateParams: []
}
```

**Comment by samsmooth** [comment]
It seems to be the dictionary as you explained above. This causes the exception.
What will spellcheck.dictionary in my example be? "spellchecker" isn't working.

`webapp=/solr path=/select params={spellcheck.collateExtendedResults=true&spellcheck.dictionary=spellchecker&json.nl=flat&fl=*,score&start=0&rows=0&spellcheck.build=true&spellcheck.extendedResults=true&q=*:*&spellcheck.q=example&omitHeader=true&spellcheck=true&spellcheck.count=10&spellcheck.reload=true&wt=json&spellcheck.collate=true} status=500 QTime=1`

**Comment by samsmooth** [comment]
So when putting directory to "default", I get suggestions, but it says "correctly spelled".

```
Result {#212 ▼
  #suggestions: array:1 [▼
    0 => Suggestion {#207 ▼
      +"numFound": 1
      +"startOffset": 0
      +"endOffset": 7
      +"originalFrequency": 0
      +"words": array:1 [▼
        0 => array:2 [▼
          "word" => "family"
          "freq" => 2
        ]
      ]
    }
  ]
  #collations: array:1 [▼
    0 => Collation {#211 ▼
      #query: "family"
      #hits: 0
      #corrections: array:1 [▼
        "fammili" => "family"
      ]
    }
  ]
  #correctlySpelled: true
}
```

**Comment by mkalkbrenner** [comment]
OK, do you agree, we don't have a solarium issue here, right?

Anyway, any parameter you don't put into your schema.xml as default value for your query handler needs to be set via solarium. That is the case with the dictionary here. And yes, "default" is the name.

ASFAIK "correctlySpelled" turns to true, if the term occurs at least once in your dictionary. If your dictionary is build from the indexed content, "famili" is somewhere in the data.

And it's a valid use-case to return suggestions even if the term is correctly spelled. That's the base for a "Did you mean" function.

**Comment by samsmooth** [comment]
$spellcheckResult is null when there is no match in the dictionary, if there's a match  ->getCorrectlySpelled is always true, so it won't ever be false in my setup.

I can't tell if this works as it should. Nevertheless I build a workaround for my usecase now, so I'm fine.

Thanks a lot for your quick support, Markus.
