### ISSUE TITLE
Limit "start" to the max int

### ISSUE THREAD

**Issue by sascha-egerer** [solariumphp/solarium#640]
Setting `start` to `2147483648` does throw a `Solarium\Exception\HttpException` as it must be an 32 bit integer.

There are two solutions: Simply use `min($offset, 2147483647)` or throw a more specific exception.

What would you prefer?

**Comment by mkalkbrenner** [comment]
OK, the issue is that PHP uses 64bit integers on a 64bit system.
I searched to Solr's documentation. It seems that they use 32 bit `ìnt`.
But I'm against `min($offset, 2147483647)`because it would hide search results.
So throwing a precise execption would be better.

**Comment by mkalkbrenner** [comment]
We just figured out that using the max int as start or rows parameter might cause memory issues on Solr Cloud if a collection uses shards. Therefore we can't guarantee that no execption will be thrown.
