### ISSUE TITLE
Readthedocs right navbar wraps to next line

### ISSUE THREAD

**Issue by kehh** [solariumphp/solarium#642]
I know it sounds ridiculous, but the right navbar on readthedocs wraps over the top of the content which makes it difficult to read. 

![screenshot from 2018-12-04 12-39-33](https://user-images.githubusercontent.com/12571/49419464-e060f700-f7c1-11e8-9923-e5a0f8d3fb2d.png)

I'm wondering whether there's another readthedocs theme that could be used?

**Comment by ndxsoftware** [comment]
+1 This new theme has rendered what was pretty good documentation nearly unusable.

**Comment by mkalkbrenner** [comment]
Seems like readthedocs internally switched to the default theme:
https://mkdocs.readthedocs.io/en/stable/user-guide/styling-your-docs/#built-in-themes

I just had a look at our account settings but I don't have an idea about how to change that. Anyone who could help?

**Comment by roelofjan-elsinga** [comment]
@mkalkbrenner Not sure how readthedocs works, but perhaps this section helps: https://mkdocs.readthedocs.io/en/stable/user-guide/styling-your-docs/#customizing-a-theme It seems like it's just a few basic lines of CSS
