### ISSUE TITLE
Error: Class 'Solarium\Core\Event\Events' not found in

### ISSUE THREAD

**Issue by rokJencic** [solariumphp/solarium#644]
I installed the Solarium library with composer require solarium/solarium and when I try to use it's classes the autoloader is not picking them up. Even a simple <echo 'Solarium library version: ' . Solarium\Client::VERSION . ' - '; > produces the error -> Error: Class 'Solarium\Client' not found in main() (line 24 of index.php). The funny thing is if I type `Client` Php Storm will suggest the class and if you press tab it will create the use statement at the top with the correct path to the class, go to declaration will open the file. All other namespaces in the project are working correctly except Solarium.

**Comment by timohund** [comment]
Just by reading the code i can not see something unusual here. Are you sure your autoload information is uptodate? Did you try ```composer dump-autoload```?

**Comment by mkalkbrenner** [comment]
Maybe there's an older version of Solarium somewhere in your composer managed setup, maybe in the global space. With 4.x we restructured the directories. I remember a similar issue in the Drupal issue queue.

**Comment by mkalkbrenner** [comment]
no feedback provided
