### ISSUE TITLE
getFacets return docblock is FacetInterface[] but actually returns Solarium\Component\Result\Facet\Field[]

### ISSUE THREAD

**Issue by acha5066** [solariumphp/solarium#656]
The signature of getFacets says it returns FacetInterface[] but the result is actually an array of instances of Solarium\Component\Result\Facet\Field. So the methods that the IDE guesses  do not work. 

```
    /**
     * Get all results.
     *
     * @return FacetInterface[]
     */
    public function getFacets()
    {
        return $this->facets;
    }
```

My code: 

```
$response['facets'] = $result->getFacetSet()->getFacets();
```

**Comment by mkalkbrenner** [comment]
You're right that the return type is not correct. In fact it is an array of various facet results.
One is Solarium\Component\Result\Facet\Field
