### ISSUE TITLE
Facet Result

### ISSUE THREAD

**Issue by elvispdosreis** [solariumphp/solarium#673]
I have difficulty setting up a faceted search with product attributes

for example in the image below the site https://www.comprasparaguai.com.br/ when I search for "HD" or "Notebook" faceted searches changes according to the attributes of the products, and the range of favor tbm if adjust according to the products searched.

The facets searches by brand and department are more useful because I know the data to send to create the research

` $facetSet->createFacetField('`Brand')->setField('brand')->setMinCount(1)->addExclude('inner');`
![image](https://user-images.githubusercontent.com/15267623/57016591-3ca13900-6bf1-11e9-9da9-548f96d90c4b.png)

**Comment by mkalkbrenner** [comment]
Sorry, but I don't get the concrete question from you explanations. So what's the question or bug you're facing?

**Comment by elvispdosreis** [comment]
Not a bug, and a question of how to implement this

> Sorry, but I don't get the concrete question from you explanations. So what's the question or bug you're facing?

Not a bug, and a question of how to implement this

**Comment by mkalkbrenner** [comment]
Without any knowledge about your search index I can't help you.

You should read the Solr documentation and create a prototype that uses plain Solr queries via Solr's user interface or curl on the command line.
If you have questions during this phase you should ask on the Solr mailing list for help.

If you know how to implement your features, you can ask here about how to do it in PHP.
Or even better at https://drupalchat.me/channel/solarium-php
