### ISSUE TITLE
Broken examples : stats

### ISSUE THREAD

**Issue by harikt** [solariumphp/solarium#674]
I was going through the examples and noticed a few broken ones. One of them is below.

```
( ! ) Fatal error: Uncaught TypeError: Return value of Solarium\QueryType\Select\Result\Result::getStats() must be an instance of Solarium\Component\Result\Stats\Result or null, instance of Solarium\Component\Result\Stats\Stats returned in /media/hari/8345a046-99fd-4905-b4e1-813be6128914/projects/app-web/code/vendor/solarium/solarium/src/QueryType/Select/Result/Result.php on line 311
--

1 | 0.0006 | 394608 | {main}( ) | .../2.1.5.10-stats.php:0
2 | 0.5999 | 703296 | Solarium\QueryType\Select\Result\Result->getStats( ) | .../2.1.5.10-stats.php:21

```

http://localhost:8000/2.1.5.10-stats.php

**Comment by harikt** [comment]
http://localhost:8000/2.1.5.9-spellcheck.php

![Screenshot from 2019-05-09 12-27-39](https://user-images.githubusercontent.com/120454/57433336-daca7a00-7255-11e9-81df-b858782b1709.png)

http://localhost:8000/2.1.5.7-grouping-by-query.php

![Screenshot from 2019-05-09 12-28-43](https://user-images.githubusercontent.com/120454/57433413-0c434580-7256-11e9-9abc-bd435cc8bc95.png)

http://localhost:8000/2.1.5.1.4-facet-range.php

![Screenshot from 2019-05-09 12-30-13](https://user-images.githubusercontent.com/120454/57433471-3563d600-7256-11e9-8a1c-d691624b2c33.png)

http://localhost:8000/2.1.5.1.6-facet-interval.php

![Screenshot from 2019-05-09 12-30-36](https://user-images.githubusercontent.com/120454/57433505-44e31f00-7256-11e9-9ca4-c0b1cf36a647.png)

http://localhost:8000/2.1.5.2-morelikethis.php

![Screenshot from 2019-05-09 12-31-10](https://user-images.githubusercontent.com/120454/57433529-59271c00-7256-11e9-805a-50275adc8a49.png)

http://localhost:8000/2.1.5.3-highlighting.php

![Screenshot from 2019-05-09 12-31-48](https://user-images.githubusercontent.com/120454/57433560-6c39ec00-7256-11e9-8e2f-133b1e0e3f00.png)

I have taken a few of the broken ones. Using solr 8.x , solarium 5.1 .

**Comment by mkalkbrenner** [comment]
Thanks for reporting. We had various issues with the docs. Now as they're picked up again correctly by readthedocs we should review and fix them.
