### ISSUE TITLE
Multiple queries on different fields

### ISSUE THREAD

**Issue by Firesphere** [solariumphp/solarium#679]
I can't find any answer before, but I hope this is not a duplicate.

I'd like to achieve something like the following.

I have a Solr index with a `user` field and a `channel` field.

I want users to be able to enter the following search term:
> channel:mychannel user:myuser myquery

How I parse this in to something useful is obviously my problem, but what I would like to be able to do, is do a search with multiple params

Thus something like a search query that makes it a bit like
"channel is mychannel OR user is myuser OR myquery"

I can do this manually, but it seems like it's something that's worth considering. Or am I overlooking something?

**Comment by mkalkbrenner** [comment]
I'm not sure if I got your question.
But the code would be something like that:
```php
$solarium_query->setQuery('channel:%p1% user:%p2% myquery', ['mychannel', 'myuser']);
$solarium_query->addParam('q.op', 'OR');
```

**Comment by Firesphere** [comment]
Hey @mkalkbrenner ,

Thank you! It's a bit like I feared, it would require me somewhat generating the query myself. That's okay, I got that already.

A bit a shame because I was hoping for an API, but you can't have it all :)
