### ISSUE TITLE
SilverStripe integration

### ISSUE THREAD

**Issue by Firesphere** [solariumphp/solarium#680]
Hi team!

I'm working on finalizing most of the core work for a SilverStripe4 integration using Solarium and Solr6+

If you're interested in my work, please send me a message and I'll add you to the repository.

We will be open-sourcing this repository once we feel it's stable enough to be out in the wild :)

**Comment by mkalkbrenner** [comment]
Interesting to hear. Once the code is published we can add a link to the integrations list at https://solarium.readthedocs.io/en/stable/getting-started/

**Comment by Firesphere** [comment]
I'll be in touch once it's all in a state where we are happy with the module and open source it.

**Comment by Firesphere** [comment]
Hi @mkalkbrenner ,

Have a look here: https://github.com/firesphere/silverstripe-solr-search

And, for compatibility with an old Solr integration, there's https://github.com/firesphere/silverstripe-solr-compatibility

Let me know what you think? I've tagged it as 0.5 as it's not used in the wild much, yet. But if you feel like it, you can compare the code to https://github.com/silverstripe/silverstripe-fulltextsearch and see which one makes more sense to use (the "official" module does not use Solarium)

**Comment by mkalkbrenner** [comment]
Interesting. But I can't review it in depth because I'm not familiar with silverstripe. But you can file a PR to get listed in the docs.
