### ISSUE TITLE
Deprecations in solarium with Symfony 4.3.2

### ISSUE THREAD

**Issue by AACars** [solariumphp/solarium#683]
I installed Symfony 4.3.2 and I am using solarium version 5.0.3.
My application started logging the following depreciation:

> User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.

This started happening because Symfony's 4.3.2 components require event-dispatcher 4.3.

Looking at the changelog it appears that in order to use the new version EventDispatcherInterface::dispatch() method the code should be updated to dispatch($event, string $eventName = null), not doing so is deprecated.

It appears that $this->eventDispatcher->dispatch() is called in 18 places in the source code.

The fix to the problem would be to restrict the version of EventDispatcher to 4.3 and swap the order of arguments passed to dispatch().

Example:
```
<         $this->eventDispatcher->dispatch(Events::PRE_CREATE_REQUEST, $event);
---
>         $this->eventDispatcher->dispatch($event, Events::PRE_CREATE_REQUEST);
```

Can you advise if this solution would cause any other issue?
Is this something that can be done in the next minor version?

**Comment by Siembrink** [comment]
There is already a PR for that, see https://github.com/solariumphp/solarium/pull/682 :) Hope it gets merged soon.

**Comment by mkalkbrenner** [comment]
fixed
