### ISSUE TITLE
Rerank query errors on range input.

### ISSUE THREAD

**Issue by acha5066** [solariumphp/solarium#687]
I am using Solarium 4.2.0

When using the rerank query functionality with a range value I get an error message (see below). Range values work with other instances of setQuery (for example on a facetQuery) and I can make the same rerank query successfully in the solr interface. 

### Working range query in solr interface
```
rq={!rerank reRankQuery=$rqq reRankDocs=1000 reRankWeight=3}&rqq=availability:[1 TO *]
```
### Code that causes an error 
```
$rerank = $query->getReRankQuery();
    // Increase weight of any product that has any availability.
    $rerank->setQuery('availability:[1 TO *]');
    $rerank->setWeight(10);
```
### Error message
```
{
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.search.SyntaxError"],
    "msg":"org.apache.solr.search.SyntaxError: Expected identifier at pos 40 str='{!rerank reRankQuery=availability:[1 TO *] reRankWeight=10}'",
    "code":400}}
```

**Comment by acha5066** [comment]
Just an update. I can replicate this error in the solr interface (raw query parameters section) with the following: 

```
rq={!rerank reRankQuery=availability:[1 TO *] reRankDocs=1000 reRankWeight=3}
``` 

Notice in the previous example it uses the extra rqq param but here it does not (and this is exactly the same thing solarium ends up passing.

**Comment by acha5066** [comment]
I have opened a pull request with a fix. #688

**Comment by mkalkbrenner** [comment]
https://lucene.apache.org/solr/guide/6_6/query-re-ranking.html#rerank-query-parser
