### ISSUE TITLE
wrong typehint

### ISSUE THREAD

**Issue by norbert-n** [solariumphp/solarium#691]
If null is a alowed default value then shouldn´t it be "?bool"

https://github.com/solariumphp/solarium/blob/a64b20d4639ac21693771c3200515501aa7efa43/src/Plugin/BufferedAdd/BufferedAdd.php#L261

Now with a simple commit without parameters 
`$buffer->commit();`
I get:
 > Type error: Argument 2 passed to Solarium\Plugin\BufferedAdd\Event\PreCommit::__construct() must be of the type boolean, null given

**Comment by mkalkbrenner** [comment]
you're right
