### ISSUE TITLE
PHP 7.1: Error: Undefined class constant 'ISO8601'

### ISSUE THREAD

**Issue by mkalkbrenner** [solariumphp/solarium#694]
We access the constant like this:
```
\DateTimeInterface::ISO8601
```

But that was a change introduced by PHP 7.2:

7.2.0 | The class constants of DateTime are now defined on DateTimeInterface.

**Comment by itsAkky** [comment]
Hi @mkalkbrenner ,  how to did you fixed this issue cause I'm facing the same issue. could you just please elaborate steps to fix this. thank you in advance.

**Comment by itsAkky** [comment]
Hello for those who is facing same issue and using php version  >= 7.0.33 can fix this by simply changing 

\DateTimeInterface::ISO8601 

to

\DateTime::ISO8601
