### ISSUE TITLE
[Bug] BufferedAdd does not support Symfony event dispatcher

### ISSUE THREAD

**Issue by rms2219** [solariumphp/solarium#697]
The changes made in 5.1.1 to support "Symfony\Contracts\EventDispatcher\Event" cause an exception to be thrown when using the BufferedAdd plugin. The arguments need to be reversed.

**Comment by mkalkbrenner** [comment]
Can you provide more details? Can you post the exception?

**Comment by mkalkbrenner** [comment]
OK, I see. I wonder how we missed these lines?
