### ISSUE TITLE
[Bug] Cannot set multivalued field to empty list

### ISSUE THREAD

**Issue by rms2219** [solariumphp/solarium#698]
Per the Solr documentation, to remove the values of a multivalued field in an atomic update, you can use the "set" modifier with an empty list as the value. Solarium does not allow this. In `RequestBuilder::buildFieldsXml`, if the field value is an empty array, a field will never be added to the XML for it.

**Comment by mkalkbrenner** [comment]
https://cwiki.apache.org/confluence/display/solr/UpdateXmlMessages
https://lucene.apache.org/solr/guide/8_1/updating-parts-of-documents.html

I think we should go for the `null` value:
```xml
<field name="skills" update="set" null="true" />
```
