### ISSUE TITLE
Very weak documentation

### ISSUE THREAD

**Issue by A-H-Pooladvand** [solariumphp/solarium#702]
Please provide better documentation, lack of information, lack of examples, messy sections, some of references that the links does not work this is my first time that I am struggling to figure out how to use a library  for example there is no clear documentation to show how exactly I can set authentication in solr (at least I couldn't find) I appreciate your work on this, I DO but documentation is not really neat.
Best regards

**Comment by RevisionTen** [comment]
Theres a section on how to modify the default requests that are send by the solarium client that even includes authentication headers in the example:
https://solarium.readthedocs.io/en/stable/plugins/#customizerequest-plugin

**Comment by A-H-Pooladvand** [comment]
Yea but my point is something else, I am not that kinda guy who complains a lot but I couldn't fit myself with this package. I am closing this because this repo seams to be inactive by the owner
anyways I ended up building my own query builder for solr
