### ISSUE TITLE
Solr HTTP error: HTTP request failed, Operation timed out after 5000 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by htmax** [solariumphp/solarium#703]
Solr HTTP error: HTTP request failed, Operation timed out after 5000 milliseconds with 0 bytes received
How can I change the timeout?

**Comment by ainzz** [comment]
I would like to know that as well. I see in the adapter class the option for timeout but I don't know where to pass it on initialisation.

**Comment by ryross** [comment]
You can pass 'timeout' as an endpoint option when instantiating `Client`

```
$client = new Client([
'endpoint' => [
   'localhost' => [
      'host' => 'localhost',
      'port' => 8983,
      'path' => '/',
      'collection' => 'yourcollection',
      'timeout' => 30,
      ]
   ]
]);
```

**Comment by mkalkbrenner** [comment]
@ryross that's right :-)

There's also a setter to adjust the value on the fly: `Endpoint::setTimeout()`.
