### ISSUE TITLE
BufferedAdd does not receive the endpoint

### ISSUE THREAD

**Issue by Firesphere** [solariumphp/solarium#706]
The BufferedAdd plugin seems to not properly receive the correct configuration for the core, the core name is always null, despite the configuration on the client is correctly set to have the core name defined.

Am I doing something wrong?

**Comment by wickedOne** [comment]
you need to set it explicitly.

```php
$buffer = $client
    ->getPlugin('bufferedadd)
    ->setEndpoint($client->getEndpoint('mycorename'))
    // ...
;
```

though i understand why you would assume it receives the default core of the current client...

**Comment by Firesphere** [comment]
That might need to be added to the documentation then, because indeed it wasn't clear. Thanks!

**Comment by wickedOne** [comment]
you're welcome.
feel free to make chenges to the documentation and create a pr
