### ISSUE TITLE
How use createJsonFacetTerms() to subfacet?

### ISSUE THREAD

**Issue by zigomario** [solariumphp/solarium#710]
Hello,

How i can use method createJsonFacetTerms() to use subfacet ?

like that for example : json.facet={category:{type:terms,field:category,facet:{label_category:{type:terms,field:label_category,limit:1}}}}

I'm not sur that doc speak about management Json Facet Api..

Thank you to advance

**Comment by CrueLv** [comment]
https://github.com/solariumphp/solarium/issues/776
