### ISSUE TITLE
Pivot Facet Limit does not work

### ISSUE THREAD

**Issue by cseufert** [solariumphp/solarium#713]
I have updated to Solarium 5.1.4 to take advantage of the api for setting limits on Pivot Facet, but it still doesn't work.

I am setting up a PivotFacet & a regular Facet like this:
```
    $facetObs = $facet->createFacetPivot('question-obs');
    $facetObs->addFields(['qcode', 'observation']);
    $facetObs->setLimit(-1);
    $facetObs->setMinCount(0);
  $facet
      ->createFacetField('report')
      ->setField('report')
      ->setMinCount(1)
      ->setLimit(-1);
```
however, it never gets sent to the server, eg:
`2019-10-30 05:56:09.598 INFO  (qtp1330278544-33) [   x:inspect] o.a.s.c.S.Request [inspect]  webapp=/solr path=/select params={f.report.facet.mincount=1&facet.field={!key%3Dreport}report&json.nl=flat&facet.pivot={!key%3Dquestion-obs}qcode,observation&fl=*,score&start=0&rows=10&facet.pivot.mincount=0&q=(inspection:110f2b70eec711e8baa3bc305bf50a50)+AND+(vessel:9294109)+AND+reportdate:+[2019-10-24T00:00:00Z+TO+2019-10-26T23:59:59Z]&omitHeader=true&wt=json&facet=true&f.report.facet.limit=-1} hits=243 status=0 QTime=1`

As a side note, I can't figure out why the parameter is not being sent to the server, I cant see how the facet parameters are turned into query parameters, if you can point me in the right direction, I could possibly fix it.

**Comment by wickedOne** [comment]
fixed @ https://github.com/solariumphp/solarium/pull/732
