### ISSUE TITLE
_nest_path_ unable to update

### ISSUE THREAD

**Issue by szabizs** [solariumphp/solarium#717]
Hi guys,

I'm implementing a nested documents situation and when i'm indexing it trough solarium, it does not work.
If the indexing is done in the solr interface or trough curl, the data is indexed properly.

```
{
	"id": "parent-139",
	"product_id": 139,
	"content_type": "parentDocument",
	"type_s": "parent",
	"matnr": 70220521,
	"_nest_path_": [{
		"id": "child-139-4743-5263",
		"type_s": "child",
		"make": "FIAT",
		"model": "DOBLO Cargo (223_)",
		"fuel_slug": "motor-diesel",
		"engine_name_slug": "1-9-jtd-multijet",
		"engine_codes": "186 A9.000",
		"ktypnr": 5263,
		"kmodnr": 4743
	}, {
		"id": "child-139-2053-8812",
		"type_s": "child",
		"make": "ALFA ROMEO",
		"model": "156 (932_)",
		"fuel_slug": "motor-diesel",
		"engine_name_slug": "1-9-jtd-932b2",
		"engine_codes": "AR 32302",
		"ktypnr": 8812,
		"kmodnr": 2053
	}]
}
```

Here is the document that is created in the createDocument method.
But somehow **_nest_path_**  seems to not work in the process.

![image](https://user-images.githubusercontent.com/5064872/68390763-a1c08300-016e-11ea-95d6-6308263e94a4.png)

After this the query will return nested documents.

![image](https://user-images.githubusercontent.com/5064872/68390642-69b94000-016e-11ea-97df-5540e7170a90.png)

**Comment by mkalkbrenner** [comment]
Solarium itself would create an XML to reflect the nested documents if you work with Document objects. The command as XML should like this:
'''xml
<add>
   <doc>
      <doc>
      </doc>
      <doc>
      </doc>
   </doc>
</add>
'''

Can you share the code you used to create the docs?

**Comment by thomascorthals** [comment]
My previous reply was based solely on Solr 8. Solr 7 doesn't have `NestPathField` field type and `_nest_path_` doesn't have any special meaning there. You could use it for labelled children in Solr 7, but I would advise against it if you don't want surprises when upgrading to Solr 8.

Since #872 it is possible to add labelled children through Solarium. That fixes your issue, regardless of the label you end up using.
