### ISSUE TITLE
Deprecation warning in PHP 7.4

### ISSUE THREAD

**Issue by Mechstud** [solariumphp/solarium#720]
After upgrading to PHP 7.4, we are receiving the following deprecated warning.

> implode(): Passing glue string after array is deprecated. Swap the parameters in ../vendor/solarium/solarium/library/Solarium/Core/Query/AbstractRequestBuilder.php

This warning causes a ReactJS page to fail completely, as it requires the response to be clean.

**Comment by Mechstud** [comment]
On a global search, deprecated usage of implode function is found in two files:

[Line no. 346 in /src/Core/Query/Helper.php](https://github.com/solariumphp/solarium/blob/master/src/Core/Query/Helper.php#L346)

[Line no. 71 in /src/Core/Query/AbstractRequestBuilder.php](https://github.com/solariumphp/solarium/blob/master/src/Core/Query/AbstractRequestBuilder.php#L71)

I have clone the repo; fixed the code, and trying to commit, but getting the following error:

> remote: Permission to solariumphp/solarium.git denied to Mechstud.
> fatal: unable to access 'https://github.com/solariumphp/solarium.git/': The requested URL returned error: 403

**Comment by ejunker** [comment]
@Mechstud you need to create a pull request and then the maintainer can merge it

**Comment by Mechstud** [comment]
@ejunker Thanks for the response. I know about the PR procedure; the issue is I am trying to push the code to origin. I have created a separated branch out of master and made changes to the code. Now after commiting locally, when I try to push the code to remote (origin), I am getting the above-mentioned error. It seems that permission is required to be able to push to this repository.

**Comment by ejunker** [comment]
@Mechstud you can fork this repo which will create Mechstud/solarium which is under your control. Clone your fork, make the change, push to your fork, then create a PR against solariumphp/solarium

**Comment by ejunker** [comment]
@Mechstud I created a PR for this at #722
