### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by mateuszkib** [solariumphp/solarium#741]
Hello I have a problem with my solr. I get PHP Fatal Error in console on server.

PHP Fatal error:  Uncaught Solarium\Exception\HttpException: Solr HTTP error: HTTP request failed, Connection timed out after 5001 milliseconds in /solarium/solarium/library/Solarium/Core/Client/Adapter/Curl.php:195
--

Where is the problem ?

**Comment by wickedOne** [comment]
this means the timeout for your endpoint has been reached so you might want to increase the value passed to this option:
https://github.com/solariumphp/solarium/blob/942fdf81ea0743420af77ce48aee79964217abc1/src/Core/Client/Endpoint.php#L198-L202

the reason why the timeout has been reached might depend on you solr configuration or on the complexity of your query. perhaps try the [debug](https://solarium.readthedocs.io/en/stable/queries/select-query/building-a-select-query/components/debug-component/) component to pinpoint the curlpit

**Comment by mkalkbrenner** [comment]
You should take a look at your Solr log files, too.
It rather seems to be a Solr issue or an issue with your query instead of an issue in the solarium library.
