### ISSUE TITLE
How use createJsonFacetQuery() to subfacet?

### ISSUE THREAD

**Issue by CrueLv** [solariumphp/solarium#776]
How i can use method createJsonFacetQuery() to use subfacet ?

like that for example : json.facet={ trust_by_city: { type: terms, field: bs_field_trust, limit: 5, facet: { cities: { type: terms, field: its_field_unloading_city } } } }

I'm not sur that doc speak about management Json Facet Api..

Thank you to advance

**Comment by mkalkbrenner** [comment]
Here's a complex example of sub facets / nested facets:
https://git.drupalcode.org/project/search_api_solr/-/blob/8.x-3.x/src/Plugin/search_api/backend/SearchApiSolrBackend.php#L4514

Feel free to contribute a better documentation!

**Comment by CrueLv** [comment]
Thanks a lot, it works!!!
