### ISSUE TITLE
Solr connection problem

### ISSUE THREAD

**Issue by serkankazanci** [solariumphp/solarium#779]
Hi,

I have designed a search engine three years ago using Solr's velocity templates. I want to re-write the search engine with more functionality and came across solarium.

Downloaded the git, read documents, tried some tests. However i am not able to connect to Solr as shown in documents regarding the examples directory.

I get a 
"Uncaught TypeError: Argument 1 passed to Solarium\Core\Client\Client::__construct() must be an instance of Solarium\Core\Client\Adapter\AdapterInterface, array given, called in test.php on line 10 and defined in /src/Core/Client/Client.php:275 Stack trace: #0 /examples/test.php(10): Solarium\Core\Client\Client->__construct(Array) #1 {main} thrown in /src/Core/Client/Client.php on line 275 " error 
when i write the code "$client = new Solarium\Client($config);"

I am not sure if this is due to an out-dated documentation or my lack of programming skills.

How can i setup a connection to Solr for further transactions?

**Comment by wickedOne** [comment]
hi there,

we recently changed the constructor signature of the solarium client as can be seen over here:
https://github.com/solariumphp/solarium/blob/500018020f7dc34f29cfc474ca0432ae22772640/src/Core/Client/Client.php#L275

unfortunately not all the docs are updated yet / reflecting these changes.

in order to get you started, you might want to try the following to instantiate a solrarium client
```php
<?php

use Solarium\Client;
use Solarium\Core\Client\Adapter\Curl;
use Symfony\Component\EventDispatcher\EventDispatcher; 

class Foo
{
    $adapter = new Curl();
    $dispatcher = new EventDispatcher();
    $options = [
        // your options here
    ];

    $client = new Client($adapter, $dispatcher, $options);
}
```

**Comment by dmaicher** [comment]
@serkankazanci which version are you using? Seems you are using the master branch? So an unreleased version.

With the latest stable release `5.2.0` you should not get those errors

**Comment by dmaicher** [comment]
@serkankazanci any more feedback or can we close this? :blush:

**Comment by mkalkbrenner** [comment]
no further feedback

**Comment by RanchCoder** [comment]
> @serkankazanci which version are you using? Seems you are using the master branch? So an unreleased version.
> 
> With the latest stable release `5.2.0` you should not get those errors

I am using version 6.0.4

**Comment by Raghav9888** [comment]
**Thats my error** => 
App\DataCollector\GitDataCollector::__construct(): Argument #1 ($gitLoader) must be of type App\BranchLoader\GitLoader, array given, called in D:\wamp\www\Symfony\app.hotel.local\var\cache\dev\Container0U2iFrE\App_KernelDevDebugContainer.php on line 1097



**Thats my  service.yml** => 

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:

    App\DataCollector\GitDataCollector:
        tags:
              name: data_collector
              template: 'git/data_collector/git_data.html.twig'
                # must match the value returned by the getName() method
              id: 'app.git_data_collector'
        public: false

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            App\BranchLoader\GitLoader:
                arguments:
                  [ '%kernel.project_dir%' ]
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

**Thats my   dataCollector** =>  

<?php


namespace App\DataCollector;


use App\BranchLoader\GitLoader;
use Exception;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\DataCollector\DataCollector;

class GitDataCollector extends DataCollector
{
    private $gitLoader;

    public function __construct(GitLoader $gitLoader)
    {
        $this->gitLoader = $gitLoader;
    }

    public function collect(Request $request, Response $response,Exception|\Throwable $exception = null)
    {
        // We add the git informations in $data[]
        $this->data = [
            'git_branch' => $this->gitLoader->getBranchName(),
            'last_commit_message' => $this->gitLoader->getLastCommitMessage(),
            'logs' => $this->gitLoader->getLastCommitDetail(),
        ];
    }

    // we will use this name in the config later
    public function getName()
    {
        return 'app.git_data_collector';
    }

    public function reset()
    {
        $this->data = array();
    }
    //Some helpers to access more easily to infos in the template
    public function getGitBranch()
    {
        return $this->data['git_branch'];
    }

    public function getLastCommitMessage()
    {
        return $this->data['last_commit_message'];
    }

    public function getLastCommitAuthor()
    {
        return $this->data['logs']['author'];
    }

    public function getLastCommitDate()
    {
        return $this->data['logs']['date'];
    }
}


How to fix please tell
 me
