### ISSUE TITLE
move to symfony contracts event dispatcher interface?

### ISSUE THREAD

**Issue by wickedOne** [solariumphp/solarium#783]
https://github.com/solariumphp/solarium/blob/beb674e36b461fc8824ce4f1e1bca2c8d6e5297c/src/Core/Client/Client.php#L62

are we ok with moving to the symfony contracts version of the event dispatcher interface?

**Comment by dmaicher** [comment]
Yes seems good to me :+1: We only call the `dispatch` method :blush:

**Comment by mkalkbrenner** [comment]
go for it!
