### ISSUE TITLE
Make api endpoint configurable

### ISSUE THREAD

**Issue by EmanuelOster** [solariumphp/solarium#787]
From Solarium v5 on, the api endpoints for v1 and v2 are hardcoded into the Endpoint class.
While this is fine for *most* cases, it breaks our setup. Please make those endpoints configurable so that we can eg. change `/solr` to `/solr-4`

**Comment by mkalkbrenner** [comment]
I think that the hardcoded value is correct for any Solr version that supports the v2 API.
As you can see in the CHANGELOG we dropped support for Solr versions before 6 with solarium 4.x

Can you point me to the corresponding part in Solr's documentation where it is described how to "rename" that endpoint?

If it is possible we should for sure reflect that in solarium.

**Comment by EmanuelOster** [comment]
You are right. this isn't configurable. Apparently our proxy was configured in such a way that it directly points to the v1 API. Since this is probably an unsupported setup I think we can close this issue.

**Comment by mkalkbrenner** [comment]
You're welcome

**Comment by thomascorthals** [comment]
Since [Solarium 6.2.1](https://github.com/solariumphp/solarium/releases/tag/6.2.1), this can be done by adding a `context` to the endpoint configuration. It will default to `solr` if omitted.

```php
$config = [
    'endpoint' => [
        'localhost' => [
            'scheme' => 'http', # or https
            'host' => '127.0.0.1',
            'port' => 8983,
            'path' => '/',
            'context' => 'solr-4',
            'core' => 'techproducts', # or collection
        ]
    ]
];
```
