### ISSUE TITLE
EventDispatcher for solarium 6?

### ISSUE THREAD

**Issue by mkalkbrenner** [solariumphp/solarium#800]
We recently merged #786 

But I'm still not happy with the current state a consider this the last blocker for a 6.0.0-alpha.1 release.

solarium is a library that is used by various frameworks. And event dispatching became more and more common in these framework based on https://www.php-fig.org/psr/psr-14/

So my feeling is that we should rather use `Psr\EventDispatcher\EventDispatcherInterface` then `Symfony\Contracts\EventDispatcher\EventDispatcherInterface` which inherits the first one.

But there's a remaining issue. Both interfaces don't define a way to add an event listener.

The only downside I see is that `Psr\EventDispatcher\EventDispatcherInterface` doesn't define a way to add an event listener.
I think that this is caused by the fact that every framework does that in a different way, for example in code or configuration files.

From my point of view it would be nice to remove the hard dependency to the symfony event dispatcher entirely. The only problems are the current implementations of our own plugins. We require the symfony event dispatcher in the initPlugin implementations.

I would prefer to have our plugins (event listeners) to be compatible to any event dispatcher.

So I suggest to refactor the initPlugin methods to check if the event dispatcher implements  symfony's EventDispatcherInterface. If it does, we call the addListener as we do now.
If not we do nothing and leave the task to the developer. For sure we need to explain that in the docs.

@wickedOne
@thomascorthals
@jsteggink
@thePanz
@timohund
@localheinz
@dmaicher
What is your opinion?

**Comment by mkalkbrenner** [comment]
@wickedOne
@thomascorthals
@jsteggink
@thePanz
@timohund
@localheinz
@dmaicher
I created a first draft with #801
I think a review would be required for such a change.

**Comment by mkalkbrenner** [comment]
I just merged my own PR without a review. Normally I would wait for a review, but I want to get this tested quickly by the Drupal 8 an 9 integration tests. That will give us insights.
If major concerns araise, we can roll-back the commit.

**Comment by mkalkbrenner** [comment]
WIth the current state in master solarium now seems to become usable with Drupal 8 (symfony 3.4) and Drupal 9 (symfony 4.4) and their event dispatchers :-)

In fact it required an additional commit:
https://github.com/solariumphp/solarium/commit/45e39029754d5cc4ef7aec920089f39347e60b75

But I still have to deal with some errors.

**Comment by wickedOne** [comment]
i'm 100% in favour of this modification and your changes look ok to me.

ideally we rethink the way that we listen to our own events in the ``initPluginType`` alltogether.
 
that would not only fix the issue that there's no standardised way of adding listeners like you outlined already, but also the the fact that, for example, the ``CustomizeRequest`` and ``PostBigRequest`` plugins do not play nice together (as described in https://github.com/solariumphp/solarium/issues/755 and https://github.com/solariumphp/solarium/pull/756) which would require not only a standardised way of adding a listener / subscriber but also assigning a priority to those.

however i currently don't have a clear idea of how to achieve that without losing the decoupled nature of the plugin system or writing our own implementation of an event dispatcher...

**Comment by mkalkbrenner** [comment]
Thanks to that change I got our plugins to work with Drupal 8 and 9 event dispatching out of the box now. The massive integration tests there use the BigPostRequest and the Customization events.
So I feel pretty confident that the new implementation works and lowers the barrier for other frameworks to use solarium.
