### ISSUE TITLE
could not set options in curl adapter via constructor

### ISSUE THREAD

**Issue by dalpras** [solariumphp/solarium#808]
$adapter = new \Solarium\Core\Client\Adapter\Curl(['timeout' => 300]);

not working as expected.
You still need to set it as 

$adapter->setTimeout(300);

Bye

**Comment by mkalkbrenner** [comment]
You're right. Timeout has been removed from the options for solarium 6 as it has to be handled differently for each adapter. The constructor option has been deprecated in 5.2.
See
#767
#770
#773
#777

**Comment by mkalkbrenner** [comment]
We expected that people update to 5.2 before they use 6 to be warned.
