### ISSUE TITLE
Default "solr/" in Endpoint base URI

### ISSUE THREAD

**Issue by ehochedez** [solariumphp/solarium#815]
\Solarium\Core\Client\Endpoint base URI now adds "solr/" hardcoded and does not offer any way to overwrite this default value. 
Shouldn't there be a way to be able to change this value in the config ?
We're still using /solr4/collection URLs styles and don't know how to update our code to operate with newer versions of Solarium.

**Comment by mkalkbrenner** [comment]
The herdcoded value is correct. See #787.

**Comment by thomascorthals** [comment]
Since [Solarium 6.2.1](https://github.com/solariumphp/solarium/releases/tag/6.2.1), this can be done by adding a `context` to the endpoint configuration. It will default to `solr` if omitted.

```php
$config = [
    'endpoint' => [
        'localhost' => [
            'scheme' => 'http', # or https
            'host' => '127.0.0.1',
            'port' => 8983,
            'path' => '/',
            'context' => 'solr4',
            'collection' => 'collection',
        ]
    ]
];
```
