### ISSUE TITLE
Getting a single managed stopword/synonym

### ISSUE THREAD

**Issue by thomascorthals** [solariumphp/solarium#830]
We're currently doing this
```php
$query = $client->createManagedSynonyms();
$query->setName('english');
$result = $client->execute($query);
```
to get the result for
```bash
curl "http://localhost:8983/solr/techproducts/schema/analysis/synonyms/english"
```

I'm looking to implement support for getting a single synonym mapping (or stopword) as in
```bash
curl "http://localhost:8983/solr/techproducts/schema/analysis/synonyms/english/happy"
```

There are two ways I can go about this.

1. Set a term on the query.
```php
$query = $client->createManagedSynonyms();
$query->setName('english');
$query->setTerm('happy');
```

Pro: this is the simplest way of setting a term from a user's point of view.
Con: the result would be of a different type with or without the term set on the query.

2. Add a `Get` action.
```php
$query = $client->createManagedSynonyms();
$query->setName('english');
$get = new Get();
$get->setTerm('happy');
$query->setCommand($get);
```

Pro: one type of result for one type of command.
Con: depending on what you want to `GET` (as an HTTP verb), you do or don't need to set a command.

I think a separate `Get` command is the best choice. Unless there's a good reason I'm missing to go with the first option?

I'm also wondering what to do when the term doesn't exist as a synonym/stopword. Solr will respond with a 404. Throwing a `RuntimeException` isn't really wrong but might be a bit harsh.

There's also the `Exists` command. You have to check the status code against 200 or 404 to know if the term exists. The implementation is based on this info from the [ref guide](https://lucene.apache.org/solr/guide/8_5/managed-resources.html):
> You can test to see if a specific word exists by sending a GET request for that word as a child resource of the set, such as:
> ```bash
> curl "http://localhost:8983/solr/techproducts/schema/analysis/stopwords/english/foo"
> ```
> This request will return a status code of 200 if the child resource (foo) exists or 404 if it does not exist the managed list. 

It happens to also return the data I want from `Get`. But you can't tell an end user to use `Exists` to "get" something and parse it yourself. In fact, as a library user I would expect to get a boolean reply to the question if something exists.

Any thoughts and suggestions are appreciated. I want to implement this first and then use it in the integration test for #742.

**Comment by mkalkbrenner** [comment]
The error handling is still influenced from the early days when 404 meant that the Solr web application could not be found.
We should destinguish between the use-cases as nowadays with REST APIs 404 could simply be valid return code if you ask for existence of something. So no exception must be thrown in this case.

Regarding the code I prefer 1. it is much more intuitive. We should focus on streamlining the results.

**Comment by thomascorthals** [comment]
We could always return a `SynonymMappings` or `WordSet`, even if Solr doesn't return the same format if a term is set. It could have either 1 or 0 elements in that case. That's basically what jQuery does for `$('#someId')` vs. `document.getElementById('someId')` that would return `null` if it doesn't exist.

Pro: the result is always of the same type and you can iterate over it even if the term doesn't exist. A simple `count` can tell you if it exists.
Con: methods like `getInitializedOn()` are meaningless if a term is set because Solr doesn't return that information then.

**Comment by mkalkbrenner** [comment]
Sounds good to me.
