### ISSUE TITLE
Solr Authentication

### ISSUE THREAD

**Issue by Firesphere** [solariumphp/solarium#831]
With Solr now fully supporting several different types of authentication, it would be good to document how to set-up authentication for Solarium

**Comment by mkalkbrenner** [comment]
Feel free to do it ;-)

**Comment by Firesphere** [comment]
Heh, although I would agree, I've not fully figured it out yet, hence the issue instead of a PR :D

**Comment by wickedOne** [comment]
by looking at the code, it looks like solarium currently only supports basic auth by adding a ``Authorization`` header in the request (have a look in the ``\Solarium\Core\Client\Adapter`` namespace).

kerebos, hadoop & jwt security plugins do not have a solarium implementation.

**Comment by mkalkbrenner** [comment]
#948 introduced the usage of security.json in our tests. This one uses basic authentication.

**Comment by mkalkbrenner** [comment]
I started experimenting with JWT and token based authentication in general.

**Comment by mkalkbrenner** [comment]
I close this issue as authorization tokens are now supported.

If there's really a need for more authentications methods, open dedicated issues.

**Comment by Firesphere** [comment]
Cheers @mkalkbrenner
