### ISSUE TITLE
Helper::formatDate

### ISSUE THREAD

**Issue by wickedOne** [solariumphp/solarium#840]
https://github.com/solariumphp/solarium/blob/fe70c088f69c3b4fff35b8b5797e4be028af7044/src/Core/Query/Helper.php#L143

setting the timezone on an existing date time object, modifies the date time value when the original timezone differs:
https://3v4l.org/QPVOb

this will lead to unexpected results on each system not having UTC as the default timezone.
is this intended behaviour or a bug?

wouldn't it make more sense to simply use? 
```php
$dt->format('Y-m-d\TH:i:s\Z')
```

**Comment by mkalkbrenner** [comment]
From my point of view the "change" is the intended behaviour.
https://lucene.apache.org/solr/guide/8_5/working-with-dates.html

Internally all dates are stored as UTC. When the PHP code uses a different time zone, the conversion is correct.
But it is also important that you specify the TZ parameter when doing "date math" afterwards at query time.

But I see that this needs to be documented.

**Comment by mkalkbrenner** [comment]
https://www.drupal.org/project/search_api_solr/issues/3064173

**Comment by wickedOne** [comment]
i'm aware solr doesn't use timezones and only accepts the utc tz formatted value as a valid one.

but while adding a document to the solr index, we don't do any checks nor modifications on date time fields so when leveraging this helper function in for instance the query builder, it certainly feels both are out of sync.

shouldn't we at the very least deprecate the method in favour of a ``modifyAndFormatDate`` helper function?

**Comment by mkalkbrenner** [comment]
I agree that it is possible to get "out of sync".

But if you always use the function as it is, it should work perfectly well, if you set-up your PHP environment correctly:

- the date gets "converted" to UTC correctly at index time
- the date gets "converted" to UTC correctly at query time

But if you do "Date Math" like "minus one day", you have to ensure that the TZ parameter is correctly set.

So Solr is able to correctly handle time zones! But all dates are stored as UTC which makes sense. And that's exactly how the current solarium code behaves.

Nevertheless we have to improve our documentation in general and to emphasize that the function has to be used in update queries, too!

**Comment by mkalkbrenner** [comment]
But I agree that we might rename the function and add another.

**Comment by wickedOne** [comment]
agreed. 

the end user is the one responsible for dates to be handled correctly upon index and query time while it's the responsibility of solarium to have clear method naming and documentation so the end user is able to chose the method appropriate for their workflow.

i'll try and modify my pr for this accordingly.

**Comment by wickedOne** [comment]
my proposal: https://github.com/solariumphp/solarium/pull/841/commits/d5d4b9ea67fc1c44165ce3e32d6b5d92ba8c10bb
