### ISSUE TITLE
Atomic updates

### ISSUE THREAD

**Issue by jayadevanm** [solariumphp/solarium#851]
I am trying to update just 2 attributes of an existing document based on an ID attribute.    
`$data = array("ID" => "5ecded8fb36e167ceb3ed3b2", "salesRank" => 37, "min_srp" => 100);    

        if (
            array_key_exists("ID", $data)) {
            $client = $this->client;
            try {
                $update = $client->createUpdate();
                $doc = $update->createDocument();
                $doc->setKey('ID', $data['ID']);
                foreach ($data as $key => $item) {
                    if ($key != 'ID') {
                        $doc->setField($key, $item);
                        $doc->setFieldModifier($key, $doc::MODIFIER_SET);
                    }}
                    $update->addDocuments([$doc]);
                    $update->addCommit();
                    $result = $client->update($update);
` Each time I execute this program, a new document with data like     
`{
        "ID":"5ecded8fb36e167ceb3ed3b2",
        "min_srp":100.0,
        "salesRank":37,
        "_id":"e17508c2-d145-4229-b9e6-27e41e1986aa",
        "_version_":1674066906151124992,
        "solrtimestamp":"2020-08-04T04:16:52.070Z"}`     
gets created. The original document with about 20 attributes stays as it is. How do I fix this? Solarium version is 5.1.3

**Comment by jayadevanm** [comment]
I tried replacing "ID" with "_id" and it worked, I am not sure what that means - do I have to make "ID" unique for the update to work?

**Comment by thomascorthals** [comment]
It means `_id` rather than `ID` is the unique key that Solr uses to identify your documents. You will find this line in `schema.xml`:
```xml
<uniqueKey>_id</uniqueKey>
```

It also means that you have an `updateRequestProcessorChain` set up in `solrconfig.xml` that will generate the unique key for `_id` automatically if it is missing from an update request. It should look like this:
```xml
<updateRequestProcessorChain>
	<processor class="solr.UUIDUpdateProcessorFactory">
		<str name="fieldName">_id</str>
	</processor>
	<processor class="solr.LogUpdateProcessoryFactory" />
	<processor class="solr.RunUpdateProcessorFactory" />
</updateRequestProcessorChain>
```

**Comment by jayadevanm** [comment]
Indeed. I have _id as the unique key. I am new to Solr. I thought the update would work in fashion similar to how it does in a Relational Database, where one can update with a WHERE clause on any column. Is there a way to do that? We have the _id set to the same value as ID, so updating using _id works. Just curious to know.

**Comment by thomascorthals** [comment]
You can't, for the same reason you can't [update multiple documents in one query](https://lucene.472066.n3.nabble.com/Update-multiple-documents-in-one-query-td4070337.html). Atomic updates need the unique key to identify the document to update.
