### ISSUE TITLE
Missing proxy-Support for Http-Adapter

### ISSUE THREAD

**Issue by Radon8472** [solariumphp/solarium#861]
I noticed that the [Http-Adapter] currently has no proxy support.

This adapter should get proxy implementation similar like it is done for Curl-Adapter.

This can be done by adding this code at [Http-Adapter Line 74]
From: 
```php
        $context = stream_context_create(
            ['http' => [
                    'method' => $method,
                    'timeout' => $this->timeout,
                    'protocol_version' => 1.0,
                    'user_agent' => 'Solarium Http Adapter',
                ],
            ]
        );
```
to
```php
       $http_options = [
              'method' => $method,
              'timeout' => $this->timeout,
              'protocol_version' => 1.0,
              'user_agent' => 'Solarium Http Adapter',
        ];
        if (null !== ($proxy = $this->getOption('proxy'))) {
            $http_options['proxy'] = 'tcp://'.$proxy;
            $http_options['request_fulluri']=>true;
        }
        $context = stream_context_create(['http' =>$http_options]);
```

An example for this change you can see at https://www.php.net/manual/de/function.stream-context-create.php#111032

[Http-Adapter Line 74]: https://github.com/solariumphp/solarium/blob/0e9219daae06fe1da2d2147e23c12a29b46738ec/src/Core/Client/Adapter/Http.php#L74
[Http-Adapter]: https://github.com/solariumphp/solarium/blob/master/src/Core/Client/Adapter/Http.php

**Comment by mkalkbrenner** [comment]
Can you open a corresponding PR?

**Comment by Radon8472** [comment]
> 
> 
> Can you open a corresponding PR?

I think I can do that over the weekend, to have some time to test it.
Maybe adding proxy auth to the options would be usefull too 🤔

**Comment by mkalkbrenner** [comment]
> Maybe adding proxy auth to the options would be usefull too 🤔
I think so, yes.

> I think I can do that over the weekend, to have some time to test it.
That would be great.
BTW in our github actions based test environment we can use docker containers. So it should be doable to start any proxy as container to perform some real integration tests.

**Comment by Radon8472** [comment]
> BTW in our github actions based test environment we can use docker containers. So it should be doable to start any proxy as container to perform some real integration tests.

I agree that this would be nice, but we would ne an always reachable public proxy for this.
I could add any free proxy, but mostly they are not very trustworthy

**Comment by mkalkbrenner** [comment]
The actions are debian based. We could also do a simple `sudo apt-get install tinyproxy` or `sudo apt-get install pound` and add a config file under tests/Integration/Fixtures/ to defacto do a simple "port forwarding" with that proxy on localhost.

**Comment by Radon8472** [comment]
@mkalkbrenner 

I addes a Pull request.
I tried to write a test, but I have no experience using phpunit.
And in the current tests I found only examples where mock requests are created. And for testing a proxy mock requests are useless.

I could imagine some tests like this (Psedo-code)
```php
$result = $client->do_a_request();

$client->getAdapter()->setOption('proxy'=>'127.0.0.1:8080');
$proxyresult = $client->do_a_request();

$this->assertSame($proxyresult, $result);
```
