### ISSUE TITLE
Solr 8.6 causes Error 500 java.lang.NoClassDefFoundError: org/eclipse/jetty/server/MultiParts on PDF extraction

### ISSUE THREAD

**Issue by mkalkbrenner** [solariumphp/solarium#864]
Some of our tests fail with the latest Solr 8 release.

The same happens in https://github.com/mkalkbrenner/search_api_solr/actions

**Comment by mkalkbrenner** [comment]
https://www.mail-archive.com/solr-user@lucene.apache.org/msg152182.html

**Comment by mkalkbrenner** [comment]
If you're affected by this issue, it might help if you vote on
https://issues.apache.org/jira/browse/SOLR-14768

**Comment by thomascorthals** [comment]
[SOLR-14768](https://issues.apache.org/jira/browse/SOLR-14768) will be fixed in Solr 8.7.

**Comment by mkalkbrenner** [comment]
Solr 8.6.3 is released but unfortunately the data structure of the extraction result changed.
