### ISSUE TITLE
Error on documentation page

### ISSUE THREAD

**Issue by ChristopheCaron** [solariumphp/solarium#868]
HI,

In this page :
https://solarium.readthedocs.io/en/latest/queries/select-query/building-a-select-query/components/facetset-component/facet-range/

the line $facet->setEnd('NOW/YEAR')); have a  double ")" next YEAR' , the correct version are
$facet->setEnd('NOW/YEAR');

Thanks for your documentation.

**Comment by mkalkbrenner** [comment]
fixed, thanks!
