### ISSUE TITLE
Facet results when query contains field

### ISSUE THREAD

**Issue by olahflorin** [solariumphp/solarium#871]
Hello!

I had an older version of solarium installed and this type of code was working:

`
$facets = $query->getFacetSet();
$facets->createFacetField(array('field'=>'degree', 'exclude'=>'degree')); 
`

That facet returned the all options for "degree" even if the main query had a filter for “degree”.

In the new version i cannot find any way to add an exclude to the createFacetField, all works good but as soon as i have “degree” in the main query, the facet only return that option.

The current facet code:
`        
$facetSet->createFacetField('degree')->setField('degree')->setMethod(\Solarium\Component\Facet\Field::METHOD_FC);
`

I’m sorry if I missed it, but I searched the docs and codebase but could not find an answer

**Comment by thomascorthals** [comment]
`addExclude('degree')` should do the trick. If you want to exclude multiple filters, you can use the plural `addExcludes(['degree','grade'])`.
```php
$facetSet->createFacetField('degree')->addExclude('degree')->setField('degree')->setMethod(\Solarium\Component\Facet\Field::METHOD_FC);
```

**Comment by thomascorthals** [comment]
This still trips me up as well. The changelog is rather cryptic. It is related to this line about what was removed in 6.0.0-alpha.1.

https://github.com/solariumphp/solarium/blob/4bdd5aa674641a0751ba7a5846c5b9e31f5c70c9/CHANGELOG.md#L87

This will do the trick:

```php
$facetSet->createFacetField('degree')->setField('degree')->setMethod(\Solarium\Component\Facet\Field::METHOD_FC)->getLocalParameters()->addExcludes(['degree']);
```

**Comment by olahflorin** [comment]
Hello!

I just tried it with getLocalParameters()->addExcludes(['degree']); but it does not work. No error, it just acts as if it is not present.

I will investigate more now that i found out how these parameters are passed along.

**Comment by thomascorthals** [comment]
Did you add a tag to your filter query? You can't exclude "a field" from the facet results, it has to be a tagged filter. A tag has to be set explicitly, it is not the same as the key you used to create the filter.

```php
$query->createFilterQuery('degree')->setQuery('degree:42')->addTag('degree');
```
The first `'degree'` is the key and does nothing for excluding facets. The second `'degree'` is the tag you need. I'll often use the same string for simple filters, but they can be different too.

**Comment by olahflorin** [comment]
Indeed that was the problem! I knew about the tagging, i was just using the old code that was only partially working, it was filtering the results but not setting the tag(as in my edit above), rewrote all filterQuerys and working good!
