### ISSUE TITLE
[BUG] print_r() expects parameter 2 to be bool, int given

### ISSUE THREAD

**Issue by dkd-kaehm** [solariumphp/solarium#878]
**Solarium version(s) affected**: all with `print_r()` usage
**Solr version**: not relevant

**Description**  
PHP throws exception

**How to reproduce**  
Execute the code with `print_r('some output', 1)` usages.

**Possible Solution**  
Change all occurrences with `print_r('some output', 1)` to `print_r('some output', true)` 

**Additional context**  
See https://github.com/TYPO3-Solr/ext-solr/issues/2753

https://github.com/solariumphp/solarium/blob/5b2cc069b30bd990e9130e7a3b8c54ce4b1fe04a/src/Core/Client/Request.php#L91

and

https://github.com/solariumphp/solarium/blob/5b2cc069b30bd990e9130e7a3b8c54ce4b1fe04a/src/Core/Client/Endpoint.php#L48

**Comment by thomascorthals** [comment]
Thanks for the report. The fix will be included in our next release.
