### ISSUE TITLE
Question regarding Filter Queries keys

### ISSUE THREAD

**Issue by gapsong** [solariumphp/solarium#882]
Hello,

Why are you forced to set a key in a filter-query?
If solarium needs a key, why don't you just has the filter-query itself and set it as a key.
And If you want to set a key explicitly, you can do that aswell.
The whole concept does not make any sense to me.

Best regards 

gapsong

**Comment by mkalkbrenner** [comment]
It is required to retrieve the FIlterQuery form
```php
public function getFilterQuery(string $key): ?FilterQuery {}
```
