### ISSUE TITLE
Small update in docs for range query and excludes

### ISSUE THREAD

**Issue by olahflorin** [solariumphp/solarium#884]
**Solarium version(s) affected**: 6.0.3
**Solr version**:7.7

**Description**  
Didn't know how to make a range query with excludes

**How to reproduce**  

```
$facetSet = $query->getFacetSet();
$facet = $facetSet->createFacetRange('range_field');
$facet->setField('range_field');
$facet->setStart(1);
$facet->setGap(500);
$facet->setEnd(15000);
$facet->getLocalParameters()->addExclude('range_field');
```

This is not working, the getLocalParameters() is not defined

**Possible Solution**  

After some searching through the library i managed to get this to work:

```
$facetSet = $query->getFacetSet();
$facet = $facetSet->createFacetRange(['exclude' => ['range_field']]);
$facet->setKey('range_field');
$facet->setField('range_field');
$facet->setStart(1);
$facet->setGap(500);
$facet->setEnd(15000);
$facetSet->addFacet($facet);
```

**Additional context**  

Is this the right way ? Maybe you can include an example in the docs.
Thank you!

**Comment by mkalkbrenner** [comment]
This on is related: #873

**Comment by thomascorthals** [comment]
It's not clear to me what you're trying to exclude here. You can exclude a filter by its tag name (not its key!) like this:

```php
$query->createFilterQuery('budget')->setQuery($query->getHelper->rangeQuery('price', 50, 180))->addTag('budget');

$facetSet = $query->getFacetSet();
$facet = $facetSet->createFacetRange('allpriceranges');
$facet->setField('price');
$facet->setStart(1);
$facet->setGap(100);
$facet->setEnd(1000);
$facet->getLocalParameters()->addExcludes(['budget']);
```

This will display full facet counts for all ranges. Without the exclude, only the ranges 1–100 and 101–200 have documents to count because of the filter.

You can limit the returned ranges to only those having documents like this:

```php
$facet->setMinCount(1);
```

This can be combined with an exclude to still show full counts without the empty ranges, or used without an exclude to effectively drop all ranges outside the filter (and those within if they happen to be empty).

**Comment by olahflorin** [comment]
@thomascorthals 

Yes, my example was too generic, I was referencing the tag, not the key. I just simplified it and used the same tag and key.

The problem is as follows:
$facet = $facetSet->createFacetRange('allpriceranges');

this return a RangeFacet class which extends an Abstract Facet.

Then you have:
$facet->getLocalParameters()->addExcludes(['budget']);

From what I remember this would fail because the RangeFacet does not have access to getLocalParamenters or addExcludes function.

The only way to set the excludes was using the init function, like this:
$facetSet = $query->getFacetSet();
$facet = $facetSet->createFacetRange(['exclude' => ['range_field']]);
$facet->setKey('range_key');
$facet->setField('range_field');

This only happens for range queries, normal, pivot, multi queries are all ok.

**Comment by thomascorthals** [comment]
> `$facet->getLocalParameters()->addExclude('range_field');`

I overlooked it the first time around, but here's the problem. `LocalParametes` doesn't have a method `addExclude()` (singular). You have to use `addExcludes()` (plural) and pass an array to it.
