### ISSUE TITLE
Error thrown building Request: Extract Query file path/url invalid or not available

### ISSUE THREAD

**Issue by johnBHGW** [solariumphp/solarium#888]
I am trying to get past an error that is being thrown when I try to index one specific file type in my application. I am able to index everything except these files .htm files, they all and in !.htm or !.HTM

Below are the specifics of my server and configurations:

**Application:** Silverstripe -v 4.6 web application
**Servers:** Web server and Solr(stand alone) server are Ubuntu 20.04
**PHP:** version 7.4 
**Apache:** 2.4.46
**Solr version:** 8.7
**Solarium version:** 4.1

composer.json file:

```
    "name": "silverstripe/installer",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=7.1.0",
        "silverstripe/display-logic": "^2.0",
        "undefinedoffset/sortablegridfield": "^2.0",
        "silverstripe/widgets": "^2.0",
        "kinglozzer/metatitle": "^2.0",
        "silverstripe/googlesitemaps": "^2.1",
        "solarium/solarium": "^4.1",
        "silverstripe/recipe-cms": "~4.6",
        "google/recaptcha": "^1.2",
        "colymba/gridfield-bulk-editing-tools": "^3.0.0",
        "wildbit/postmark-php": "^4.0.0",
        "sheadawson/silverstripe-dependentdropdownfield": "^2.0"
    },
    "config": {
        "platform": {
            "php": "7.3.22"
        },
        "process-timeout": 600
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "project-files-installed": [
            "app/.htaccess",
            "app/_config.php",
            "app/_config/mimevalidator.yml",
            "app/_config/mysite.yml",
            "app/src/Page.php",
            "app/src/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "web.config"
        ]
    }
}
```

This is what I am trying to do:

Config.php
```
//Solr Config, this is set to the constant SOLR_CONFIG
$solr_config = array(
    'endpoint' => array(
        'localhost' => array(
            'host' => 'obfuscated',
            'port' => 8983,
            'path' => '/solr/my_core_name/',
        )
    )
);

Indexing-Utility-Class.php

// get solr client
public static function fetchClient()
	{
		return new Solarium\Client(json_decode(SOLR_CONFIG));
	}

//index Statute
public static function IndexStatutes($TitleNumber = null){

    //get files
    Do code ..... 

      //doing a bunch of stuff to make a urlencoded string until we end up with $url
      $url = '/path/to/the/docs/to/index/filename\!\.htm';

       $properties = array(
              //these are all schema relative document properties
         );

//call solerium
$result = self::callSolerium($url, $properties)

return $result;
}
     
// call solerium
public static function callSoleruim($doc_path, $properties) {
		// create a client instance
		$client = self::fetchClient();

		// get an extract query instance and add settings
		$query = $client->createExtract();
		$query->addFieldMapping('content', 'text');
		$query->setUprefix('attr_');
		$query->setFile($doc_path);
		$query->setCommit(true);
		$query->setOmitHeader(false);

		// add document
		$doc = $query->createDocument();
		foreach ($properties as $key => $property) {
			$doc->{$key} = $property;
		}
		$query->setDocument($doc);

		// this executes the query and returns the result
		try {
			
			$result = $client->extract($query); 

                        // Headers use to be needed for docs in SS 3 projects, maybe we will need again ??
			//  $headers = array('Content-Type:multipart/form-data;boundary=gc0p4Jq0M2Yt08jU534c0p');
			//  $request = $client->createRequest($query);
			//  $request->addHeaders($headers);
			//  $result = $client->executeRequest($request);

			echo "<b>Extract query executed</b><br/>\n";
			print_r($properties, true);
			echo 'Query status: ' . $result->getStatus(). "<br/>\n";
			echo 'Query time: ' . $result->getQueryTime(). "<br/>\n";
			return true;

		} catch (Exception $e) {
			// echo 'Exception Message is : ' . $e->getMessage(). "<br/>\n"; 

 // echo '<pre>'; print_r($e); die;    use me if needed for debugging
			return false;
		}
}
```

when I try to call this I am getting the following error messages:

/var/apps/vtleg/public/Documents/Statutes/02/fm401\!\.HTM<br/>
Exception Message is : Extract query file path/url invalid or not available<br/>
/var/apps/vtleg/public/Documents/Statutes/02/fm501\!\.HTM<br/>
Exception Message is : Extract query file path/url invalid or not available<br/>
/var/apps/vtleg/public/Documents/Statutes/02/fm601\!\.HTM<br/>
Exception Message is : Extract query file path/url invalid or not available<br/>

the thing is when I copy that path and execute cat command with the path that was just copied, the documents open up on the server.

When I look at the whole exception I get:
```
<pre>Solarium\Exception\RuntimeException Object
(
    [message:protected] => Extract query file path/url invalid or not available
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /var/apps/vtleg/vendor/solarium/solarium/src/QueryType/Extract/RequestBuilder.php
    [line:protected] => 76
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/apps/vtleg/vendor/solarium/solarium/src/Core/Client/Client.php
                    [line] => 721
                    [function] => build
                    [class] => Solarium\QueryType\Extract\RequestBuilder
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Solarium\QueryType\Extract\Query Object
                                (
                                    [options:protected] => Array
                                        (
                                            [handler] => update/extract
                                            [resultclass] => Solarium\QueryType\Extract\Result
                                            [documentclass] => Solarium\QueryType\Update\Query\Document\Document
                                            [omitheader] => 
                                            [extractonly] => 
                                            [uprefix] => attr_
                                            [file] => /var/apps/vtleg/public/Documents/Statutes/01/ffk01\!\.HTM
                                            [commit] => 1
                                            [document] => Solarium\QueryType\Update\Query\Document\Document Object
                                                (
                                                    [boost:protected] => 
                                                    [modifiers:protected] => Array
                                                        (
                                                        )

                                                    [key:protected] => 
                                                    [fieldBoosts:protected] => Array
                                                        (
                                                            [name] => 
                                                            [literal.name] => 
                                                            [literal.section_id] => 
                                                            [literal.legislature_title] => 
                                                            [literal.legislature_file_title] => 
                                                            [literal.legislature_filename] => 
                                                            [literal.legislature_category] => 
                                                            [literal.parent] => 
                                                            [literal.chapter_id] => 
                                                            [literal.subchapter_id] => 
                                                            [literal.chapter] => 
                                                            [literal.subchapter] => 
                                                        )

                                                    [version:protected] => 
                                                    [helper:protected] => Solarium\Core\Query\Helper Object
                                                        (
                                                            [placeHolderPattern:protected] => /%(L|P|T|)([0-9]+)%/i
                                                            [assembleParts:protected] => 
                                                            [derefencedParamsLastKey:protected] => 0
                                                            [query:protected] => Solarium\QueryType\Update\Query\Document\Document Object
 *RECURSION*
                                                        )

                                                    [filterControlCharacters:protected] => 1
                                                    [fields:protected] => Array
                                                        (
                                                            [name] => 01-001-001-00001
                                                            [literal.name] => 01-001-001-00001
                                                            [literal.section_id] => 00001
                                                            [literal.legislature_title] => General Provisions
                                                            [literal.legislature_file_title] => 011 V.S.A. §§  1-9 Repealed. 2001, No. 30, Section 3.
                                                            [literal.legislature_filename] => Documents/Statutes/01/ffk01!.HTM
                                                            [literal.legislature_category] => statute
                                                            [literal.parent] => 01
                                                            [literal.chapter_id] => 001
                                                            [literal.subchapter_id] => 001
                                                            [literal.chapter] => VERMONT STATUTES ANNOTATED
                                                            [literal.subchapter] => STATUTORY REVISION COMMISSION; CONTINUOUS REVISION
                                                        )

                                                )

                                        )

                                    [fieldMappings:protected] => Array
                                        (
                                            [content] => text
                                        )

                                    [helper:protected] => 
                                    [params:protected] => Array
                                        (
                                        )

                                )

                        )

 )
```

I have tried using the other request type with the headers included, but that does not fix the issue. All of the other document types indexed relatively well with minimal errors using either of the two request types(with headers and without). Why would these .htm files be causing such problems?

Am I doing something wrong with the library? I know 4.1 is a little old but Solr is running as a stand alone service and everything else seemed to run fine without issue. Is there no way to handle these file types? They are documents retrieved by our client from a LEXIS query and then they are uploaded to thier server. All of the filenames have multiple special characters in them and they all end with an ! so it is file!.htm or file!.HTM

**Comment by thomascorthals** [comment]
You mustn't do this:
```php
$url = '/path/to/the/docs/to/index/filename\!\.htm';
```
but this:
```php
$url = '/path/to/the/docs/to/index/filename!.htm';
```

Inside a single quoted string, the `\`s are treated as a literal character (except for the sequences `\'` and `\\`).

Admittedly, it would be more useful to show the filename in the exception message. You would've caught it right away. I'll open a PR for that.

**Comment by johnBHGW** [comment]
Thank you for the error handling fix, thats what I was hoping to get clarification on. Please note however that the method of using the single quotes to wrap the path does not work if there are spaces in the filename, or special characters.

**Comment by thomascorthals** [comment]
Do you mind holding off until my PR gets merged? Or can you test against [my branch](https://github.com/thomascorthals/solarium/tree/integration) in the meantime? I'm happy to help you figure this out but it would be really useful to see if the erroring filenames are what they should be to start with.

**Comment by johnBHGW** [comment]
I don't mind at all, the challenge for me here is that I am working on a severely locked down government server, updating their SOLR install. 
  When I tried to upgrade from Solarium 4.1 to something newer I had terrible problems with their code auditing software calling out the changes I had to make to trying to get the new version to run. 
That coupled with a cyber security "expert" who is likely only 2 years removed from his online cyber security degree makes me try to keep using the 4.1 version if I can get it to work. 
  I am trying to handle files that are uploaded by another entity and as such the file names and paths have a variety of makeups:
1. File paths can potentially have one or more spaces throughout, because people like to name the folders with spaces
2. File paths can also have spaces replaced with either a - char or a ~ char
3. File names can have spaces and or a variety of special characters:   ~ , - ,  @ , ! , # , $ , ¦ , §
    a. I think the last two chars are designated    ¦ - U+00A6 : BROKEN BAR  and  § - U+00A7 : SECTION SIGN
4. file extensions can be of type:  .pdf, .html, .htm, .url, .txt, .tmp, .mp3, and a few other obscure types. 
    a.  Really the only file types/extensions that I am trying to handle in  $client --> extract(  ) are .pdf or .htm or .html 

Here is an example of the last attempt I just made with some debugging output: 
 `print_r($file);`  placed on:  line 68 in `solarium/solarium/src/QueryType/Extract/RequestBuilder.php`

'/var/apps/vtleg/public/Documents/2016/Docs/ACTS/ACT001/ACT001 Act Summary.pdf'

if I run cat '/var/apps/vtleg/public/Documents/2016/Docs/ACTS/ACT001/ACT001 Act Summary.pdf' from the command line where I just recieved the error I get the files attempt at opening(all of the garbage spit out from the .executable)

Please let me know if you need anymore details, I have adjusted the Exception output so it does tell me now where the problem is coming from.

**Comment by thomascorthals** [comment]
I've added a couple of files with special characters in their file names to the integration test in PR #890. Solarium/Solr/Tika can handle all of them. The Extract request builder hasn't really changed between `4.x` and `master` (the only difference is the addition of type hinting to function signatures).

Could it be something about the way you get the filenames? Do you get them from the disk? Or are they supplied in an external source (text file, database …)? One thing that comes to mind is some invisible character that got appended to the name in that source. It would be part of the filename string in PHP and cause a mismatch. But that's just a guess.

**Comment by johnBHGW** [comment]
The Files are located on the same Ubuntu server that I am running the index task from. I am grabbing them from within a php service. I have tried a couple of different means to get them, I have used:
$url = dirname(__FILE__) . '/../../../public/'.$file->Filename
I have also used:
$url = '/hand/written/path/to/directory/with/files/' . $file->Filename
The filename is always coming from mysql, but the problem thinking that it is coming from there is that 85% of the documents do index properly. Also when I output the filename it comes back as a valid string, additionally I am stripping leading or tailing whitespaces and whatnot.

this is where I am grabbing the file records from the database:

//find the Bill files
$JournalFiles = LegislatureFile::get()->filter(array(
     'Type' => 'File',
     'ParentID' => $folder_ids,
     'IsSolrIndexed' => 0
));

   foreach($JournalFiles as $file) {
	    LegSolr::indexSingleJournal($file, $biennium, $sessionId, $database);
   }

public static function indexSingleJournal($file = null, $biennium = null, $sessionId = null, $database = null) //JD: borrowed from indexSingleBill
	{
		$settings = null;
		//if $biennium is null get it from url
		if(!$biennium) {
			//get third part of exploded $file->Filename
			$path_parts = explode('/', $file->Filename);
			$RefValue = $path_parts[1];
			$settings = LegislatureSettings::get()->filter(array('RefValue' => $RefValue))->First();
			$biennium = $settings->RefValue;
		}

		//if $sessionId is null get it
		if(!$sessionId && $settings)
			$sessionId = $settings->RefId;

		//if $database is null get it
		if(!$database && $settings)
			$database = $settings->RefRelated;

		//get files parent folder
		$folder = LegislatureFile::get()->filter(array(
			'Type' => 'Folder',
			'ID' => $file->ParentID
		))->First();

		//if biennium and sessionId and database
		if($file && $biennium && $sessionId && $database) {
			//fix the url so it is url encoded
			$url = dirname(__FILE__) . '/../../../public/'.$file->Filename;
			echo $url."<br/>\n";

			//Get journal information from filename
			//$db = LegSQL::fetchDB($database);
			$body = substr($file->Name, 0, 2);
			$date = intval($file->Name);

			$properties = array(
				'name' => $file->ID,
				'literal.name' => $file->ID,
				'literal.legislature_title' => iconv("UTF-8","ISO-8859-1//TRANSLIT", $file->Name),
				'literal.legislature_file_title' => $file->Name,
				'literal.legislature_filename' => $file->Filename,
				'literal.biennium' => $biennium,
				'literal.legislature_category' => 'journal',
				'literal.parent' => $body,
				'literal.related' => $date
				// 'literal.legislature_keywords' => $bill_keywords
			);

			if($file->ID > 0) {
				//  self::addAndCommitSolrDocument($properties, $url);
				$result = self::callSoleruim($url, $properties);
				if($result) {
					$file->IsSolrIndexed = 1;
					$file->write();
				}
			}
		}
	}

But like I said I have stepped through every where I can think to check the value of $url before it gets sent to Solarium and it always looks like a valid filename, and I can find the file by that path on the server. using cat or another program to access it.

Thank you for your continued support on this.

**Comment by thomascorthals** [comment]
Can you try this?

```php
$url = realpath(dirname(__FILE__) . '/../../../public/'.$file->Filename);
var_dump($url);
```
It'll either output a string with the absolute path to the file if it exists, `bool(false)` if the file doesn't exists, or `NULL` and emit a warning if the path is invalid (i.e. contains a null byte).

**Comment by johnBHGW** [comment]
here is the output of that var_dump:
string(76) "/var/apps/vtleg/public/Documents/2010/Docs/ACTS/ACT004/ACT004 As Enacted.pdf"

**Comment by thomascorthals** [comment]
That proves the filename does match with what's on disk. Can you try something else?

```php
$url = realpath(dirname(__FILE__) . '/../../../public/'.$file->Filename);
var_dump(is_readable($url));
```
It this outputs `bool(false)`, the script doesn't have read access to the file. This happens if the file has `600` or `660` as permissions and isn't owned by the user running the script.

**Comment by johnBHGW** [comment]
The output is:   **bool(true)**

**Comment by thomascorthals** [comment]
That's odd. It's the exact same check that determines whether to add the file to the request or throw the exception you're encountering.

https://github.com/solariumphp/solarium/blob/4dfd71fefb307cac1ec394b672f2f57256752e4b/src/QueryType/Extract/RequestBuilder.php#L67-L77

Can you try this right before that `if`?

```php
var_dump($file);
var_dump(realpath($file));
var_dump(is_readable($file));
```

It'll tell you the path of the file as you're trying to add, how the path is resolved, and if the script can read the file at that point.

**Comment by johnBHGW** [comment]
here is the output:

string(76) "/var/apps/vtleg/public/Documents/2010/Docs/ACTS/ACT004/ACT004 As Enacted.pdf"
........end of var_dump.......

string(76) "/var/apps/vtleg/public/Documents/2010/Docs/ACTS/ACT004/ACT004 As Enacted.pdf"
........end of var_dump.......

bool(true)
.............END of SOLARIUM TESTS....................

The stuff after each of the commands are output by me

**Comment by thomascorthals** [comment]
And you still get the exception after that? That really shouldn't happen …

**Comment by johnBHGW** [comment]
I get the exception for some of the files, but not all of them. I would say about 10% of them throw.

**Comment by thomascorthals** [comment]
What's the output of those last 3 `var_dump`s for a file that does result in an exception?

**Comment by johnBHGW** [comment]
Here is the output of the first error thrown when I try to re-index the BILLS folder now:

/var/apps/vtleg/public/Documents/2016/Docs/BILLS/H-0039/H-0039 As Introduced.pdf  <br/> 
Exception Message: Solr HTTP error: OK (500)
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /solr/vtleg/update/extract. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>org.apache.solr.common.SolrException: URLDecoder: Invalid character encoding detected after position 182 of query string / form data (while parsing as UTF-8)
	at org.apache.solr.servlet.SolrRequestParsers.decodeChars(SolrRequestParsers.java:421)
	at org.apache.solr.servlet.SolrRequestParsers.decodeBuffer(SolrRequestParsers.java:437)
	at org.apache.solr.servlet.SolrRequestParsers.parseFormDataContent(SolrRequestParsers.java:404)
	at org.apache.solr.servlet.SolrRequestParsers.parseQueryString(SolrRequestParsers.java:304)
	at org.apache.solr.servlet.SolrRequestParsers.parseQueryString(SolrRequestParsers.java:274)
	at org.apache.solr.servlet.HttpSolrCall.&lt;init&gt;(HttpSolrCall.java:181)
	at org.apache.solr.servlet.SolrDispatchFilter.getHttpSolrCall(SolrDispatchFilter.java:429)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:374)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:323)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.base/java.lang.Thread.run(Thread.java:834)
</pre>

</body>
</html>
<br/>
  


And HERE is the output of those 3 `var_dumps`:

/var/apps/vtleg/public/Documents/2016/Docs/BILLS/H-0039/H-0039 As Introduced.pdf<br/> 
string(80) "/var/apps/vtleg/public/Documents/2016/Docs/BILLS/H-0039/H-0039 As Introduced.pdf"
             
             
string(80) "/var/apps/vtleg/public/Documents/2016/Docs/BILLS/H-0039/H-0039 As Introduced.pdf"
             
             
bool(true)


The problem is that the only way that I can get the application to use the file that I know to have thrown the exception it to replace the         $url = __DIR__ . '/public/'. $file->Filename;      _with_         
just a string        $url = "/var/apps/vtleg/public/Documents/2016/Docs/H-0039/H-0039 As Introduced.pdf" 
So I dont know if that is skewing the results.

**Comment by thomascorthals** [comment]
You're running into a different issue here:
```
org.apache.solr.common.SolrException: URLDecoder: Invalid character encoding detected after position 182 of query string / form data (while parsing as UTF-8)
```
Feel free to go ahead an open a separate issue.

On the topic of this issue, I'd like to see the output for files of the form `/var/apps/vtleg/public/Documents/Statutes/02/fm601!.HTM`. It will be interesting to see what `realpath` and `is_readable` have to say.

**Comment by johnBHGW** [comment]
ok here is that output for exception message:

/var/apps/vtleg/app/src/VTLeg/public/Documents/Statutes/01/ffk01!.HTM
Exception Message is : Extract query file path/url invalid or not available

using the original method of getting file path :    $url = __DIR__ . '/public/' . $file->Filename;

var_dump 1: string(69) "/var/apps/vtleg/app/src/VTLeg/public/Documents/Statutes/01/ffk01!.HTM"
             
             
var_dump 2:   bool(false)
             
             
var_dump 3:  bool(false)

**Comment by thomascorthals** [comment]
The file path does look correct and you'll be able to `cat` that file _as the correct user_ (file owner or member an appropriate usergroup). The user under which the PHP script is running, however, has no read access to the file. Try these in a shell:
```bash
ls -l /var/apps/vtleg/public/Documents/2016/Docs/BILLS/H-0039
ls -l /var/apps/vtleg/app/src/VTLeg/public/Documents/Statutes/01
```
You'll either see that the first has `-rw-r--r--

**Comment by johnBHGW** [comment]
they both have the following permissions:
rwxrwxr-x    1 bhg www-data
with the bhg being our companies username

**Comment by thomascorthals** [comment]
Can you reach both files from the web browser, seeing as they both belong to the `www-data` group?

**Comment by johnBHGW** [comment]
The files in those locations are accessible to the web application for download or viewing. That is why they are stored there and belong to that group. 
Those particular few files are not however. They throw the error.

**Comment by thomascorthals** [comment]
Do you run the script under the same user as the web application?

**Comment by johnBHGW** [comment]
Yes. The script is run by the bhg user when I run it manually, or it is run by the application(www-data)


 The only thing that is different about anything in application or the logic since the last time these indexes were run is:
 that the server is newer(updated to -version 20 from -version 16),
that php is newer 7.4 from 7.2

also for whatever reason the logic for getting to the file path is a little different now. 
It used to be that the code snippet to get the path looked like: $url = dirname(__FILE__) . '/../../../public/'.$file->Filename
this was run from the /var/apps/vtleg/app/src/VTLeg/VTLegSolr.php class so by going up, up, up, then public/Documents/....
worked fine. But now that yields the incorrect path /var/apps/vtleg/app/src/VTLeg/../../../public/Documents/Statutes/01/ffk01!.HTM
It does not seem to be doing what it is supposed to be doing, instead it is including the directory the task is run from and the /../../../ characters as well.
So we have changed the function to just use a string for the base path, this gives us the correct path(/var/apps/vtleg/public/Documents/Statutes/01/ffk01!.HTM), but we are now seeing these errors.

**Comment by johnBHGW** [comment]
I am putting this(specific exception message) on the back burner for a bit. I want to look into the other issue because the files that throw that exception fail 100% of the time. I will start a different issue like you asked. 
You can close this for now if you would like
