### ISSUE TITLE
Deprecation message with symfony 5.2

### ISSUE THREAD

**Issue by mjag8** [solariumphp/solarium#898]
**Solarium version(s) affected**: 5.2.0
**PHP verison**: 7.4.12
**Symfony verison**: 5.2

**Description**
The following message is given after I made some holistic upgrade
`Since symfony/event-dispatcher 5.1: Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy is deprecated, use the event dispatcher without the proxy.`

**How to reproduce**
Following the docs:
```
$adapter = new \Solarium\Core\Client\Adapter\Curl();
$eventDispatcher = new \Symfony\Component\EventDispatcher\EventDispatcher();
$client = new \Solarium\Client($adapter, $eventDispatcher);
```
Probably will be just replaced in solarium 6, but not sure

**Comment by mkalkbrenner** [comment]
You should update to solarium 6.0.4. I think we already addressed that issue.

**Comment by mkalkbrenner** [comment]
no further feedback
