### ISSUE TITLE
When a grouping group returns 0 results solarium raise exception

### ISSUE THREAD

**Issue by etcware** [solariumphp/solarium#913]
**Solarium version(s) affected**: 6.0.4
**Solr version**:8.6.3

**Description**  
I get this error:
`
 Severity: error --> Exception: Argument 4 passed to Solarium\Component\Result\Grouping\QueryGroup::__construct() must be of the type float or null, string given, called in /Users/alendo/Sites/didatticaweb/vendor/solarium/solarium/src/Component/ResponseParser/Grouping.php on line 102 /Users/alendo/Sites/didatticaweb/vendor/solarium/solarium/src/Component/Result/Grouping/QueryGroup.php 71
`
**How to reproduce**  
The query result has a group with 0 documents, like this:
``
{
  "grouped":{
    "tipo_s:corso":{
      "matches":66,
      "doclist":{"numFound":0,"start":0,"maxScore":"NaN","numFoundExact":true,"docs":[]
      }}...
``
**Possible Solution**  
The error is raised because $maxScore value is "NaN".
I added this row before 
/Users/alendo/Sites/didatticaweb/vendor/solarium/solarium/src/Component/ResponseParser/Grouping.php line 102:

if (is_string($maxScore)) $maxScore=null;

**Additional context**

**Comment by thomascorthals** [comment]
It looks like you've encountered [SOLR-13839](https://issues.apache.org/jira/browse/SOLR-13839). JSON doesn't define a representation of `NaN`. It should be returned as `"maxScore":null`.

According to that issue, it only occurs when you fetch the score with your query. Solarium's default field list is `*,score`. If you don't need the score, you should be able to work around it with `$query->setFields('*');`.

**Comment by etcware** [comment]
> It looks like you've encountered [SOLR-13839](https://issues.apache.org/jira/browse/SOLR-13839). JSON doesn't define a representation of `NaN`. It should be returned as `"maxScore":null`.
> 
> According to that issue, it only occurs when you fetch the score with your query. Solarium's default field list is `*,score`. If you don't need the score, you should be able to work around it with `$query->setFields('*');`.

Thanks it works. But in any case I suggest to implement a control if fields are of the expected type/value.
