### ISSUE TITLE
[Documentation] PHP Solr Extension required?

### ISSUE THREAD

**Issue by Ninja-007** [solariumphp/solarium#925]
Thanks for providing the library.

Does it need PHP Solr extension as a requirement?
My hosting does not have PHP Solr extension. :(
http://docs.php.net/manual/en/book.solr.php

**Comment by thomascorthals** [comment]
You don't need it.

**Comment by Ninja-007** [comment]
Thanks.
I am trying to download tthe repo as zip file. But only src folder is getting downloaded.
Is it normal?

**Comment by thomascorthals** [comment]
The `src` folder is the only one you need to use Solarium as a library in a production environment.

`docs` contains the source files to build the documentation at https://solarium.readthedocs.io/. It's easier to read it there.

`examples` contains examples scripts that demonstrate basic tasks you can carry out with Solarium. You can run them against the techproducts example index, or use them as a starting point for building your own application.

`tests` contains unit and integration tests. You don't need them until you start contributing code to the project. Although you could consider the integration tests as another example of working code.

If at all possible, you should consider using Composer to install Solarium.

```shell
composer require solarium/solarium
```
