### ISSUE TITLE
ParallelExecution: Misleading annotations in getQueries method

### ISSUE THREAD

**Issue by ismailcherri** [solariumphp/solarium#927]
The PHP [annotation](https://github.com/solariumphp/solarium/blob/master/src/Plugin/ParallelExecution/ParallelExecution.php#L80) in the `getQueries()` method says it should return an array of `QueryInterface` while it returns an array of query + endpoint.

This can be misleading and can lead to someone using the return type directly without knowing that it is actually a different type of array.

**Comment by thomascorthals** [comment]
Good catch!

The description is also wrong. It returns the key of an endpoint with the query, not a client instance.
