### ISSUE TITLE
Uncaught exception 'Solarium_Client_HttpException' error

### ISSUE THREAD

**Issue by balmydrizzle** [solariumphp/solarium#93]
Got this when run example 'Select query params', the complete error messages are as follows:

<html><head><title>Solarium examples</title></head><body><br />
<b>Fatal error</b>:  Uncaught exception 'Solarium_Client_HttpException' with message 'Solr HTTP error: Bad Request (400)' in C:\AppServ\www\Solarium-2.4.0\library\Solarium\Result.php:98
Stack trace:
#0 C:\AppServ\www\Solarium-2.4.0\library\Solarium\Client.php(535): Solarium_Result-&gt;__construct(Object(Solarium_Client), Object(Solarium_Query_Select), Object(Solarium_Client_Response))
#1 C:\AppServ\www\Solarium-2.4.0\library\Solarium\Client.php(555): Solarium_Client-&gt;createResult(Object(Solarium_Query_Select), Object(Solarium_Client_Response))
#2 C:\AppServ\www\Solarium-2.4.0\library\Solarium\Client.php(651): Solarium_Client-&gt;execute(Object(Solarium_Query_Select))
#3 C:\AppServ\www\Solarium-2.4.0\examples\2.1.1-query-params.php(25): Solarium_Client-&gt;select(Object(Solarium_Query_Select))
#4 {main}

  thrown in <b>C:\AppServ\www\Solarium-2.4.0\library\Solarium\Result.php</b> on line <b>98</b><br />

```
The code in Result.php is:


        // check status for error (range of 400 and 500)
        $statusNum = floor($response->getStatusCode() / 100);
        if ($statusNum == 4 || $statusNum == 5) {
            throw new Solarium_Client_HttpException(
                $response->getStatusMessage(),
                $response->getStatusCode()
            );
        }

The error occurs at throw statement, what's wrong?
```

**Comment by mohanstar13** [comment]
how can we use multiple core in solarium..pls give me example
