### ISSUE TITLE
Fatal Error with Symfony EventDispatcher

### ISSUE THREAD

**Issue by milothatch** [solariumphp/solarium#932]
I am new to solarium.
While trying to use codes from examples, I permanently get "Fatal error: Uncaught Error: Class 'Symfony\Component\EventDispatcher\EventDispatcher' not found in init.php" at the code line $eventDispatcher = new EventDispatcher() - up to this line everything seems to work fine.
Solarium was installed today using composer, as described in "Getting started" on https://solarium.readthedocs.io
Examples downloaded with git client, folder vendor\symfony\event-dispatcher-contracts\ contains Event.php and EventDispatcherInterface.php
Do I miss something in respect to installation? Where is the class 'Symfony\Component\EventDispatcher\EventDispatcher' defined?

**Comment by thomascorthals** [comment]
How did you install it?

If you check out the project from Github, you must run `composer install` in the project root first. That will install all dependencies needed for running the included examples (and tests).

If you install Solarium in your application through Composer, you must also separately install a PSR-15 compatible event dispatcher (e.g. `symfony/event-dispatcher`).

**Comment by milothatch** [comment]
You made my day, it seems :-)
Thank you very much!
