### ISSUE TITLE
Codecov.io integration is broken

### ISSUE THREAD

**Issue by mkalkbrenner** [solariumphp/solarium#933]
Since two weeks ago, codecov.io answers the webhooks with 403.

Any action I try in the codecov.io user interface leeds to permission denied.
I followed a recommendation to delete the webhhook in github and to recreate it using the codecov UI.
The result is an error message:

Sorry, there was an issue
Cannot find webhook 216909372

Now we're lost :-(

It isn't possible to delete our account or data ... permission denied. 

Very similar to https://github.com/mattermost/mattermost-plugin-webex/issues/35

I assume that the our solariumphp organization causes this trouble. It seems that codecov changed something for organizations or teams. For me this look like bugs.

Maybe we need to wait some time and try again.

**Comment by mkalkbrenner** [comment]
It looks like the issue is related to the solariumphp organization.
@basdenooijer is still the owner and I don't have administration privileges for the organization.

**Comment by basdenooijer** [comment]
@mkalkbrenner I approved the plugin, also made you an organization admin

**Comment by mkalkbrenner** [comment]
Thanks @basdenooijer !

**Comment by mkalkbrenner** [comment]
@thomascorthals

After a lot of trial and error I managed to upload the coverage reports again. Unfortunately there's an error when the processing happens. But the error itself is hidden or emtpy!

I invited you to the solariumphp organization. Once you accept this invitation you should be able to login to codecov.io and access the solarium results (after selecting the organization). Maybe you have an idea what is going on.

BTW I added https://github.com/solariumphp/solarium/blob/master/codecov.yml to create fixes.
And I changed to upload to collect all reports from the entire matrix and to upload them at once.

**Comment by thomascorthals** [comment]
@mkalkbrenner 

The yaml is invalid according to Codedov:
```shell
$ cat codecov.yml | curl --data-binary @- https://codecov.io/validate
Error at ['codecov', 'fixes']:
extra keys not allowed

```

Unfortunately, my first hunch didn't work out. I had expected consequent commits to be successful because they should have a valid base commit to compare against. Unfortunately, the very vaguely described error still occurs.

**Comment by mkalkbrenner** [comment]
@thomascorthals I committed a valid codecov.yml now. Let's see what happens.

**Comment by mkalkbrenner** [comment]
Unfortunately there's still an error in the processing. But they don't provide any details.

**Comment by thomascorthals** [comment]
> @thomascorthals I committed a valid codecov.yml now. Let's see what happens.

Nothing changed because both the invalid version and this one were never read by Codecov for some reason:

https://github.com/solariumphp/solarium/runs/2906641398?check_suite_focus=true#step:4:34

**Comment by mkalkbrenner** [comment]
@thomascorthals I got it to work :-)

I improved the process by sending all reports at once. But I missed to checkout solarium for the upload process.
Another advantage is that you can now download the results as artefacts.
