### ISSUE TITLE
Option to configure "/solr" in base-path

### ISSUE THREAD

**Issue by jschultze** [solariumphp/solarium#938]
When using Solarium in a recent project, I needed to connect to a Solr instance that is using `/index` instead of `/solr` in the url. As far as I can see, there's no way to configure or change this base-path when setting up a Solarium-client. In fact, it seems that `/solr` has been hardcoded with version 2 of the API.

An option to change this setting, while keeping the default as `/solr`, would improve the usability of Solarium.

**Comment by thomascorthals** [comment]
This was discussed in #853. It will get implemented someday. In the meantime, you can work around it by extending the cURL adapter. Override `createHandle` with a method that calls the parent and then replaces the path of the URI for the handle before returning it.

**Comment by jschultze** [comment]
Thanks for the info and sorry for the double post! I extended the Endpoint for now but will have a look if the suggested extension of the cURL adapter works better.

**Comment by thomascorthals** [comment]
Since [Solarium 6.2.1](https://github.com/solariumphp/solarium/releases/tag/6.2.1), this can be done without workarounds by adding a `context` to the endpoint configuration. It will default to `solr` if omitted.

```php
$config = [
    'endpoint' => [
        'localhost' => [
            'scheme' => 'http', # or https
            'host' => '127.0.0.1',
            'port' => 8983,
            'path' => '/',
            'context' => 'index',
            'core' => 'techproducts', # or collection
        ]
    ]
];
```

**Comment by jschultze** [comment]
Thanks a lot for the addition of this configuration setting!
