### ISSUE TITLE
Compile Error when creating a new document using symfony command service

### ISSUE THREAD

**Issue by asajedi** [solariumphp/solarium#947]
**Solarium version(s) affected**: 5.x-dev
**Solr version**:8.0

**Description**  
When trying to create a new document using Symfony command which calls a controller action the following error message ist being output:
Compile Error: Solarium\QueryType\Update\Query\Document::__set(): Return type must be void when declared 
If the controller action is called via http it works fine.

**How to reproduce**  
   In Symfony command

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
       $this->myController->myDocument();
    }
   
   In the contoller

    public function myDocument(): void
    {
        $update = $this->client->createUpdate();
        $doc = $update->createDocument();
        $doc->id = 1;
        $update->addDocument($doc);
        $this->client->execute($update);
    }

    Calling createDocument causes the problem here.

**Possible Solution**  

**Additional context**

**Comment by thomascorthals** [comment]
I think it's `$doc->id = 1` that's actually causing the problem. The assignment invokes the magic setter `__set()` and that method used to return the `Document` instance, which it shouldn't do.

This is fixed now. If you can upgrade to Solarium 6, the problem will disappear.
