### ISSUE TITLE
Merge latest PR -> 6.2.2 ? (Support for PHP 8.1)

### ISSUE THREAD

**Issue by oakleaf** [solariumphp/solarium#973]
Hi, not a bug but a wish to release a new version, 6.2.2 from the existing PR, since one of the includes a fix for PHP 8.1 (http_build_query null -> ""). It seems that it's possible to just release the version?

Thanks

**Comment by mkalkbrenner** [comment]
I just created a 6.2.2 release for PHP 8.1 compatibility.
